# What the picture should show for each of the 320 base catalog ids.
# Abstract words (pronouns, prepositions, question words) get a concrete,
# AAC-conventional scene so the picture reads at a glance on a tile.

SUBJECTS = {
    # core
    "i_me": "a smiling child pointing at their own chest",
    "you": "a child pointing straight forward at the viewer",
    "he": "a smiling boy with short hair, portrait",
    "she": "a smiling girl with a ponytail, portrait",
    "they": "three children of different heights standing together",
    "we": "two children with arms around each other's shoulders, smiling",
    "it": "a hand pointing at a red rubber ball",
    "want": "a child reaching both hands toward a toy with a hopeful face",
    "like": "a child hugging a teddy bear with a big smile and small hearts",
    "dont_like": "a child pushing away a plate of broccoli with a grimace",
    "need": "a child with a raised hand and a bright exclamation mark",
    "more": "a child holding out an empty bowl toward a pot of food, a plus sign",
    "help": "a child with one hand raised high and a worried face, an adult hand reaching toward them",
    "stop": "a red octagon stop sign held by a child with an open palm",
    "go": "a bright green traffic light and a child running forward",
    "yes": "a big green check mark next to a nodding child giving a thumbs up",
    "no": "a big red X next to a child shaking their head with a hand up",
    "good": "a gold star and a child giving a thumbs up",
    "bad": "a child frowning next to a broken toy with a gray cloud",
    "look": "a child with wide eyes looking through binoculars",
    "see": "a big open eye with a child pointing at it",
    "get": "a child grabbing a box from a shelf",
    "give": "a child handing a wrapped gift to another child",
    "put": "a child placing a toy into an open box",
    "make": "a child building a small model with a hammer and blocks",
    "open": "a child opening a door that is halfway open",
    "close": "a child closing a door, almost shut",
    "turn": "a child turning a big round knob, with a curved arrow",
    "turn_on": "a hand flipping a light switch up with a glowing bulb",
    "turn_off": "a hand flipping a light switch down with a dark bulb",
    "again": "two circular arrows forming a loop around a child clapping",
    "all_done": "a child pushing away an empty plate with a checkered finish flag",
    "wait": "a child sitting on a chair with hands folded, an hourglass beside them",
    "now": "a clock with the word-free face and a big arrow pointing at it, a child pointing down",
    "later": "a clock with an arrow curving forward and a child holding up one finger",
    "here": "a big red map pin next to a child pointing at the ground",
    "there": "a child pointing far away at a distant house",
    "what": "a big question mark and a child with a puzzled face and open hands",
    "where": "a map with a location pin and a child looking around",
    "who": "a silhouette of a person with a question mark on the chest",
    "when": "a calendar and a clock together with a question mark",
    "why": "a child scratching their head with a thought bubble holding a question mark",
    "how": "gears turning next to a child holding a wrench, question mark",
    "my_turn": "a child pointing at their own chest while a friend waits, small arrow",
    "your_turn": "a child gesturing toward a friend to go next, small arrow",
    "big": "one huge gray elephant filling the whole frame",
    "little": "one tiny gray mouse, very small in the center of the frame with lots of empty space around it",
    "fast": "a cheetah running with speed lines",
    "slow": "a turtle walking slowly with a snail",
    "in": "a cat inside a cardboard box",
    "out": "a cat stepping out of a cardboard box",
    "on": "a cat sitting on top of a box",
    "off": "a cat jumping off a box",
    "up": "a big upward arrow with a child pointing up at a balloon",
    "down": "a big downward arrow with a child pointing down at the floor",
    "same": "two identical red apples side by side",
    "different": "a red apple next to a yellow banana",
    "break": "a child relaxing on a beanbag with a pause symbol",
    # feelings
    "happy": "a child with a huge joyful smile and sparkles",
    "sad": "a child with a downturned mouth and a single tear",
    "mad": "a child with a red angry face, furrowed brows and clenched fists",
    "excited": "a child jumping with arms up and stars around them",
    "tired": "a child yawning and rubbing their eyes with droopy eyelids",
    "sick": "a child in bed with a thermometer and a green tinted face",
    "hurt": "a child holding a scraped knee with a bandaid and a tear",
    "scared": "a child hiding under a blanket with wide eyes",
    "silly": "a child crossing their eyes and sticking out their tongue",
    "surprised": "a child with wide eyes and mouth open, hands on cheeks",
    "calm": "a child sitting cross-legged with closed eyes and a gentle smile",
    "proud": "a child with chest out holding a gold medal",
    "nervous": "a child biting their nails with sweat drops",
    "bored": "a child slumped on a couch with a blank stare",
    "confused": "a child with a tilted head and question marks around them",
    "loved": "a child being hugged by a parent surrounded by hearts",
    "shy": "a child peeking from behind a curtain with pink cheeks",
    "hungry": "a child holding their empty tummy and looking at a sandwich",
    "thirsty": "a child with a dry tongue out reaching for a glass of water",
    "hot_feeling": "a child sweating and fanning themselves under a blazing sun",
    "cold_feeling": "a child shivering in a scarf with blue cheeks and snowflakes",
    "too_loud": "a child covering their ears with a pained face and sound waves",
    "frustrated": "a child with gritted teeth and steam coming from their ears",
    "worried": "a child chewing a lip with furrowed brows and a gray cloud",
    # food
    "pizza": "a slice of pepperoni pizza", "burger": "a cheeseburger with lettuce and tomato",
    "french_fries": "a red carton of french fries", "hotdog": "a hot dog with mustard",
    "sandwich": "a sandwich with lettuce, cheese and ham", "taco": "a crunchy taco",
    "burrito": "a wrapped burrito cut to show the filling", "pasta": "a bowl of spaghetti with tomato sauce",
    "rice": "a bowl of white rice with a spoon", "chicken": "a roasted chicken drumstick",
    "apple": "a shiny red apple", "banana": "a yellow banana",
    "orange_fruit": "an orange with one slice", "strawberries": "three red strawberries",
    "grapes": "a bunch of purple grapes", "watermelon": "a slice of watermelon",
    "pineapple": "a pineapple", "carrots": "three orange carrots with green tops",
    "broccoli": "a floret of broccoli", "corn": "an ear of corn with butter",
    "bread": "a loaf of bread with a slice", "cereal": "a bowl of cereal with milk and a spoon",
    "pancakes": "a stack of pancakes with syrup and butter", "waffles": "a waffle with syrup and strawberries",
    "eggs": "a fried egg in a pan", "cheese": "a wedge of yellow cheese",
    "soup": "a steaming bowl of soup", "salad": "a bowl of green salad",
    "cookie": "a chocolate chip cookie", "cake": "a slice of layered cake",
    "cupcake": "a cupcake with pink frosting and sprinkles", "ice_cream": "an ice cream cone with two scoops",
    "donut": "a pink frosted donut with sprinkles", "popcorn": "a striped bucket of popcorn",
    "chocolate": "a chocolate bar partly unwrapped", "candy": "colorful wrapped candies",
    "crackers": "a stack of square crackers", "yogurt": "a cup of yogurt with a spoon and berries",
    "chips_snack": "a bag of potato chips", "muffin": "a blueberry muffin",
    # drinks
    "water": "a clear glass of water", "milk": "a glass of milk with a carton",
    "chocolate_milk": "a glass of chocolate milk with a straw", "apple_juice": "a glass of apple juice next to an apple",
    "orange_juice": "a glass of orange juice next to an orange", "juice_box": "a juice box with a straw",
    "lemonade": "a glass of lemonade with a lemon slice", "hot_chocolate": "a mug of hot chocolate with marshmallows",
    "smoothie": "a purple berry smoothie in a cup with a straw", "tea": "a teacup with a tea bag",
    "soda": "a soda can with bubbles", "ice_water": "a glass of ice water with ice cubes",
    "bottle": "a baby bottle of milk", "milkshake": "a milkshake with whipped cream and a straw",
    # actions
    "eat": "a child eating with a fork from a plate", "drink_act": "a child drinking from a cup",
    "play_act": "a child playing with blocks and a toy car", "sleep": "a child sleeping in bed with Zs",
    "walk": "a child walking on a path", "run": "a child running with speed lines",
    "jump": "a child jumping in the air with arms up", "swim": "a child swimming in a pool",
    "read": "a child reading an open book", "write": "a child writing with a pencil on paper",
    "draw": "a child drawing a picture with a crayon", "sing": "a child singing into a microphone with notes",
    "dance": "a child dancing with music notes", "wash_hands": "hands being washed with soap and water",
    "brush_teeth": "a child brushing their teeth", "hug": "two children hugging",
    "listen": "a child cupping a hand to their ear with sound waves", "watch": "a child watching a TV",
    "sit": "a child sitting on a chair", "stand": "a child standing up straight",
    "cut": "a child cutting paper with safety scissors", "glue": "a child gluing paper with a glue stick",
    "clean_up": "a child putting toys into a bin", "push": "a child pushing a big box",
    "pull": "a child pulling a wagon", "climb": "a child climbing a ladder",
    "throw": "a child throwing a ball", "catch": "a child catching a ball with both hands",
    # people
    "mom": "a smiling mother with shoulder-length hair, portrait", "dad": "a smiling father with short hair, portrait",
    "grandma": "a smiling grandmother with gray hair and glasses, portrait", "grandpa": "a smiling grandfather with a gray beard, portrait",
    "brother": "a boy with a backpack, portrait", "sister": "a girl with braids, portrait",
    "baby": "a happy baby in a onesie", "teacher": "a teacher holding a book in front of a chalkboard",
    "friend": "two kids high-fiving", "doctor": "a doctor in a white coat with a stethoscope",
    "nurse": "a nurse in scrubs with a clipboard", "police": "a police officer in uniform waving",
    "firefighter": "a firefighter in a helmet holding a hose", "therapist": "a friendly therapist at a table with picture cards",
    "family": "a family of four holding hands", "dentist_person": "a dentist in a mask holding a mirror tool",
    # places
    "home": "a cozy house with a red roof", "school": "a school building with a flag",
    "classroom": "a classroom with desks and a whiteboard", "playground": "a playground with a slide and swings",
    "park": "a park with trees, a bench and a path", "store": "a grocery store front with a cart",
    "restaurant": "a restaurant table with plates and a menu", "hospital": "a hospital building with a red cross",
    "bathroom": "a bathroom with a toilet and sink", "bedroom": "a bedroom with a bed and a lamp",
    "kitchen": "a kitchen with a stove and counter", "living_room": "a living room with a green couch, a lamp and a blank dark television screen",
    "library": "library shelves full of books", "pool": "a swimming pool with a ladder",
    "zoo": "a zoo entrance with a lion and giraffe", "beach": "a sandy beach with an umbrella and waves",
    "movie_theater": "a movie theater screen with seats and popcorn", "gym": "a gym with a basketball hoop",
    # play
    "ball": "a colorful bouncy ball", "blocks": "a stack of wooden alphabet blocks",
    "toy_car": "a red toy car", "train_toy": "a wooden toy train",
    "doll": "a doll with a dress and yarn hair", "puzzle": "puzzle pieces fitting together",
    "tablet_ipad": "a tablet computer showing a blank blue screen with a few colorful app squares, no writing", "video_game": "a game controller with a screen",
    "bubbles": "a child blowing soap bubbles", "crayons": "a box of crayons",
    "swing": "a child on a swing", "slide": "a child going down a slide",
    "music_play": "a toy xylophone with music notes", "playdough": "colorful play dough with a rolling pin",
    "bike": "a kid's bike with training wheels", "board_game": "a board game with dice and pieces",
    "sandbox": "a sandbox with a bucket and shovel", "stickers": "a few loose star and smiley-face stickers, no sheet, no backing paper",
    # daily
    "potty": "a small potty chair", "bath": "a bathtub with bubbles and a duck",
    "soap": "a bar of soap with bubbles", "shirt": "a plain blue t-shirt with no print",
    "pants": "a pair of blue jeans", "shoes": "a pair of sneakers",
    "socks": "a pair of striped socks", "jacket": "a zip-up jacket",
    "hat": "a baseball cap", "pajamas": "a pair of star-patterned pajamas",
    "backpack": "a red backpack", "glasses": "a pair of eyeglasses",
    "blanket": "a soft folded blanket", "pillow": "a plain fluffy white pillow with a light blue stripe",
    "towel": "a folded blue towel",
    # animals
    "dog": "a friendly brown dog", "cat": "an orange cat", "bird": "a small blue bird on a branch",
    "fish": "an orange goldfish", "rabbit": "a white rabbit", "horse": "a brown horse",
    "cow": "a black and white cow", "pig": "a pink pig", "sheep": "a fluffy white sheep",
    "duck": "a yellow duck", "lion": "a lion with a mane", "tiger": "an orange striped tiger",
    "elephant": "a gray elephant", "monkey": "a monkey holding a banana", "bear": "a brown bear",
    "turtle": "a green turtle", "frog": "a green frog on a lily pad", "butterfly": "a colorful butterfly",
    "dinosaur": "a green T-rex dinosaur", "dolphin": "a dolphin jumping over water", "penguin": "a penguin",
    # health
    "headache": "a child holding their head with pain squiggles", "tummy_ache": "a child holding their stomach with a green face",
    "fever": "a child with a thermometer in their mouth and red cheeks", "cough_cold": "a child coughing into an elbow with a tissue",
    "bandaid": "a bandaid on a knee", "medicine": "a medicine bottle with a spoon and pills",
    "doctor_health": "a doctor listening to a child's heart with a stethoscope", "dentist": "a dentist chair with a tooth",
    "head": "a child's head outlined with a hand pointing to it", "eyes": "two big open eyes",
    "ears": "an ear with sound waves", "mouth": "a smiling mouth with lips",
    "hands": "two open hands, palms up", "feet": "two bare feet",
    "wheelchair": "a child in a wheelchair smiling", "emergency": "an ambulance with flashing lights and a red cross",
    # vehicles
    "car_veh": "a blue car", "school_bus": "a yellow school bus", "train_veh": "a passenger train",
    "airplane": "an airplane in the sky", "boat_veh": "a sailboat on water", "fire_truck": "a red fire truck",
    "police_car": "a police car with lights", "ambulance_veh": "an ambulance", "truck": "a plain blue delivery truck with no lettering",
    "helicopter": "a helicopter", "bicycle_veh": "a bicycle",
    # nature
    "sun": "a bright sun", "rain": "a cloud with rain drops and an umbrella", "snow": "a snowman with falling snow",
    "wind": "a tree bending in the wind with leaves blowing", "cloud": "a fluffy white cloud",
    "thunder": "a dark cloud with a lightning bolt", "rainbow": "a rainbow over green hills",
    "tree": "a big green tree", "flower": "a pink flower", "moon_stars": "a crescent moon with stars",
    # concepts
    "num_1": "a big bold number 1 in bright red", "num_2": "a big bold number 2 in bright orange",
    "num_3": "a big bold number 3 in bright yellow", "num_4": "a big bold number 4 in bright green",
    "num_5": "a big bold number 5 in bright blue", "num_6": "a big bold number 6 in bright purple",
    "num_7": "a big bold number 7 in bright pink", "num_8": "a big bold number 8 in bright teal",
    "num_9": "a big bold number 9 in bright red", "num_10": "a big bold number 10 in bright blue",
    "all_concept": "five apples all inside a circle with a check mark", "none_concept": "an empty circle with a red slash through it",
    # colors
    "red": "a big bold red paint splash", "blue": "a big bold blue paint splash", "green": "a big bold green paint splash",
    "yellow": "a big bold plain yellow paint splash", "orange_col": "a big bold plain orange paint splash",
    "purple": "a big bold purple paint splash", "pink": "a big bold pink paint splash",
    "star_shape": "a bold yellow star shape", "heart_shape": "a bold red heart shape",
    # social
    "hello": "a child waving hello with a big smile", "goodbye": "a child waving goodbye while walking away",
    "please": "a child with hands pressed together asking nicely", "thank_you": "a child with a hand on their heart smiling",
    "youre_welcome": "a child smiling with open welcoming arms", "sorry": "a child with sad eyes and hands together apologizing",
    "excuse_me": "a child politely raising one finger", "i_love_you": "a child making a heart shape with both hands",
    "ready": "a child standing with a thumbs up and a green light", "great_job": "a child clapping with confetti and a gold star",
}
