# Expansion set 2 (2026-09-13): core grammar, feelings, social phrases.
# Same tuple shape as extra_symbols.py: (id, label, category, emoji, tts, [tags], image_subject)

EXTRA2 = [
    # --- core / grammar ---------------------------------------------------------
    ("her", "Her", "core", "👧", "Her", ["her", "hers", "girl"], "a child pointing at a smiling girl with a ponytail standing nearby"),
    ("him", "Him", "core", "👦", "Him", ["him", "his", "boy"], "a child pointing at a smiling boy standing nearby"),
    ("them", "Them", "core", "👥", "Them", ["them", "those people", "group"], "a child pointing at a group of three children standing together"),
    ("us", "Us", "core", "🫂", "Us", ["us", "our", "together"], "a child with an arm around a friend, both pointing at themselves"),
    ("mine", "Mine", "core", "🙌", "Mine", ["mine", "my", "belongs to me"], "a child hugging a teddy bear tightly to their chest, possessive smile"),
    ("yours", "Yours", "core", "🎁", "Yours", ["yours", "your", "for you"], "a child holding out a teddy bear toward another child"),
    ("something", "Something", "core", "❔", "Something", ["something", "thing", "item"], "a small closed cardboard box with a question mark on the lid"),
    ("nothing", "Nothing", "core", "⭕", "Nothing", ["nothing", "empty", "zero"], "two open empty hands held out, palms up, with a dashed empty circle above"),
    ("everything", "Everything", "core", "🌐", "Everything", ["everything", "all of it", "whole"], "a big pile of assorted toys, blocks, a ball and books with a circle around it all"),
    ("always", "Always", "core", "♾️", "Always", ["always", "forever", "every time"], "a calendar with every day marked with a green check mark"),
    ("never", "Never", "core", "🚫", "Never", ["never", "not ever", "no way"], "a calendar with a big red X across the whole thing"),
    ("sometimes", "Sometimes", "core", "🔀", "Sometimes", ["sometimes", "maybe", "once in a while"], "a calendar with only a few days marked with green check marks"),
    ("maybe", "Maybe", "core", "🤔", "Maybe", ["maybe", "perhaps", "not sure"], "a child tilting a flat hand side to side with a so-so face"),
    ("almost", "Almost", "core", "🏁", "Almost", ["almost", "nearly", "close"], "a child running toward a finish line just a step away"),
    ("very", "Very", "core", "❗", "Very", ["very", "really", "so much"], "a child with arms stretched wide showing something huge, exclamation mark"),
    ("too_much", "Too Much", "core", "🫗", "Too much", ["too much", "overflowing", "excess"], "a cup overflowing with juice spilling over the sides"),
    ("enough", "Enough", "core", "✋", "Enough", ["enough", "that's enough", "plenty"], "a child holding up a flat palm toward a bowl that is full"),
    ("not", "Not", "core", "❌", "Not", ["not", "no", "negative"], "a big red circle with a thick diagonal red slash through it, like a no-entry sign"),
    ("and", "And", "core", "➕", "And", ["and", "plus", "also"], "a red apple plus sign a yellow banana side by side"),
    ("or", "Or", "core", "⚖️", "Or", ["or", "either", "choice"], "a child looking between an apple on one side and a cookie on the other"),
    ("because", "Because", "core", "➡️", "Because", ["because", "reason", "why"], "a rain cloud with an arrow pointing to a child holding an umbrella"),
    ("with", "With", "core", "🤝", "With", ["with", "together", "along"], "two children walking side by side holding hands"),
    ("without", "Without", "core", "🚶", "Without", ["without", "alone", "missing"], "one child walking alone with a faded empty outline beside them"),
    ("for", "For", "core", "🎀", "For", ["for", "to give", "intended"], "a wrapped gift box with a tag and an arrow pointing to a smiling child"),
    ("from", "From", "core", "📤", "From", ["from", "sent by", "origin"], "an arrow coming out of an open mailbox toward a letter"),
    ("to", "To", "core", "📍", "To", ["to", "toward", "go to"], "a big arrow pointing toward a house"),
    ("about", "About", "core", "💬", "About", ["about", "topic", "regarding"], "a child holding a book with a speech bubble that shows a dog inside"),
    ("under", "Under", "core", "⬇️", "Under", ["under", "below", "beneath"], "a cat lying underneath a table"),
    ("over", "Over", "core", "⤴️", "Over", ["over", "above", "across"], "a bird flying over a fence"),
    ("behind", "Behind", "core", "🔙", "Behind", ["behind", "back", "in back of"], "a child peeking out from behind a tree"),
    ("in_front", "In Front", "core", "🔜", "In front", ["in front", "front", "ahead"], "a child standing in front of a big tree facing the viewer"),
    ("next_to", "Next To", "core", "↔️", "Next to", ["next to", "beside", "near"], "a cat sitting right beside a dog"),
    ("between", "Between", "core", "↕️", "Between", ["between", "middle", "in the middle"], "a child standing in the middle between two trees"),
    ("around", "Around", "core", "🔄", "Around", ["around", "circle", "surround"], "a child running in a circle around a tree with a curved arrow"),
    ("through", "Through", "core", "🚪", "Through", ["through", "pass", "tunnel"], "a child crawling through a play tunnel"),
    ("top", "Top", "core", "🔝", "Top", ["top", "highest", "above"], "a stack of blocks with a star on the very top block, arrow pointing at it"),
    ("bottom", "Bottom", "core", "⏬", "Bottom", ["bottom", "lowest", "below"], "a stack of blocks with an arrow pointing at the lowest block"),
    ("middle", "Middle", "core", "🎯", "Middle", ["middle", "center", "between"], "three blocks in a row, the middle one highlighted with an arrow"),
    ("left", "Left", "core", "⬅️", "Left", ["left", "left side"], "a child pointing to the left with a big arrow pointing left"),
    ("right_dir", "Right", "core", "➡️", "Right", ["right", "right side"], "a child pointing to the right with a big arrow pointing right"),
    ("far", "Far", "core", "🔭", "Far", ["far", "far away", "distant"], "a child looking at a tiny house far away on a hill"),
    ("near", "Near", "core", "📌", "Near", ["near", "close", "nearby"], "a child standing right next to a house, touching the wall"),
    ("early", "Early", "core", "🌅", "Early", ["early", "soon", "sunrise"], "a clock showing six and a sunrise out a window"),
    ("late", "Late", "core", "⏰", "Late", ["late", "behind", "running late"], "a child rushing with a backpack while an alarm clock rings"),
    ("soon", "Soon", "core", "⏳", "Soon", ["soon", "shortly", "almost time"], "an hourglass with just a little sand left on top"),
    ("long_time", "Long Time", "core", "📅", "A long time", ["long time", "forever", "ages"], "a child sitting and waiting next to a calendar with many pages"),
    ("once", "Once", "core", "1️⃣", "One time", ["once", "one time", "single"], "a child holding up one finger next to a single green check mark"),
    ("twice", "Twice", "core", "2️⃣", "Two times", ["twice", "two times", "again"], "a child holding up two fingers next to two green check marks"),
    ("every_day", "Every Day", "core", "🔁", "Every day", ["every day", "daily", "routine"], "a week calendar with a sun on every day"),
    ("start", "Start", "core", "▶️", "Start", ["start", "begin", "go"], "a child at a starting line with a big green play triangle"),
    ("end", "End", "core", "⏹️", "End", ["end", "finish", "over"], "a child crossing a checkered finish line with a red square stop symbol"),
    ("keep_going", "Keep Going", "core", "⏩", "Keep going", ["keep going", "continue", "don't stop"], "a child walking forward on a path with two arrows pointing ahead"),
    ("try", "Try", "core", "💪", "Try", ["try", "attempt", "give it a go"], "a child with a determined face reaching up to stack a tall block tower"),
    ("show", "Show", "core", "👀", "Show me", ["show", "show me", "look at this"], "a child holding up a drawing toward the viewer with both hands"),
    ("tell", "Tell", "core", "🗣️", "Tell me", ["tell", "tell me", "say"], "a child whispering into a friend's ear with a speech bubble"),
    ("find", "Find", "core", "🔍", "Find", ["find", "search", "look for"], "a child looking under a bed with a magnifying glass"),
    ("lost", "Lost", "core", "😟", "Lost", ["lost", "missing", "can't find"], "a child looking worried holding an empty leash"),
    ("found", "Found", "core", "🎉", "Found it", ["found", "found it", "here it is"], "a child happily holding up a lost teddy bear"),
    ("bring", "Bring", "core", "🛍️", "Bring", ["bring", "carry", "deliver"], "a child carrying a basket toward another child"),
    ("hold", "Hold", "core", "🤲", "Hold", ["hold", "carry", "keep"], "two hands cupped together holding a small bird"),
    ("drop", "Drop", "core", "⬇️", "Drop", ["drop", "let go", "fall"], "a hand letting go of a ball that is falling with motion lines"),
    ("pick", "Pick", "core", "☝️", "Pick", ["pick", "choose", "select"], "a child pointing at one of three colored cups"),
    ("choose", "Choose", "core", "🤔", "Choose", ["choose", "pick one", "decide"], "a child deciding between a red ball and a blue ball with a question mark"),
    ("change", "Change", "core", "🔃", "Change", ["change", "switch", "swap"], "a red shirt and a blue shirt with curved swap arrows between them"),
    ("fix", "Fix", "core", "🔧", "Fix", ["fix", "repair", "mend"], "a child with a wrench fixing a broken toy car"),
    ("broken", "Broken", "core", "💔", "Broken", ["broken", "not working", "damaged"], "a toy robot cracked in two pieces with a sad face"),
    ("working", "Working", "core", "✅", "Working", ["working", "works", "fixed"], "a toy robot standing with a green check mark and a happy face"),
    ("careful", "Careful", "core", "⚠️", "Be careful", ["careful", "caution", "watch out"], "a child stepping carefully around a wet floor sign, yellow warning triangle"),
    ("hurry", "Hurry", "core", "💨", "Hurry", ["hurry", "quick", "rush"], "a child sprinting with speed lines and a stopwatch"),
    ("gentle", "Gentle", "core", "🐣", "Gentle", ["gentle", "soft", "easy"], "a child softly petting a small kitten with a calm smile"),
    ("heavy", "Heavy", "core", "🏋️", "Heavy", ["heavy", "weighs a lot"], "a child straining to lift a big rock"),
    ("light_weight", "Light", "core", "🎈", "Light", ["light", "not heavy", "easy to lift"], "a child easily lifting a feather with one finger"),
    ("tall", "Tall", "core", "🦒", "Tall", ["tall", "high", "big"], "a very tall giraffe next to a small child looking up"),
    ("short", "Short", "core", "🐕", "Short", ["short", "small", "low"], "a short dachshund dog next to a tall chair"),
    ("long", "Long", "core", "📏", "Long", ["long", "lengthy"], "a very long green snake stretched across the picture"),
    ("soft", "Soft", "core", "🧸", "Soft", ["soft", "fluffy", "cozy"], "a fluffy pillow with a child pressing a hand into it"),
    ("hard", "Hard", "core", "🪨", "Hard", ["hard", "solid", "tough"], "a child knocking on a gray rock"),
    ("smooth", "Smooth", "core", "🥚", "Smooth", ["smooth", "flat", "even"], "a child stroking a smooth white egg"),
    ("rough", "Rough", "core", "🌵", "Rough", ["rough", "bumpy", "scratchy"], "a child touching bumpy tree bark"),
    ("sharp", "Sharp", "core", "🔪", "Sharp", ["sharp", "pointy", "careful"], "a pair of scissors with a warning triangle"),
    ("sticky", "Sticky", "core", "🍯", "Sticky", ["sticky", "gooey", "glue"], "a child with honey stuck on their fingers pulling them apart"),
    ("strong", "Strong", "core", "💪", "Strong", ["strong", "powerful", "muscles"], "a child flexing an arm muscle with a proud face"),
    ("weak", "Weak", "core", "🥀", "Weak", ["weak", "tired", "no energy"], "a child slumped over trying to lift a small box"),
    ("open_adj", "Open", "core", "🔓", "Open", ["open", "unlocked", "opened"], "a wide open door with light coming through"),
    ("closed", "Closed", "core", "🔒", "Closed", ["closed", "shut", "locked"], "a closed door with a lock on it"),
    ("pretty", "Pretty", "core", "🌸", "Pretty", ["pretty", "beautiful", "nice"], "a child admiring a bright pink flower"),
    ("ugly", "Ugly", "core", "🤢", "Ugly", ["ugly", "yucky", "gross"], "a child making a disgusted face at a moldy sandwich"),
    ("easy", "Easy", "core", "👍", "Easy", ["easy", "simple", "no problem"], "a child stacking two blocks with a relaxed thumbs up"),
    ("difficult", "Hard to Do", "core", "😓", "Difficult", ["hard", "difficult", "tricky"], "a child sweating over a tangled puzzle"),
    ("right_correct", "Right", "core", "✔️", "That's right", ["right", "correct", "yes"], "a worksheet with a big green check mark and a smiling child"),
    ("wrong", "Wrong", "core", "✖️", "Wrong", ["wrong", "incorrect", "mistake"], "a worksheet with a big red X and a child scratching their head"),
    ("real", "Real", "core", "🍏", "Real", ["real", "true", "actual"], "a real shiny apple next to a flat drawing of an apple, arrow at the real one"),
    ("pretend_adj", "Pretend", "core", "🎭", "Pretend", ["pretend", "fake", "make believe"], "a child wearing a paper crown holding a cardboard sword"),
    ("favorite", "Favorite", "core", "⭐", "My favorite", ["favorite", "best", "love it"], "a child hugging a toy dinosaur with a big gold star above"),
    ("other", "Other", "core", "↪️", "The other one", ["other", "different one", "another"], "two cups, a hand pointing past the first to the second one"),
    ("both", "Both", "core", "✌️", "Both", ["both", "two", "the two"], "a child holding an apple in one hand and a banana in the other"),
    ("only", "Only", "core", "1️⃣", "Only", ["only", "just", "single"], "a single red ball alone on an empty shelf"),
    ("each", "Each", "core", "🍪", "Each", ["each", "every one", "per"], "three children each holding one cookie"),
    ("part", "Part", "core", "🧩", "Part", ["part", "piece", "some of"], "one puzzle piece removed from a puzzle"),
    ("whole", "Whole", "core", "🍕", "Whole", ["whole", "entire", "all of it"], "a complete whole pizza, uncut"),
    ("half", "Half", "core", "🌗", "Half", ["half", "half of"], "an apple cut cleanly in half"),
    ("problem", "Problem", "core", "⚠️", "There's a problem", ["problem", "issue", "trouble"], "a child looking at a spilled cup of milk with a worried face and an exclamation mark"),
    ("idea", "Idea", "core", "💡", "I have an idea", ["idea", "thought", "plan"], "a child with a big glowing lightbulb above their head, excited"),
    ("question", "Question", "core", "❓", "I have a question", ["question", "ask", "wonder"], "a child raising a hand with a big question mark above"),
    ("answer", "Answer", "core", "💬", "Answer", ["answer", "reply", "respond"], "a child with a speech bubble containing a green check mark"),
    ("secret", "Secret", "core", "🤫", "Secret", ["secret", "shh", "quiet"], "a child with a finger over their lips, whispering"),
    ("surprise", "Surprise", "core", "🎁", "Surprise", ["surprise", "gift", "unexpected"], "a child opening a gift box with confetti popping out"),
    ("turn_around", "Turn Around", "core", "🔄", "Turn around", ["turn around", "spin", "face the other way"], "a child spinning around with a curved arrow around them"),
    ("move", "Move", "core", "↔️", "Move", ["move", "shift", "scoot"], "a child pushing a chair sideways with an arrow"),
    ("stay", "Stay", "core", "🛑", "Stay", ["stay", "remain", "don't move"], "a child standing still on a marked spot with a flat palm out"),
    ("leave", "Leave", "core", "🚪", "Leave", ["leave", "go away", "exit"], "a child walking out through a door with a backpack"),
    ("arrive", "Arrive", "core", "🏠", "We're here", ["arrive", "here", "get there"], "a car pulling up in front of a house with a waving child"),

    # --- feelings ---------------------------------------------------------------
    ("disappointed", "Disappointed", "feelings", "😞", "I feel disappointed", ["disappointed", "let down", "sad"], "a child looking down at a deflated balloon with a sad face"),
    ("annoyed", "Annoyed", "feelings", "😒", "I feel annoyed", ["annoyed", "irritated", "bothered"], "a child with crossed arms and a flat, irritated expression, a fly buzzing near"),
    ("curious", "Curious", "feelings", "🧐", "I feel curious", ["curious", "interested", "wonder"], "a child peeking into a box with wide interested eyes"),
    ("hopeful", "Hopeful", "feelings", "🤞", "I feel hopeful", ["hopeful", "wish", "fingers crossed"], "a child with crossed fingers looking up at a shooting star"),
    ("grateful", "Grateful", "feelings", "🙏", "I feel grateful", ["grateful", "thankful", "thanks"], "a child holding a gift with hands pressed together and a warm smile"),
    ("guilty", "Guilty", "feelings", "😳", "I feel guilty", ["guilty", "sorry", "oops"], "a child looking down at a broken vase with a guilty face"),
    ("relieved", "Relieved", "feelings", "😮‍💨", "I feel relieved", ["relieved", "phew", "better now"], "a child wiping their forehead with a relaxed smile"),
    ("uncomfortable", "Uncomfortable", "feelings", "😣", "I feel uncomfortable", ["uncomfortable", "awkward", "itchy"], "a child squirming in a scratchy sweater"),
    ("comfortable", "Comfortable", "feelings", "😌", "I feel comfortable", ["comfortable", "cozy", "relaxed"], "a child snuggled in a soft blanket on a couch, content"),
    ("cranky", "Cranky", "feelings", "😤", "I feel cranky", ["cranky", "grouchy", "moody"], "a child with messy hair and a scowl rubbing their eyes"),
    ("sleepy", "Sleepy", "feelings", "🥱", "I feel sleepy", ["sleepy", "drowsy", "yawn"], "a child yawning with droopy eyes and a small moon above"),
    ("energetic", "Energetic", "feelings", "⚡", "I feel energetic", ["energetic", "hyper", "full of energy"], "a child bouncing with lightning bolts and motion lines"),
    ("sad_crying", "Crying", "feelings", "😢", "I'm crying", ["crying", "tears", "upset"], "a child with big tears streaming down their cheeks"),
    ("laughing", "Laughing", "feelings", "😂", "I'm laughing", ["laughing", "funny", "giggle"], "a child laughing hard holding their belly"),
    ("in_pain", "In Pain", "feelings", "🤕", "I'm in pain", ["pain", "ouch", "hurts"], "a child holding a bandaged arm wincing"),
    ("nauseous", "Nauseous", "feelings", "🤢", "I feel sick to my stomach", ["nauseous", "queasy", "throw up"], "a green-faced child holding their mouth and stomach"),
    ("bad_mood", "Bad Mood", "feelings", "🌧️", "I'm in a bad mood", ["bad mood", "grumpy", "off"], "a child slouched under a small rain cloud"),
    ("good_mood", "Good Mood", "feelings", "🌞", "I'm in a good mood", ["good mood", "cheerful", "great"], "a child skipping with a small sun above their head"),
    ("mixed_up", "Mixed Up", "feelings", "😵‍💫", "I feel mixed up", ["mixed up", "confused", "dizzy"], "a child with swirly eyes and question marks spinning around their head"),
    ("left_out", "Left Out", "feelings", "🙁", "I feel left out", ["left out", "excluded", "alone"], "a child standing apart watching a group of kids play together"),
    ("included", "Included", "feelings", "🤗", "I feel included", ["included", "part of", "welcome"], "a group of children waving a child over to join their circle"),
    ("bullied", "Bullied", "feelings", "😠", "Someone is being mean to me", ["bullied", "mean", "teased"], "a child covering their ears while a bigger kid points and shouts"),
    ("need_hug", "Need a Hug", "feelings", "🫂", "I need a hug", ["hug", "comfort", "cuddle"], "a child with arms open wide asking for a hug"),
    ("need_space", "Need Space", "feelings", "🙅", "I need space", ["space", "alone", "back off"], "a child holding both palms out with a circle of empty space around them"),
    ("too_bright", "Too Bright", "feelings", "🕶️", "It's too bright", ["bright", "light", "sunglasses"], "a child squinting and shielding their eyes from a bright sun"),
    ("too_busy", "Too Busy", "feelings", "🌀", "It's too busy here", ["busy", "crowded", "overwhelming"], "a child covering their ears surrounded by many small floating people icons and swirl lines, no walls, no room"),
    ("too_hot", "Too Hot", "feelings", "🥵", "I'm too hot", ["too hot", "sweaty", "warm"], "a red-faced child sweating and fanning themselves"),
    ("too_cold", "Too Cold", "feelings", "🥶", "I'm too cold", ["too cold", "freezing", "shiver"], "a blue-lipped child shivering with arms wrapped around themselves"),

    # --- social / phrases -------------------------------------------------------
    ("good_afternoon", "Good Afternoon", "social", "🌤️", "Good afternoon", ["good afternoon", "greeting"], "a child waving with a sun high in the sky"),
    ("see_you_later", "See You Later", "social", "👋", "See you later", ["see you later", "bye", "later"], "a child waving goodbye while walking away with a backpack"),
    ("nice_to_meet_you", "Nice to Meet You", "social", "🤝", "Nice to meet you", ["nice to meet you", "hello", "introduce"], "two children shaking hands and smiling"),
    ("my_name_is", "My Name Is", "social", "🏷️", "My name is", ["my name is", "name", "introduce"], "a child pointing at a blank name tag sticker on their shirt"),
    ("whats_your_name", "What's Your Name?", "social", "❓", "What's your name?", ["what's your name", "name", "ask"], "a child pointing at another child's blank name tag with a question mark"),
    ("how_old", "How Old Are You?", "social", "🎂", "How old are you?", ["how old", "age", "birthday"], "a birthday cake with candles and a question mark"),
    ("i_am_years_old", "I Am ... Years Old", "social", "🔢", "I am years old", ["years old", "age", "my age"], "a child holding up fingers next to a birthday cake"),
    ("whats_that", "What's That?", "social", "👉", "What's that?", ["what's that", "what is it", "point"], "a child pointing at a mystery object with a question mark"),
    ("i_want_that", "I Want That", "social", "👆", "I want that", ["i want that", "want", "that one"], "a child pointing eagerly at a toy on a high shelf"),
    ("i_like_it", "I Like It", "social", "👍", "I like it", ["i like it", "like", "good"], "a child giving a thumbs up with a big smile and a small heart"),
    ("i_dont_like_it", "I Don't Like It", "social", "👎", "I don't like it", ["i don't like it", "dislike", "no"], "a child giving a thumbs down with a frown"),
    ("im_hungry", "I'm Hungry", "social", "🍽️", "I'm hungry", ["hungry", "food", "eat"], "a child holding their tummy looking at an empty plate"),
    ("im_thirsty", "I'm Thirsty", "social", "🥤", "I'm thirsty", ["thirsty", "drink", "water"], "a child with a dry tongue out looking at a glass of water"),
    ("im_tired", "I'm Tired", "social", "😴", "I'm tired", ["tired", "sleepy", "rest"], "a child yawning and rubbing their eyes"),
    ("im_sick", "I'm Sick", "social", "🤒", "I don't feel well", ["sick", "ill", "not well"], "a child with a thermometer in their mouth under a blanket"),
    ("im_bored", "I'm Bored", "social", "😐", "I'm bored", ["bored", "nothing to do"], "a child slumped on a chair staring at the ceiling"),
    ("im_scared", "I'm Scared", "social", "😨", "I'm scared", ["scared", "afraid", "frightened"], "a child hiding behind a blanket with wide eyes"),
    ("im_happy", "I'm Happy", "social", "😊", "I'm happy", ["happy", "glad", "good"], "a child jumping with joy, arms up"),
    ("im_sad", "I'm Sad", "social", "😢", "I'm sad", ["sad", "unhappy", "down"], "a child sitting with knees hugged and a tear"),
    ("im_mad", "I'm Mad", "social", "😡", "I'm mad", ["mad", "angry", "upset"], "a red-faced child with clenched fists and steam"),
    ("i_feel_sick", "My Tummy Hurts", "social", "🤢", "My tummy hurts", ["tummy hurts", "stomach ache", "sick"], "a child holding their stomach with a pained face"),
    ("im_okay", "I'm Okay", "social", "👌", "I'm okay", ["okay", "fine", "all right"], "a child making an OK hand sign with a calm smile"),
    ("not_okay", "I'm Not Okay", "social", "🆘", "I'm not okay", ["not okay", "help", "something's wrong"], "a child with a worried face holding up both hands"),
    ("need_break", "I Need a Break", "social", "⏸️", "I need a break", ["break", "pause", "rest"], "a child sitting on a bench with a pause symbol above"),
    ("need_help", "I Need Help", "social", "🙋", "I need help", ["need help", "help me", "assist"], "a child raising a hand high with a worried face"),
    ("need_bathroom", "I Need the Bathroom", "social", "🚻", "I need to go to the bathroom", ["bathroom", "potty", "toilet"], "a child crossing their legs next to a toilet door sign"),
    ("wait_please", "Wait Please", "social", "✋", "Wait please", ["wait", "hold on", "one minute"], "a child holding up a flat palm with a small clock"),
    ("one_more", "One More", "social", "☝️", "One more", ["one more", "again", "another"], "a child holding up one finger beside a plate with one cookie"),
    ("all_gone", "All Gone", "social", "🫙", "All gone", ["all gone", "empty", "finished"], "a child shrugging with palms up in front of an empty white plate with only a few crumbs on it"),
    ("whats_wrong", "What's Wrong?", "social", "😟", "What's wrong?", ["what's wrong", "are you okay", "problem"], "a child with a concerned face and a hand on a sad friend's shoulder"),
    ("are_you_okay", "Are You Okay?", "social", "🤔", "Are you okay?", ["are you okay", "check", "ask"], "a child leaning toward a friend with a question mark, caring face"),
    ("i_can_help", "I Can Help", "social", "🤲", "I can help", ["i can help", "help you", "offer"], "a child holding out both hands to a friend who dropped books"),
    ("thats_funny", "That's Funny", "social", "😄", "That's funny", ["funny", "laugh", "joke"], "a child laughing at a friend making a silly face"),
    ("thats_cool", "That's Cool", "social", "😎", "That's cool", ["cool", "awesome", "nice"], "a child in sunglasses giving a thumbs up"),
    ("oh_no", "Oh No", "social", "😱", "Oh no", ["oh no", "uh oh", "yikes"], "a child with hands on cheeks looking at a spilled milk carton"),
    ("uh_oh", "Uh Oh", "social", "😬", "Uh oh", ["uh oh", "oops", "mistake"], "a child with a grimace looking at a dropped ice cream cone"),
    ("wow", "Wow", "social", "🤩", "Wow", ["wow", "amazing", "impressive"], "a child with star eyes and an open mouth looking at fireworks"),
    ("yay", "Yay", "social", "🎉", "Yay", ["yay", "hooray", "celebrate"], "a child jumping with arms up and confetti"),
    ("yuck", "Yuck", "social", "🤮", "Yuck", ["yuck", "gross", "disgusting"], "a child sticking their tongue out at a plate of slimy green food"),
    ("yum", "Yum", "social", "😋", "Yum", ["yum", "delicious", "tasty"], "a child licking their lips holding a chocolate cupcake"),
    ("ouch", "Ouch", "social", "🤕", "Ouch", ["ouch", "hurt", "ow"], "a child holding a stubbed toe with a pain star"),
    ("shh", "Shh", "social", "🤫", "Shh, quiet", ["shh", "quiet", "hush"], "a child with a finger to their lips"),
    ("stop_it", "Stop It", "social", "✋", "Stop it", ["stop it", "quit", "don't"], "a child with a flat palm out and a firm face"),
    ("dont_touch", "Don't Touch", "social", "🙅", "Don't touch", ["don't touch", "hands off", "no touching"], "a hand reaching toward a vase with a red no symbol over it"),
    ("be_nice", "Be Nice", "social", "💕", "Be nice", ["be nice", "kind", "gentle"], "two children sharing a toy with hearts above"),
    ("good_idea", "Good Idea", "social", "💡", "Good idea", ["good idea", "smart", "agree"], "a child pointing at a glowing lightbulb with a thumbs up"),
    ("i_agree", "I Agree", "social", "👍", "I agree", ["agree", "yes", "same"], "two children nodding at each other with thumbs up"),
    ("i_disagree", "I Disagree", "social", "👎", "I disagree", ["disagree", "no", "different"], "a child shaking their head with crossed arms"),
    ("your_turn_phrase", "It's Your Turn", "social", "🫵", "It's your turn", ["your turn", "go ahead", "next"], "a child gesturing to a friend to roll a big die"),
    ("can_i_play", "Can I Play?", "social", "🙋", "Can I play?", ["can i play", "join", "play with me"], "a child holding a ball asking a group of kids with a hopeful face"),
    ("play_with_me", "Play With Me", "social", "🤝", "Play with me", ["play with me", "join me", "together"], "a child holding out a toy car to a friend"),
    ("lets_share", "Let's Share", "social", "🍪", "Let's share", ["share", "half", "together"], "a child breaking a cookie in half to give to a friend"),
    ("happy_birthday", "Happy Birthday", "social", "🎂", "Happy birthday", ["happy birthday", "birthday", "cake"], "a birthday cake with lit candles and balloons"),
    ("merry_christmas", "Merry Christmas", "social", "🎄", "Merry Christmas", ["merry christmas", "christmas", "holiday"], "a decorated Christmas tree with gifts underneath"),
    ("happy_halloween", "Happy Halloween", "social", "🎃", "Happy Halloween", ["halloween", "pumpkin", "trick or treat"], "a smiling carved jack-o-lantern with a small ghost"),
    ("trick_or_treat", "Trick or Treat", "social", "🍬", "Trick or treat", ["trick or treat", "halloween", "candy"], "a child in a costume holding out a candy bucket"),
    ("happy_easter", "Happy Easter", "social", "🐰", "Happy Easter", ["easter", "bunny", "eggs"], "a bunny with a basket of colorful painted eggs"),
    ("happy_thanksgiving", "Happy Thanksgiving", "social", "🦃", "Happy Thanksgiving", ["thanksgiving", "turkey", "dinner"], "a cartoon turkey next to a pumpkin pie"),
    ("happy_new_year", "Happy New Year", "social", "🎆", "Happy New Year", ["new year", "fireworks", "party"], "fireworks bursting with a party hat and horn"),
    ("valentine", "Valentine's Day", "social", "💝", "Happy Valentine's Day", ["valentine", "love", "hearts"], "a big red heart card with smaller hearts around it"),
    ("fourth_of_july", "Fourth of July", "social", "🎇", "Happy Fourth of July", ["fourth of july", "fireworks", "flag"], "red white and blue fireworks with a small flag"),
    ("get_well", "Get Well Soon", "social", "💐", "Get well soon", ["get well", "feel better", "sick"], "a child handing flowers to a friend in bed"),
    ("congratulations", "Congratulations", "social", "🏆", "Congratulations", ["congratulations", "well done", "trophy"], "a child holding up a gold trophy with confetti"),
    ("good_luck", "Good Luck", "social", "🍀", "Good luck", ["good luck", "luck", "clover"], "a child holding a four-leaf clover with crossed fingers"),
    ("welcome", "Welcome", "social", "🚪", "Welcome", ["welcome", "come in", "greeting"], "a child holding open a front door with a welcome mat"),
    ("bless_you", "Bless You", "social", "🤧", "Bless you", ["bless you", "sneeze", "achoo"], "a child sneezing into a tissue while a friend smiles"),
    ("i_miss_you", "I Miss You", "social", "💌", "I miss you", ["miss you", "love", "far away"], "a child hugging a framed photo with a small heart"),
    ("im_proud_of_you", "I'm Proud of You", "social", "🌟", "I'm proud of you", ["proud", "well done", "praise"], "an adult patting a child on the shoulder, gold star above"),
    ("high_five", "High Five", "social", "🙏", "High five", ["high five", "celebrate", "hands"], "two children slapping hands in a high five"),
    ("fist_bump", "Fist Bump", "social", "👊", "Fist bump", ["fist bump", "bump", "greeting"], "two children bumping fists"),
    ("call_mom", "Call Mom", "social", "📞", "I want to call Mom", ["call mom", "phone", "mom"], "a child holding a phone with a heart and a mom's face on the screen"),
    ("call_dad", "Call Dad", "social", "📱", "I want to call Dad", ["call dad", "phone", "dad"], "a child holding a phone with a dad's face on the screen"),
    ("go_home", "I Want to Go Home", "social", "🏡", "I want to go home", ["go home", "home", "leave"], "a child pointing at a house with a hopeful face"),
    ("im_lost", "I'm Lost", "social", "🧭", "I'm lost", ["lost", "help", "where am i"], "a child looking around confused at a crossroads sign"),
    ("emergency_phrase", "Emergency", "social", "🚨", "This is an emergency", ["emergency", "911", "urgent"], "a child pointing at a red flashing siren light"),
    ("i_dont_feel_safe", "I Don't Feel Safe", "social", "🛡️", "I don't feel safe", ["not safe", "scared", "danger"], "a child hugging themselves with a cracked shield beside them"),
    ("leave_me_alone", "Leave Me Alone", "social", "🚷", "Leave me alone", ["leave me alone", "go away", "alone"], "a child turned away with a hand held up behind them"),
    ("i_need_quiet", "I Need Quiet", "social", "🔇", "I need it quiet", ["quiet", "too loud", "silence"], "a child covering their ears next to a crossed-out speaker"),
    ("turn_it_down", "Turn It Down", "social", "🔉", "Turn it down", ["turn down", "volume", "lower"], "a hand turning a volume knob down with a small speaker"),
    ("turn_it_up", "Turn It Up", "social", "🔊", "Turn it up", ["turn up", "volume", "louder"], "a hand turning a volume knob up with a big speaker"),
]
