# Expansion set 4 (2026-09-13): people, places, play, daily life & clothing.

EXTRA4 = [
    # --- people -----------------------------------------------------------------
    ("stepmom", "Stepmom", "people", "👩", "Stepmom", ["stepmom", "mom", "parent"], "a smiling woman with a warm expression, portrait"),
    ("stepdad", "Stepdad", "people", "👨", "Stepdad", ["stepdad", "dad", "parent"], "a smiling man with a beard, portrait"),
    ("parents", "Parents", "people", "👫", "Parents", ["parents", "mom and dad", "family"], "a mom and dad standing together smiling"),
    ("twin", "Twin", "people", "👯", "Twin", ["twin", "sibling", "same"], "two identical smiling children side by side"),
    ("big_brother", "Big Brother", "people", "👦", "Big brother", ["big brother", "older brother"], "a tall boy with an arm around a smaller child"),
    ("little_sister", "Little Sister", "people", "👧", "Little sister", ["little sister", "younger sister"], "a small girl with pigtails holding a doll"),
    ("nana", "Nana", "people", "👵", "Nana", ["nana", "grandma", "granny"], "a smiling grandmother with gray hair and glasses, portrait"),
    ("papa", "Papa", "people", "👴", "Papa", ["papa", "grandpa", "pop"], "a smiling grandfather with a bald head and mustache, portrait"),
    ("niece", "Niece", "people", "👧", "Niece", ["niece", "family"], "a young girl waving, portrait"),
    ("nephew", "Nephew", "people", "👦", "Nephew", ["nephew", "family"], "a young boy waving, portrait"),
    ("husband", "Husband", "people", "🤵", "Husband", ["husband", "spouse"], "a smiling man with a wedding ring, portrait"),
    ("wife", "Wife", "people", "👰", "Wife", ["wife", "spouse"], "a smiling woman with a wedding ring, portrait"),
    ("partner", "Partner", "people", "💑", "Partner", ["partner", "boyfriend", "girlfriend"], "two adults holding hands with a small heart"),
    ("best_friend", "Best Friend", "people", "👭", "Best friend", ["best friend", "bff", "buddy"], "two children with arms around each other and a heart above"),
    ("classmate", "Classmate", "people", "🧑‍🎓", "Classmate", ["classmate", "school", "friend"], "a child with a backpack waving next to a desk"),
    ("neighbor", "Neighbor", "people", "🏘️", "Neighbor", ["neighbor", "next door"], "a person waving from the porch of a house next door"),
    ("stranger", "Stranger", "people", "🕵️", "Stranger", ["stranger", "unknown", "safety"], "a gray silhouette of a person with a question mark face"),
    ("crowd", "Crowd", "people", "👥", "Crowd", ["crowd", "many people", "busy"], "a big group of many people standing close together"),
    ("adult", "Adult", "people", "🧑", "Adult", ["adult", "grown up"], "a tall grown-up standing next to a small child, arrow at the adult"),
    ("kid", "Kid", "people", "🧒", "Kid", ["kid", "child"], "a small child standing next to a tall grown-up, arrow at the child"),
    ("teenager", "Teenager", "people", "🧑‍🦱", "Teenager", ["teenager", "teen"], "a teenager with headphones and a hoodie, portrait"),
    ("toddler", "Toddler", "people", "👶", "Toddler", ["toddler", "little kid"], "a toddler taking wobbly steps with arms out"),
    ("principal", "Principal", "people", "👩‍💼", "Principal", ["principal", "school", "office"], "a woman in a blazer holding a folder in front of a school"),
    ("aide", "Aide", "people", "🧑‍🏫", "Aide", ["aide", "helper", "para"], "a friendly adult kneeling next to a child at a desk"),
    ("speech_therapist", "Speech Therapist", "people", "🗣️", "Speech therapist", ["speech therapist", "slp", "therapy"], "an adult pointing to their mouth while a child watches with a picture card"),
    ("ot", "OT", "people", "🖐️", "Occupational therapist", ["ot", "occupational therapist", "therapy"], "an adult helping a child squeeze a ball"),
    ("pt", "PT", "people", "🦵", "Physical therapist", ["pt", "physical therapist", "therapy"], "an adult helping a child walk between parallel bars"),
    ("counselor", "Counselor", "people", "🧑‍⚕️", "Counselor", ["counselor", "talk", "feelings"], "an adult sitting across from a child talking, both calm"),
    ("librarian", "Librarian", "people", "📚", "Librarian", ["librarian", "library", "books"], "a person with glasses holding books in front of shelves"),
    ("janitor", "Janitor", "people", "🧹", "Janitor", ["janitor", "custodian", "clean"], "a person with a mop and a bucket"),
    ("lunch_lady", "Lunch Lady", "people", "🍽️", "Lunch lady", ["lunch lady", "cafeteria", "lunch"], "a person in a hairnet serving food from a counter"),
    ("crossing_guard", "Crossing Guard", "people", "🛑", "Crossing guard", ["crossing guard", "stop sign", "safety"], "a person in a vest holding a stop sign at a crosswalk"),
    ("mail_carrier", "Mail Carrier", "people", "📬", "Mail carrier", ["mail carrier", "mailman", "letters"], "a person in uniform putting a letter into a mailbox"),
    ("delivery", "Delivery Person", "people", "📦", "Delivery person", ["delivery", "package", "driver"], "a person holding a package at a front door"),
    ("chef", "Chef", "people", "👨‍🍳", "Chef", ["chef", "cook", "kitchen"], "a chef in a white hat holding a spoon"),
    ("waiter", "Waiter", "people", "🧑‍🍳", "Waiter", ["waiter", "server", "restaurant"], "a person holding a tray of food"),
    ("cashier", "Cashier", "people", "🧾", "Cashier", ["cashier", "store", "checkout"], "a person at a cash register"),
    ("farmer", "Farmer", "people", "🧑‍🌾", "Farmer", ["farmer", "farm", "tractor"], "a farmer in overalls and a straw hat holding a pitchfork"),
    ("vet", "Vet", "people", "🐾", "Vet", ["vet", "veterinarian", "animal doctor"], "a person in a white coat holding a puppy"),
    ("pilot", "Pilot", "people", "🧑‍✈️", "Pilot", ["pilot", "airplane", "fly"], "a pilot in a cap and uniform"),
    ("astronaut", "Astronaut", "people", "🧑‍🚀", "Astronaut", ["astronaut", "space", "rocket"], "an astronaut in a white space suit waving"),
    ("scientist", "Scientist", "people", "🧑‍🔬", "Scientist", ["scientist", "science", "lab"], "a person in a lab coat holding a bubbling beaker"),
    ("artist", "Artist", "people", "🧑‍🎨", "Artist", ["artist", "paint", "art"], "a person with a beret holding a palette and brush"),
    ("musician", "Musician", "people", "🧑‍🎤", "Musician", ["musician", "singer", "music"], "a person singing into a microphone with notes"),
    ("athlete", "Athlete", "people", "🏃", "Athlete", ["athlete", "sports", "player"], "a person in a jersey holding a ball"),
    ("soldier", "Soldier", "people", "🪖", "Soldier", ["soldier", "army", "military"], "a soldier in green uniform saluting"),
    ("construction_worker", "Construction Worker", "people", "👷", "Construction worker", ["construction", "builder", "hard hat"], "a worker in a hard hat and orange vest holding a hammer"),
    ("mechanic", "Mechanic", "people", "🧑‍🔧", "Mechanic", ["mechanic", "fix cars", "wrench"], "a person in overalls holding a wrench next to a car"),
    ("plumber", "Plumber", "people", "🔧", "Plumber", ["plumber", "pipes", "fix"], "a person with a wrench fixing a pipe under a sink"),
    ("hairdresser", "Hairdresser", "people", "💇", "Hairdresser", ["hairdresser", "barber", "haircut"], "a person holding scissors and a comb"),
    ("santa", "Santa", "people", "🎅", "Santa", ["santa", "christmas", "ho ho ho"], "Santa Claus in a red suit waving"),
    ("superhero", "Superhero", "people", "🦸", "Superhero", ["superhero", "hero", "cape"], "a child in a cape and mask striking a hero pose"),
    ("princess", "Princess", "people", "👸", "Princess", ["princess", "crown", "dress"], "a girl in a sparkly gown and tiara"),
    ("pirate", "Pirate", "people", "🏴‍☠️", "Pirate", ["pirate", "ship", "eye patch"], "a child in a pirate hat and eye patch"),
    ("king", "King", "people", "🤴", "King", ["king", "crown", "castle"], "a king with a gold crown and red robe"),
    ("queen", "Queen", "people", "👑", "Queen", ["queen", "crown", "castle"], "a queen with a gold crown and purple robe"),
    ("clown", "Clown", "people", "🤡", "Clown", ["clown", "circus", "funny"], "a friendly clown with a red nose and rainbow wig"),
    ("robot_person", "Robot", "people", "🤖", "Robot", ["robot", "machine"], "a friendly boxy robot with glowing eyes waving"),
    ("monster", "Monster", "people", "👾", "Monster", ["monster", "scary", "pretend"], "a friendly fuzzy purple monster with one eye"),
    ("ghost", "Ghost", "people", "👻", "Ghost", ["ghost", "halloween", "boo"], "a friendly white cartoon ghost saying boo"),
    ("fairy", "Fairy", "people", "🧚", "Fairy", ["fairy", "wings", "magic"], "a small fairy with wings and a wand"),
    ("mermaid", "Mermaid", "people", "🧜", "Mermaid", ["mermaid", "ocean", "tail"], "a mermaid with a green tail sitting on a rock"),
    ("wizard", "Wizard", "people", "🧙", "Wizard", ["wizard", "magic", "wand"], "a wizard in a pointed hat holding a wand"),
    ("knight", "Knight", "people", "🛡️", "Knight", ["knight", "armor", "sword"], "a knight in silver armor holding a shield"),
    ("cowboy", "Cowboy", "people", "🤠", "Cowboy", ["cowboy", "hat", "horse"], "a cowboy in a hat and boots with a lasso"),
    ("elf", "Elf", "people", "🧝", "Elf", ["elf", "christmas", "pointy ears"], "a small elf in green with pointy ears and a hat"),
    ("bunny_easter", "Easter Bunny", "people", "🐰", "Easter bunny", ["easter bunny", "easter", "eggs"], "a bunny in a bow tie holding a basket of eggs"),
    ("tooth_fairy", "Tooth Fairy", "people", "🦷", "Tooth fairy", ["tooth fairy", "tooth", "coin"], "a fairy holding a tooth and a coin"),

    # --- places -----------------------------------------------------------------
    ("dining_room", "Dining Room", "places", "🍽️", "Dining room", ["dining room", "table", "eat"], "a dining table with chairs and a lamp above"),
    ("garage", "Garage", "places", "🚗", "Garage", ["garage", "car", "tools"], "an open garage with a car inside"),
    ("basement", "Basement", "places", "🪜", "Basement", ["basement", "downstairs"], "stairs going down into a room with boxes"),
    ("attic", "Attic", "places", "🏠", "Attic", ["attic", "upstairs", "storage"], "a slanted-roof room with boxes and a small window"),
    ("upstairs", "Upstairs", "places", "⬆️", "Upstairs", ["upstairs", "up", "stairs"], "a child climbing up a staircase with an arrow up"),
    ("downstairs", "Downstairs", "places", "⬇️", "Downstairs", ["downstairs", "down", "stairs"], "a child walking down a staircase with an arrow down"),
    ("hallway", "Hallway", "places", "🚪", "Hallway", ["hallway", "hall", "corridor"], "a long hallway with doors on both sides"),
    ("porch", "Porch", "places", "🪑", "Porch", ["porch", "front", "outside"], "a front porch with a rocking chair and steps"),
    ("backyard", "Backyard", "places", "🌳", "Backyard", ["backyard", "yard", "outside"], "a grassy backyard with a fence and a tree"),
    ("front_yard", "Front Yard", "places", "🏡", "Front yard", ["front yard", "yard", "lawn"], "a house with a green lawn and a mailbox"),
    ("driveway", "Driveway", "places", "🛣️", "Driveway", ["driveway", "car", "outside"], "a driveway with a parked car in front of a garage"),
    ("laundry_room", "Laundry Room", "places", "🧺", "Laundry room", ["laundry", "washer", "dryer"], "a washing machine and dryer with a laundry basket"),
    ("closet", "Closet", "places", "🚪", "Closet", ["closet", "clothes", "hang"], "an open closet with hanging clothes"),
    ("office", "Office", "places", "💼", "Office", ["office", "work", "desk"], "a desk with a computer and an office chair"),
    ("cafeteria", "Cafeteria", "places", "🍽️", "Cafeteria", ["cafeteria", "lunchroom", "lunch"], "long tables with trays and a food counter"),
    ("nurse_office", "Nurse's Office", "places", "🩹", "Nurse's office", ["nurse", "school nurse", "sick"], "a small room with a cot and a first aid cross"),
    ("principal_office", "Principal's Office", "places", "🏫", "Principal's office", ["principal", "office"], "an office with a big desk and a school flag"),
    ("hallway_school", "School Hallway", "places", "🚶", "School hallway", ["hallway", "lockers", "school"], "a school hallway lined with lockers"),
    ("locker", "Locker", "places", "🔒", "Locker", ["locker", "school", "bag"], "a blue school locker half open with a backpack inside"),
    ("bus_school", "On the Bus", "places", "🚌", "On the bus", ["bus", "school bus", "ride"], "children sitting inside a yellow school bus"),
    ("recess", "Recess", "places", "🛝", "Recess", ["recess", "playground", "break"], "children running out to a playground with a clock"),
    ("pe_class", "Gym Class", "places", "🏀", "Gym class", ["pe", "gym class", "sports"], "children in a gym with a basketball and cones"),
    ("science_class", "Science Class", "places", "🔬", "Science class", ["science", "class", "experiment"], "a classroom with a microscope and beakers"),
    ("math_class", "Math Class", "places", "➗", "Math class", ["math", "class", "numbers"], "a board with numbers and plus signs, a child at a desk"),
    ("reading_class", "Reading", "places", "📖", "Reading class", ["reading", "class", "books"], "children sitting on a rug listening to a story"),
    ("assembly", "Assembly", "places", "🎤", "Assembly", ["assembly", "gym", "everyone"], "children sitting in rows in front of a stage"),
    ("field_trip", "Field Trip", "places", "🚌", "Field trip", ["field trip", "trip", "bus"], "children with a teacher getting off a bus at a museum"),
    ("after_school", "After School", "places", "🕒", "After school", ["after school", "program", "care"], "children playing a board game with a clock showing three"),
    ("daycare", "Daycare", "places", "🧸", "Daycare", ["daycare", "childcare", "preschool"], "a bright room with small tables, toys and a caregiver"),
    ("preschool", "Preschool", "places", "🎨", "Preschool", ["preschool", "pre-k", "school"], "a small colorful classroom with an alphabet rug"),
    ("college", "College", "places", "🎓", "College", ["college", "university", "school"], "a brick building with columns and a graduation cap"),
    ("museum", "Museum", "places", "🏛️", "Museum", ["museum", "dinosaur", "art"], "a big building with columns and a dinosaur skeleton inside"),
    ("aquarium", "Aquarium", "places", "🐠", "Aquarium", ["aquarium", "fish", "sharks"], "a giant fish tank window with fish and a shark"),
    ("farm", "Farm", "places", "🚜", "Farm", ["farm", "barn", "animals"], "a red barn with a cow and a fence"),
    ("amusement_park", "Amusement Park", "places", "🎢", "Amusement park", ["amusement park", "rides", "roller coaster"], "a roller coaster and a ferris wheel"),
    ("carnival", "Carnival", "places", "🎡", "Carnival", ["carnival", "fair", "rides"], "a ferris wheel and a striped tent with balloons"),
    ("water_park", "Water Park", "places", "🌊", "Water park", ["water park", "slides", "splash"], "colorful water slides splashing into a pool"),
    ("bowling_alley", "Bowling Alley", "places", "🎳", "Bowling alley", ["bowling", "alley", "pins"], "a bowling lane with pins and a ball"),
    ("arcade", "Arcade", "places", "🕹️", "Arcade", ["arcade", "games", "tokens"], "arcade machines with glowing screens"),
    ("skate_park", "Skate Park", "places", "🛹", "Skate park", ["skate park", "skateboard", "ramp"], "a skateboard ramp with a child skating"),
    ("ice_rink", "Ice Rink", "places", "⛸️", "Ice rink", ["ice rink", "skating", "ice"], "an ice rink with skaters"),
    ("stadium", "Stadium", "places", "🏟️", "Stadium", ["stadium", "game", "crowd"], "a big stadium with a field and crowd"),
    ("soccer_field", "Soccer Field", "places", "⚽", "Soccer field", ["soccer field", "field", "goal"], "a green soccer field with goals"),
    ("baseball_field", "Baseball Field", "places", "⚾", "Baseball field", ["baseball field", "diamond"], "a baseball diamond with bases"),
    ("basketball_court", "Basketball Court", "places", "🏀", "Basketball court", ["basketball court", "court", "hoop"], "a basketball court with a hoop"),
    ("tennis_court", "Tennis Court", "places", "🎾", "Tennis court", ["tennis court", "net"], "a tennis court with a net"),
    ("track", "Track", "places", "🏃", "Running track", ["track", "running", "race"], "an oval red running track"),
    ("trampoline_park", "Trampoline Park", "places", "🤸", "Trampoline park", ["trampoline park", "jump", "bounce"], "children bouncing on a big room of trampolines"),
    ("campground", "Campground", "places", "🏕️", "Campground", ["campground", "camping", "tent"], "tents and a campfire among trees"),
    ("lake", "Lake", "places", "🏞️", "Lake", ["lake", "water", "swim"], "a calm blue lake with trees and a dock"),
    ("river", "River", "places", "🏞️", "River", ["river", "water", "stream"], "a winding blue river through green banks"),
    ("forest", "Forest", "places", "🌲", "Forest", ["forest", "woods", "trees"], "a dense forest of green pine trees"),
    ("desert", "Desert", "places", "🏜️", "Desert", ["desert", "sand", "cactus"], "sand dunes with a cactus and sun"),
    ("island", "Island", "places", "🏝️", "Island", ["island", "beach", "palm tree"], "a small island with a palm tree in blue water"),
    ("cave", "Cave", "places", "🕳️", "Cave", ["cave", "dark", "rocks"], "a dark cave opening in a rocky hill"),
    ("waterfall", "Waterfall", "places", "💧", "Waterfall", ["waterfall", "water", "nature"], "a waterfall pouring into a pool"),
    ("city", "City", "places", "🏙️", "City", ["city", "downtown", "buildings"], "tall city buildings with a street"),
    ("town", "Town", "places", "🏘️", "Town", ["town", "village", "houses"], "a row of small houses and shops on a street"),
    ("countryside", "Countryside", "places", "🌾", "Countryside", ["country", "farmland", "fields"], "rolling green fields with a fence and a barn far away"),
    ("street", "Street", "places", "🛣️", "Street", ["street", "road", "cars"], "a road with cars and a sidewalk"),
    ("sidewalk", "Sidewalk", "places", "🚶", "Sidewalk", ["sidewalk", "walk", "path"], "a concrete sidewalk beside a road with a child walking"),
    ("crosswalk", "Crosswalk", "places", "🚸", "Crosswalk", ["crosswalk", "cross street", "safe"], "white crosswalk stripes with a walk signal"),
    ("parking_lot", "Parking Lot", "places", "🅿️", "Parking lot", ["parking lot", "cars", "park"], "rows of parked cars in a lot with a P sign"),
    ("gas_station", "Gas Station", "places", "⛽", "Gas station", ["gas station", "gas", "fuel"], "a gas pump under a station roof"),
    ("car_wash", "Car Wash", "places", "🚿", "Car wash", ["car wash", "wash", "bubbles"], "a car going through spinning brushes with soap bubbles"),
    ("airport", "Airport", "places", "✈️", "Airport", ["airport", "plane", "travel"], "an airport terminal with an airplane outside"),
    ("train_station", "Train Station", "places", "🚉", "Train station", ["train station", "train", "platform"], "a train at a platform with a clock"),
    ("hotel", "Hotel", "places", "🏨", "Hotel", ["hotel", "trip", "stay"], "a tall hotel building with a sign"),
    ("bank", "Bank", "places", "🏦", "Bank", ["bank", "money"], "a bank building with columns and a dollar sign"),
    ("post_office", "Post Office", "places", "🏤", "Post office", ["post office", "mail", "stamps"], "a post office building with a mailbox"),
    ("fire_station", "Fire Station", "places", "🚒", "Fire station", ["fire station", "fire truck"], "a fire station with a red truck in the open bay"),
    ("police_station", "Police Station", "places", "🚔", "Police station", ["police station", "police"], "a police station building with a police car"),
    ("courthouse", "Courthouse", "places", "⚖️", "Courthouse", ["courthouse", "court", "judge"], "a building with columns and a scale of justice"),
    ("pharmacy", "Pharmacy", "places", "💊", "Pharmacy", ["pharmacy", "drugstore", "medicine"], "a pharmacy counter with a pill bottle sign"),
    ("clinic", "Clinic", "places", "🏥", "Clinic", ["clinic", "doctor", "checkup"], "a small medical building with a cross"),
    ("dentist_office", "Dentist Office", "places", "🦷", "Dentist office", ["dentist", "teeth", "office"], "a dental chair with a light and a tooth sign"),
    ("eye_doctor", "Eye Doctor", "places", "👓", "Eye doctor", ["eye doctor", "optometrist", "glasses"], "a pair of round eyeglasses next to a big friendly eye, no chart, no letters"),
    ("vet_office", "Vet Office", "places", "🐾", "Vet office", ["vet", "animal hospital"], "a building with a paw print sign and a dog outside"),
    ("hair_salon", "Hair Salon", "places", "💈", "Hair salon", ["hair salon", "barber", "haircut"], "a salon chair with a mirror and scissors"),
    ("grocery_store", "Grocery Store", "places", "🛒", "Grocery store", ["grocery store", "supermarket", "food"], "a store aisle with shelves of food and a cart"),
    ("bakery", "Bakery", "places", "🥐", "Bakery", ["bakery", "bread", "cake"], "a bakery display case with breads and cakes"),
    ("ice_cream_shop", "Ice Cream Shop", "places", "🍦", "Ice cream shop", ["ice cream shop", "ice cream"], "an ice cream counter with tubs of flavors"),
    ("pizza_place", "Pizza Place", "places", "🍕", "Pizza place", ["pizza place", "pizzeria"], "a pizza shop counter with a big pizza"),
    ("fast_food", "Fast Food", "places", "🍔", "Fast food", ["fast food", "burger place"], "a fast food restaurant with a burger sign"),
    ("coffee_shop", "Coffee Shop", "places", "☕", "Coffee shop", ["coffee shop", "cafe"], "a cafe counter with a coffee cup sign"),
    ("toy_store", "Toy Store", "places", "🧸", "Toy store", ["toy store", "toys"], "a store with shelves of teddy bears and toys"),
    ("bookstore", "Bookstore", "places", "📚", "Bookstore", ["bookstore", "books"], "a shop with shelves full of books"),
    ("clothing_store", "Clothing Store", "places", "👗", "Clothing store", ["clothing store", "clothes", "shop"], "a store with racks of clothes"),
    ("shoe_store", "Shoe Store", "places", "👟", "Shoe store", ["shoe store", "shoes"], "a store with shelves of shoes"),
    ("pet_store", "Pet Store", "places", "🐹", "Pet store", ["pet store", "pets", "animals"], "a store with a puppy in a window and fish tanks"),
    ("hardware_store", "Hardware Store", "places", "🔨", "Hardware store", ["hardware store", "tools"], "a store aisle with hammers and paint cans"),
    ("dollar_store", "Dollar Store", "places", "💵", "Dollar store", ["dollar store", "cheap", "shop"], "a store with a dollar sign and shelves of items"),
    ("market", "Farmers Market", "places", "🍎", "Farmers market", ["farmers market", "market", "vegetables"], "outdoor stalls with baskets of fruits and vegetables"),
    ("food_court", "Food Court", "places", "🍟", "Food court", ["food court", "mall", "eat"], "tables in front of several food counters"),
    ("elevator", "Elevator", "places", "🛗", "Elevator", ["elevator", "up", "down"], "an open elevator with up and down buttons"),
    ("escalator", "Escalator", "places", "↗️", "Escalator", ["escalator", "moving stairs"], "a moving escalator with a child riding up"),
    ("stairs", "Stairs", "places", "🪜", "Stairs", ["stairs", "steps"], "a staircase with a handrail"),
    ("waiting_room", "Waiting Room", "places", "🪑", "Waiting room", ["waiting room", "wait", "doctor"], "rows of chairs with people waiting and a magazine table"),
    ("lobby", "Lobby", "places", "🏢", "Lobby", ["lobby", "entrance", "front desk"], "a front desk with a sign and a plant"),
    ("tent", "Tent", "places", "⛺", "Tent", ["tent", "camping"], "a triangular orange camping tent"),
    ("treehouse", "Treehouse", "places", "🌳", "Treehouse", ["treehouse", "tree", "play"], "a small wooden house up in a tree with a ladder"),
    ("fort", "Fort", "places", "🏰", "Fort", ["fort", "blanket fort", "pillow"], "a blanket fort made of chairs and pillows"),
    ("castle", "Castle", "places", "🏰", "Castle", ["castle", "princess", "king"], "a stone castle with towers and a flag"),
    ("space", "Outer Space", "places", "🌌", "Space", ["space", "planets", "stars"], "planets and stars with a rocket"),
    ("heaven", "Heaven", "places", "☁️", "Heaven", ["heaven", "sky", "clouds"], "soft clouds with golden light rays"),
    ("everywhere", "Everywhere", "places", "🌍", "Everywhere", ["everywhere", "all over", "world"], "a globe with arrows pointing in every direction"),
    ("somewhere_else", "Somewhere Else", "places", "🗺️", "Somewhere else", ["somewhere else", "different place", "go"], "a map with a pin and an arrow to another pin"),

    # --- play / toys ------------------------------------------------------------
    ("lego", "Building Bricks", "play", "🧱", "Building bricks", ["lego", "bricks", "build"], "a pile of colorful interlocking plastic bricks"),
    ("action_figure", "Action Figure", "play", "🦸", "Action figure", ["action figure", "toy", "hero"], "a small superhero action figure toy"),
    ("stuffed_animal", "Stuffed Animal", "play", "🧸", "Stuffed animal", ["stuffed animal", "plush", "teddy"], "a soft brown teddy bear sitting"),
    ("teddy_bear", "Teddy Bear", "play", "🧸", "Teddy bear", ["teddy bear", "bear", "cuddle"], "a fluffy teddy bear with a red bow"),
    ("dinosaur_toy", "Dinosaur Toy", "play", "🦖", "Dinosaur toy", ["dinosaur toy", "t-rex", "toy"], "a green plastic T-rex toy"),
    ("robot_toy", "Robot Toy", "play", "🤖", "Robot toy", ["robot toy", "robot"], "a wind-up tin robot toy"),
    ("toy_truck", "Toy Truck", "play", "🚚", "Toy truck", ["toy truck", "truck", "dump truck"], "a yellow toy dump truck"),
    ("race_car_toy", "Race Car", "play", "🏎️", "Race car", ["race car", "toy car", "fast"], "a red toy race car"),
    ("toy_plane", "Toy Airplane", "play", "✈️", "Toy airplane", ["toy plane", "airplane"], "a small wooden toy airplane"),
    ("boat_toy", "Toy Boat", "play", "⛵", "Toy boat", ["toy boat", "bath toy", "boat"], "a small toy sailboat floating in bath water"),
    ("rubber_duck", "Rubber Duck", "play", "🦆", "Rubber duck", ["rubber duck", "bath toy", "duck"], "a yellow rubber duck"),
    ("bath_toys", "Bath Toys", "play", "🛁", "Bath toys", ["bath toys", "bath", "play"], "a rubber duck, a boat and a cup floating in bubbles"),
    ("marbles", "Marbles", "play", "🔮", "Marbles", ["marbles", "glass", "roll"], "a handful of shiny colorful glass marbles"),
    ("yo_yo", "Yo-Yo", "play", "🪀", "Yo-yo", ["yo-yo", "toy", "string"], "a red yo-yo on a string"),
    ("kite", "Kite", "play", "🪁", "Kite", ["kite", "fly", "wind"], "a colorful diamond kite with a tail in the sky"),
    ("balloon", "Balloon", "play", "🎈", "Balloon", ["balloon", "party", "float"], "a shiny red balloon on a string"),
    ("pinwheel", "Pinwheel", "play", "🌀", "Pinwheel", ["pinwheel", "spin", "wind"], "a colorful pinwheel on a stick"),
    ("jump_rope", "Jump Rope", "play", "🪢", "Jump rope", ["jump rope", "skip", "rope"], "a child jumping over a jump rope"),
    ("hula_hoop", "Hula Hoop", "play", "⭕", "Hula hoop", ["hula hoop", "hoop", "spin"], "a child spinning a hula hoop around their waist"),
    ("frisbee", "Frisbee", "play", "🥏", "Frisbee", ["frisbee", "throw", "disc"], "a flying orange frisbee"),
    ("soccer_ball", "Soccer Ball", "play", "⚽", "Soccer ball", ["soccer ball", "soccer", "kick"], "a black and white soccer ball"),
    ("basketball", "Basketball", "play", "🏀", "Basketball", ["basketball", "hoop", "bounce"], "an orange basketball"),
    ("football", "Football", "play", "🏈", "Football", ["football", "throw", "touchdown"], "a brown football with white laces"),
    ("baseball", "Baseball", "play", "⚾", "Baseball", ["baseball", "bat", "catch"], "a white baseball with red stitching and a bat"),
    ("tennis", "Tennis", "play", "🎾", "Tennis", ["tennis", "racket", "ball"], "a tennis racket and a yellow ball"),
    ("volleyball", "Volleyball", "play", "🏐", "Volleyball", ["volleyball", "net", "ball"], "a white and blue volleyball"),
    ("hockey", "Hockey", "play", "🏒", "Hockey", ["hockey", "stick", "puck"], "a hockey stick and puck"),
    ("golf_toy", "Golf", "play", "⛳", "Golf", ["golf", "ball", "club"], "a golf ball on a tee with a flag"),
    ("bowling", "Bowling", "play", "🎳", "Bowling", ["bowling", "pins", "ball"], "a bowling ball and pins"),
    ("skateboard", "Skateboard", "play", "🛹", "Skateboard", ["skateboard", "skate", "ride"], "a skateboard with colorful wheels"),
    ("roller_skates", "Roller Skates", "play", "🛼", "Roller skates", ["roller skates", "skates", "ride"], "a pair of pink roller skates"),
    ("ice_skates", "Ice Skates", "play", "⛸️", "Ice skates", ["ice skates", "skating", "ice"], "a pair of white ice skates"),
    ("helmet", "Helmet", "play", "⛑️", "Helmet", ["helmet", "bike", "safety"], "a blue bike helmet"),
    ("trampoline", "Trampoline", "play", "🤸", "Trampoline", ["trampoline", "jump", "bounce"], "a round trampoline with a child bouncing"),
    ("seesaw", "Seesaw", "play", "⚖️", "Seesaw", ["seesaw", "teeter totter", "playground"], "two children on a seesaw"),
    ("monkey_bars", "Monkey Bars", "play", "🐒", "Monkey bars", ["monkey bars", "climb", "playground"], "a child hanging from playground monkey bars"),
    ("climbing_wall", "Climbing Wall", "play", "🧗", "Climbing wall", ["climbing wall", "climb", "rocks"], "a child climbing a wall with colorful holds"),
    ("merry_go_round", "Merry-Go-Round", "play", "🎠", "Merry-go-round", ["merry go round", "carousel", "spin"], "a carousel with painted horses"),
    ("ferris_wheel", "Ferris Wheel", "play", "🎡", "Ferris wheel", ["ferris wheel", "ride", "fair"], "a big colorful ferris wheel"),
    ("roller_coaster", "Roller Coaster", "play", "🎢", "Roller coaster", ["roller coaster", "ride", "fast"], "a roller coaster car going down a loop"),
    ("bumper_cars", "Bumper Cars", "play", "🚗", "Bumper cars", ["bumper cars", "ride", "fair"], "two colorful bumper cars bumping"),
    ("water_gun", "Water Gun", "play", "🔫", "Water squirter", ["water gun", "squirt", "summer"], "a colorful plastic water squirter spraying water"),
    ("sprinkler", "Sprinkler", "play", "💦", "Sprinkler", ["sprinkler", "water", "summer"], "a child running through a lawn sprinkler"),
    ("kiddie_pool", "Kiddie Pool", "play", "🏊", "Kiddie pool", ["kiddie pool", "pool", "splash"], "a small round inflatable pool with a child in it"),
    ("sand_toys", "Sand Toys", "play", "🏖️", "Sand toys", ["sand toys", "bucket", "shovel"], "a bucket and shovel in sand with a sandcastle"),
    ("sandcastle", "Sandcastle", "play", "🏰", "Sandcastle", ["sandcastle", "beach", "sand"], "a sandcastle with a small flag"),
    ("snowman", "Snowman", "play", "⛄", "Snowman", ["snowman", "snow", "winter"], "a snowman with a carrot nose and scarf"),
    ("snowball", "Snowball", "play", "❄️", "Snowball", ["snowball", "snow", "throw"], "a child throwing a snowball"),
    ("sled_toy", "Sled", "play", "🛷", "Sled", ["sled", "snow", "ride"], "a red wooden sled"),
    ("magnets", "Magnets", "play", "🧲", "Magnets", ["magnets", "magnetic", "tiles"], "colorful magnetic tiles stuck together"),
    ("marble_run", "Marble Run", "play", "🎢", "Marble run", ["marble run", "build", "roll"], "a colorful marble run track with marbles"),
    ("train_set", "Train Set", "play", "🚂", "Train set", ["train set", "tracks", "train"], "a wooden toy train on a wooden track"),
    ("dollhouse", "Dollhouse", "play", "🏠", "Dollhouse", ["dollhouse", "dolls", "pretend"], "a small open dollhouse with tiny furniture"),
    ("play_kitchen", "Play Kitchen", "play", "🍳", "Play kitchen", ["play kitchen", "pretend", "cook"], "a small toy kitchen with a pot and stove"),
    ("play_food", "Play Food", "play", "🍔", "Play food", ["play food", "pretend", "kitchen"], "plastic toy food: a burger, apple and pizza slice"),
    ("dress_up", "Dress Up", "play", "🎩", "Dress up", ["dress up", "costume", "pretend"], "a trunk of costumes with a hat, cape and crown"),
    ("puppet", "Puppet", "play", "🧦", "Puppet", ["puppet", "hand puppet", "show"], "a hand puppet of a dog on a child's hand"),
    ("tea_party", "Tea Party", "play", "🫖", "Tea party", ["tea party", "pretend", "tea set"], "a toy tea set with tiny cups and a teapot"),
    ("doctor_kit", "Doctor Kit", "play", "🩺", "Doctor kit", ["doctor kit", "pretend", "stethoscope"], "a toy doctor kit with a stethoscope and bandage"),
    ("tool_set", "Tool Set", "play", "🔨", "Tool set", ["tool set", "toy tools", "hammer"], "a toy toolbox with a plastic hammer and wrench"),
    ("cash_register", "Cash Register", "play", "🧾", "Cash register", ["cash register", "pretend", "store"], "a toy cash register with play money"),
    ("walkie_talkie", "Walkie Talkie", "play", "📻", "Walkie talkie", ["walkie talkie", "radio", "talk"], "two toy walkie talkies"),
    ("binoculars", "Binoculars", "play", "🔭", "Binoculars", ["binoculars", "look", "explore"], "a pair of black binoculars"),
    ("magnifying_glass", "Magnifying Glass", "play", "🔍", "Magnifying glass", ["magnifying glass", "look", "explore"], "a magnifying glass over a ladybug"),
    ("flashlight", "Flashlight", "play", "🔦", "Flashlight", ["flashlight", "light", "dark"], "a flashlight shining a beam"),
    ("glow_stick", "Glow Stick", "play", "🟢", "Glow stick", ["glow stick", "glow", "dark"], "bright glowing green and pink glow sticks"),
    ("fidget", "Fidget Toy", "play", "🌀", "Fidget toy", ["fidget", "spinner", "sensory"], "a colorful fidget spinner"),
    ("pop_it", "Pop It", "play", "🫧", "Pop it", ["pop it", "sensory", "bubbles"], "a rainbow silicone pop-it toy"),
    ("stress_ball", "Stress Ball", "play", "🟡", "Stress ball", ["stress ball", "squeeze", "sensory"], "a yellow squishy stress ball being squeezed"),
    ("slime", "Slime", "play", "🟢", "Slime", ["slime", "goo", "sensory"], "green stretchy slime between two hands"),
    ("kinetic_sand", "Kinetic Sand", "play", "🏖️", "Kinetic sand", ["kinetic sand", "sand", "sensory"], "a tray of moldable sand with a scoop"),
    ("sensory_bin", "Sensory Bin", "play", "🫘", "Sensory bin", ["sensory bin", "beans", "scoop"], "a bin of dried beans with a scoop and small toys"),
    ("chewy", "Chewy", "play", "🦷", "Chewy", ["chewy", "chew necklace", "sensory"], "a silicone chew necklace"),
    ("weighted_blanket", "Weighted Blanket", "play", "🛌", "Weighted blanket", ["weighted blanket", "calm", "heavy"], "a child under a thick gray weighted blanket"),
    ("swing_sensory", "Sensory Swing", "play", "🪢", "Sensory swing", ["sensory swing", "swing", "calm"], "a child wrapped in a fabric pod swing"),
    ("bean_bag", "Bean Bag", "play", "🛋️", "Bean bag", ["bean bag", "sit", "cozy"], "a big soft bean bag chair"),
    ("tunnel", "Play Tunnel", "play", "🚇", "Play tunnel", ["tunnel", "crawl", "play"], "a colorful fabric crawl tunnel"),
    ("ball_pit", "Ball Pit", "play", "🎱", "Ball pit", ["ball pit", "balls", "play"], "a pit full of colorful plastic balls with a child"),
    ("bubble_machine", "Bubble Machine", "play", "🫧", "Bubble machine", ["bubble machine", "bubbles"], "a machine blowing many bubbles"),
    ("chalk", "Chalk", "play", "🖍️", "Chalk", ["chalk", "sidewalk", "draw"], "colorful sidewalk chalk sticks with a drawing"),
    ("markers", "Markers", "play", "🖊️", "Markers", ["markers", "draw", "color"], "a set of colorful markers"),
    ("colored_pencils", "Colored Pencils", "play", "✏️", "Colored pencils", ["colored pencils", "draw", "color"], "a fan of colored pencils"),
    ("paint_set", "Paint Set", "play", "🎨", "Paint set", ["paint set", "paint", "brush"], "a watercolor paint set with a brush"),
    ("finger_paint", "Finger Paint", "play", "🖐️", "Finger paint", ["finger paint", "paint", "messy"], "a child's hands covered in paint on paper"),
    ("coloring_book", "Coloring Book", "play", "📖", "Coloring book", ["coloring book", "color", "crayons"], "an open coloring book with a half-colored picture"),
    ("sticker_book", "Sticker Book", "play", "⭐", "Sticker book", ["sticker book", "stickers"], "an open book with sticker pages"),
    ("craft", "Craft", "play", "✂️", "Craft", ["craft", "art project", "glue"], "paper, scissors, glue and glitter on a table"),
    ("beads", "Beads", "play", "📿", "Beads", ["beads", "necklace", "craft"], "a bowl of colorful beads and a string"),
    ("puzzle_big", "Floor Puzzle", "play", "🧩", "Floor puzzle", ["floor puzzle", "puzzle", "big"], "a big floor puzzle half put together"),
    ("card_game", "Card Game", "play", "🃏", "Card game", ["card game", "cards", "uno"], "a hand of colorful playing cards"),
    ("dice", "Dice", "play", "🎲", "Dice", ["dice", "roll", "game"], "two white dice"),
    ("chess", "Chess", "play", "♟️", "Chess", ["chess", "board game", "king"], "a chess board with pieces"),
    ("checkers", "Checkers", "play", "🔴", "Checkers", ["checkers", "board game"], "a checkers board with red and black pieces"),
    ("dominoes", "Dominoes", "play", "🁡", "Dominoes", ["dominoes", "game", "tiles"], "a line of dominoes standing up"),
    ("bingo", "Bingo", "play", "🎱", "Bingo", ["bingo", "game", "numbers"], "a bingo card with chips"),
    ("tic_tac_toe", "Tic Tac Toe", "play", "❌", "Tic tac toe", ["tic tac toe", "game", "x and o"], "a tic tac toe grid with X and O"),
    ("video_game_controller", "Game Controller", "play", "🎮", "Game controller", ["controller", "video game", "play"], "a game controller with colorful buttons"),
    ("handheld_game", "Handheld Game", "play", "🕹️", "Handheld game", ["handheld", "switch", "video game"], "a handheld gaming device with a colorful screen"),
    ("vr", "VR Headset", "play", "🥽", "VR headset", ["vr", "virtual reality", "headset"], "a child wearing a virtual reality headset"),
    ("movie", "Movie", "play", "🎬", "Movie", ["movie", "film", "watch"], "a movie clapperboard and popcorn"),
    ("cartoon", "Cartoon", "play", "📺", "Cartoon", ["cartoon", "show", "tv"], "a tv screen showing a colorful cartoon character"),
    ("youtube", "Videos", "play", "▶️", "Watch videos", ["youtube", "videos", "watch"], "a tablet with a play button on the screen"),
    ("music_player", "Music", "play", "🎵", "Music", ["music", "songs", "listen"], "a music player with headphones and notes"),
    ("song", "Song", "play", "🎶", "Song", ["song", "sing", "music"], "a music note with sound waves"),
    ("dance_party", "Dance Party", "play", "🪩", "Dance party", ["dance party", "dance", "disco"], "children dancing under a disco ball"),
    ("karaoke", "Karaoke", "play", "🎤", "Karaoke", ["karaoke", "sing", "microphone"], "a child singing into a microphone with a screen"),
    ("story_time", "Story Time", "play", "📖", "Story time", ["story time", "book", "read"], "an adult reading a picture book to children on a rug"),
    ("audiobook", "Audiobook", "play", "🎧", "Audiobook", ["audiobook", "listen", "story"], "headphones over a book"),
    ("comic", "Comic Book", "play", "💥", "Comic book", ["comic", "superhero", "read"], "an open comic book with action panels"),
    ("magazine", "Magazine", "play", "📰", "Magazine", ["magazine", "read"], "a glossy magazine with a colorful cover"),
    ("library_book", "Library Book", "play", "📚", "Library book", ["library book", "borrow", "read"], "a book with a library barcode sticker"),
    ("scavenger_hunt", "Scavenger Hunt", "play", "🗺️", "Scavenger hunt", ["scavenger hunt", "find", "list"], "a child with a checklist and magnifying glass looking around"),
    ("hide_and_seek", "Hide and Seek", "play", "🙈", "Hide and seek", ["hide and seek", "hide", "find"], "a child counting against a wall while another hides behind a tree"),
    ("simon_says", "Simon Says", "play", "🫵", "Simon says", ["simon says", "game", "copy"], "an adult touching their head while children copy"),
    ("freeze_dance", "Freeze Dance", "play", "🧊", "Freeze dance", ["freeze dance", "dance", "stop"], "children frozen mid-dance pose"),
    ("duck_duck_goose", "Duck Duck Goose", "play", "🦆", "Duck duck goose", ["duck duck goose", "circle game"], "children sitting in a circle with one tapping heads"),
    ("hopscotch", "Hopscotch", "play", "🦘", "Hopscotch", ["hopscotch", "chalk", "hop"], "a chalk hopscotch grid with a child hopping"),
    ("catch_game", "Play Catch", "play", "🤾", "Play catch", ["catch", "throw", "ball"], "two children tossing a ball to each other"),
    ("water_balloons", "Water Balloons", "play", "🎈", "Water balloons", ["water balloons", "splash", "summer"], "a bucket of colorful water balloons"),
    ("tag_game", "Tag", "play", "🏃", "Play tag", ["tag", "chase", "run"], "children running and chasing on grass"),
    ("play_date", "Play Date", "play", "🤝", "Play date", ["play date", "friend", "visit"], "two children playing with blocks together at a house"),
    ("sleepover", "Sleepover", "play", "🛌", "Sleepover", ["sleepover", "friend", "night"], "two children in sleeping bags with a flashlight"),
    ("birthday_party", "Birthday Party", "play", "🥳", "Birthday party", ["birthday party", "party", "balloons"], "children in party hats around a cake with balloons"),
    ("pinata", "Pinata", "play", "🪅", "Pinata", ["pinata", "party", "candy"], "a colorful donkey pinata with candy falling out"),
    ("party_hat", "Party Hat", "play", "🎉", "Party hat", ["party hat", "party"], "a striped cone party hat"),
    ("present", "Present", "play", "🎁", "Present", ["present", "gift", "wrapped"], "a wrapped gift box with a big bow"),
    ("parade", "Parade", "play", "🎺", "Parade", ["parade", "march", "band"], "a marching band with a float and balloons"),
    ("fireworks", "Fireworks", "play", "🎆", "Fireworks", ["fireworks", "boom", "night"], "colorful fireworks bursting in a night sky"),
    ("circus", "Circus", "play", "🎪", "Circus", ["circus", "tent", "clown"], "a striped red circus tent with a flag"),
    ("magic_show", "Magic Show", "play", "🎩", "Magic show", ["magic show", "magician", "trick"], "a magician pulling a rabbit out of a hat"),
    ("concert", "Concert", "play", "🎤", "Concert", ["concert", "music", "band"], "a band on a stage with lights and a crowd"),
    ("play_theater", "Play / Show", "play", "🎭", "A play", ["play", "show", "theater"], "children in costumes on a stage with a curtain"),
    ("game_night", "Game Night", "play", "🎲", "Game night", ["game night", "board game", "family"], "a family around a table playing a board game"),
    ("movie_night", "Movie Night", "play", "🍿", "Movie night", ["movie night", "popcorn", "watch"], "a family on a couch with popcorn watching a tv"),
    ("screen_time", "Screen Time", "play", "📱", "Screen time", ["screen time", "tablet", "phone"], "a child holding a tablet with a timer beside"),
    ("no_screens", "No Screens", "play", "📵", "No screens", ["no screens", "screen time over", "put away"], "a tablet with a red no symbol over it"),
    ("free_time", "Free Time", "play", "🕰️", "Free time", ["free time", "choice", "play"], "a child choosing between toys, a book and blocks"),
    ("my_choice", "My Choice", "play", "🙋", "My choice", ["my choice", "choose", "pick"], "a child pointing at a toy with a star above"),
    ("all_done_playing", "Done Playing", "play", "🧹", "All done playing", ["done playing", "clean up", "finished"], "a child putting toys into a bin"),

    # --- daily life / clothing --------------------------------------------------
    ("t_shirt", "T-Shirt", "daily", "👕", "T-shirt", ["t-shirt", "shirt", "top"], "a plain green t-shirt"),
    ("long_sleeve", "Long Sleeve Shirt", "daily", "👔", "Long sleeve shirt", ["long sleeve", "shirt"], "a striped long-sleeve shirt"),
    ("hoodie", "Hoodie", "daily", "🧥", "Hoodie", ["hoodie", "sweatshirt", "hood"], "a gray hoodie with a pocket"),
    ("tank_top", "Tank Top", "daily", "🎽", "Tank top", ["tank top", "sleeveless", "summer"], "a blue tank top"),
    ("jeans", "Jeans", "daily", "👖", "Jeans", ["jeans", "pants", "denim"], "a pair of blue jeans"),
    ("leggings", "Leggings", "daily", "🩱", "Leggings", ["leggings", "pants", "stretchy"], "a pair of black leggings"),
    ("sweatpants", "Sweatpants", "daily", "👖", "Sweatpants", ["sweatpants", "pants", "comfy"], "a pair of gray sweatpants"),
    ("skirt", "Skirt", "daily", "👗", "Skirt", ["skirt", "clothes"], "a pleated pink skirt"),
    ("overalls", "Overalls", "daily", "👖", "Overalls", ["overalls", "clothes"], "a pair of denim overalls"),
    ("onesie", "Onesie", "daily", "👶", "Onesie", ["onesie", "baby", "clothes"], "a baby onesie with snaps"),
    ("swimsuit", "Swimsuit", "daily", "🩱", "Swimsuit", ["swimsuit", "bathing suit", "swim"], "a blue swimsuit and swim trunks"),
    ("swim_trunks", "Swim Trunks", "daily", "🩳", "Swim trunks", ["swim trunks", "shorts", "swim"], "a pair of orange swim trunks"),
    ("raincoat", "Raincoat", "daily", "🧥", "Raincoat", ["raincoat", "rain", "jacket"], "a yellow raincoat with a hood"),
    ("rain_boots", "Rain Boots", "daily", "👢", "Rain boots", ["rain boots", "boots", "puddles"], "a pair of red rubber rain boots"),
    ("snow_pants", "Snow Pants", "daily", "🎿", "Snow pants", ["snow pants", "winter", "snow"], "a pair of puffy blue snow pants"),
    ("mittens", "Mittens", "daily", "🧤", "Mittens", ["mittens", "hands", "winter"], "a pair of red knit mittens"),
    ("scarf", "Scarf", "daily", "🧣", "Scarf", ["scarf", "neck", "winter"], "a striped wool scarf"),
    ("winter_hat", "Winter Hat", "daily", "🧢", "Winter hat", ["winter hat", "beanie", "warm"], "a knit beanie with a pom-pom"),
    ("earmuffs", "Earmuffs", "daily", "🎧", "Earmuffs", ["earmuffs", "ears", "winter"], "a pair of fluffy pink earmuffs"),
    ("sun_hat", "Sun Hat", "daily", "👒", "Sun hat", ["sun hat", "hat", "summer"], "a wide-brimmed straw sun hat"),
    ("cap", "Baseball Cap", "daily", "🧢", "Baseball cap", ["cap", "hat", "baseball"], "a red baseball cap"),
    ("sunglasses", "Sunglasses", "daily", "🕶️", "Sunglasses", ["sunglasses", "shades", "sun"], "a pair of dark sunglasses"),
    ("sandals", "Sandals", "daily", "👡", "Sandals", ["sandals", "summer", "shoes"], "a pair of brown sandals"),
    ("flip_flops", "Flip Flops", "daily", "🩴", "Flip flops", ["flip flops", "beach", "shoes"], "a pair of blue flip flops"),
    ("sneakers", "Sneakers", "daily", "👟", "Sneakers", ["sneakers", "running shoes", "shoes"], "a pair of white and blue sneakers"),
    ("slippers", "Slippers", "daily", "🥿", "Slippers", ["slippers", "cozy", "house shoes"], "a pair of fluffy bunny slippers"),
    ("dress_shoes", "Dress Shoes", "daily", "👞", "Dress shoes", ["dress shoes", "fancy", "shoes"], "a pair of shiny black dress shoes"),
    ("belt", "Belt", "daily", "🧵", "Belt", ["belt", "pants"], "a brown leather belt with a buckle"),
    ("tie", "Tie", "daily", "👔", "Tie", ["tie", "necktie", "fancy"], "a blue striped necktie"),
    ("bow_tie", "Bow Tie", "daily", "🎀", "Bow tie", ["bow tie", "fancy"], "a red bow tie"),
    ("uniform", "Uniform", "daily", "👔", "Uniform", ["uniform", "school clothes"], "a white collared shirt with a navy sweater vest"),
    ("costume", "Costume", "daily", "🎭", "Costume", ["costume", "dress up", "halloween"], "a child in a lion costume"),
    ("apron", "Apron", "daily", "🥻", "Apron", ["apron", "cooking", "art"], "a red apron with a pocket"),
    ("bib", "Bib", "daily", "👶", "Bib", ["bib", "baby", "eat"], "a baby bib with a duck on it"),
    ("pull_up", "Pull-Up", "daily", "🩲", "Pull-up", ["pull-up", "training pants", "potty"], "a pair of training pants with a star pattern"),
    ("wipes", "Wipes", "daily", "🧻", "Wipes", ["wipes", "clean", "baby"], "a pack of baby wipes with one pulled out"),
    ("hair_tie", "Hair Tie", "daily", "🎀", "Hair tie", ["hair tie", "ponytail", "hair"], "colorful elastic hair ties"),
    ("headband", "Headband", "daily", "👸", "Headband", ["headband", "hair"], "a pink headband with a bow"),
    ("necklace", "Necklace", "daily", "📿", "Necklace", ["necklace", "jewelry"], "a gold necklace with a heart pendant"),
    ("bracelet", "Bracelet", "daily", "📿", "Bracelet", ["bracelet", "jewelry", "wrist"], "a beaded bracelet"),
    ("ring_daily", "Ring", "daily", "💍", "Ring", ["ring", "jewelry", "finger"], "a gold ring with a gem"),
    ("watch_daily", "Watch", "daily", "⌚", "Watch", ["watch", "time", "wrist"], "a wristwatch"),
    ("wallet", "Wallet", "daily", "👛", "Wallet", ["wallet", "money", "cards"], "a brown wallet with cards"),
    ("purse", "Purse", "daily", "👜", "Purse", ["purse", "bag", "handbag"], "a red handbag"),
    ("keys", "Keys", "daily", "🔑", "Keys", ["keys", "door", "car"], "a ring of keys"),
    ("umbrella", "Umbrella", "daily", "☂️", "Umbrella", ["umbrella", "rain"], "an open red umbrella"),
    ("laundry", "Laundry", "daily", "🧺", "Laundry", ["laundry", "clothes", "wash"], "a basket piled with clothes"),
    ("washing_machine", "Washing Machine", "daily", "🫧", "Washing machine", ["washing machine", "washer", "laundry"], "a front-load washing machine with suds"),
    ("dryer", "Dryer", "daily", "🌀", "Dryer", ["dryer", "laundry", "warm"], "a clothes dryer with a warm glow"),
    ("hanger", "Hanger", "daily", "🪝", "Hanger", ["hanger", "closet", "clothes"], "a wooden clothes hanger"),
    ("dresser", "Dresser", "daily", "🗄️", "Dresser", ["dresser", "drawers", "clothes"], "a wooden dresser with drawers"),
    ("drawer", "Drawer", "daily", "🗄️", "Drawer", ["drawer", "open", "put away"], "an open dresser drawer with folded shirts"),
    ("shelf", "Shelf", "daily", "🪜", "Shelf", ["shelf", "put away", "books"], "a wall shelf with books and a plant"),
    ("basket", "Basket", "daily", "🧺", "Basket", ["basket", "toys", "carry"], "a woven basket"),
    ("bin", "Bin", "daily", "📦", "Bin", ["bin", "box", "toys"], "a blue plastic storage bin with a lid"),
    ("trash_can", "Trash Can", "daily", "🗑️", "Trash can", ["trash can", "garbage", "throw away"], "a gray trash can with a lid"),
    ("recycling_bin", "Recycling Bin", "daily", "♻️", "Recycling bin", ["recycling", "bin", "bottles"], "a blue bin with a recycling symbol"),
    ("broom", "Broom", "daily", "🧹", "Broom", ["broom", "sweep", "clean"], "a broom and dustpan"),
    ("mop", "Mop", "daily", "🪣", "Mop", ["mop", "floor", "clean"], "a mop and a bucket"),
    ("sponge", "Sponge", "daily", "🧽", "Sponge", ["sponge", "wash", "clean"], "a yellow sponge with bubbles"),
    ("spray_bottle", "Spray Bottle", "daily", "🧴", "Spray bottle", ["spray", "cleaner", "clean"], "a spray bottle spraying mist"),
    ("paper_towel", "Paper Towel", "daily", "🧻", "Paper towel", ["paper towel", "wipe", "clean"], "a roll of paper towels"),
    ("toilet_paper", "Toilet Paper", "daily", "🧻", "Toilet paper", ["toilet paper", "bathroom"], "a roll of toilet paper"),
    ("toilet", "Toilet", "daily", "🚽", "Toilet", ["toilet", "bathroom", "potty"], "a white toilet"),
    ("sink", "Sink", "daily", "🚰", "Sink", ["sink", "faucet", "wash"], "a bathroom sink with a faucet"),
    ("bathtub", "Bathtub", "daily", "🛁", "Bathtub", ["bathtub", "bath", "tub"], "a white bathtub with bubbles"),
    ("shower_head", "Shower", "daily", "🚿", "Shower", ["shower", "wash", "water"], "a shower head spraying water"),
    ("faucet", "Faucet", "daily", "🚰", "Faucet", ["faucet", "tap", "water"], "a faucet with water running"),
    ("plunger", "Plunger", "daily", "🪠", "Plunger", ["plunger", "toilet", "clog"], "a red plunger"),
    ("shampoo", "Shampoo", "daily", "🧴", "Shampoo", ["shampoo", "hair", "wash"], "a bottle of shampoo"),
    ("conditioner", "Conditioner", "daily", "🧴", "Conditioner", ["conditioner", "hair"], "a bottle of hair conditioner"),
    ("body_wash", "Body Wash", "daily", "🧼", "Body wash", ["body wash", "soap", "shower"], "a bottle of body wash with bubbles"),
    ("bar_soap", "Bar of Soap", "daily", "🧼", "Bar of soap", ["bar soap", "soap", "wash"], "a bar of soap with bubbles"),
    ("hand_sanitizer", "Hand Sanitizer", "daily", "🧴", "Hand sanitizer", ["sanitizer", "germs", "clean hands"], "a pump bottle of hand sanitizer"),
    ("toothpaste", "Toothpaste", "daily", "🪥", "Toothpaste", ["toothpaste", "teeth", "brush"], "a tube of toothpaste squeezing onto a brush"),
    ("mouthwash", "Mouthwash", "daily", "🫧", "Mouthwash", ["mouthwash", "rinse", "teeth"], "a bottle of blue mouthwash with a cup"),
    ("dental_floss", "Floss", "daily", "🧵", "Dental floss", ["floss", "teeth"], "a container of dental floss"),
    ("deodorant", "Deodorant", "daily", "🧴", "Deodorant", ["deodorant", "armpits", "hygiene"], "a stick of deodorant"),
    ("sunscreen", "Sunscreen", "daily", "🧴", "Sunscreen", ["sunscreen", "sun", "protect"], "a bottle of sunscreen with a sun"),
    ("bug_spray", "Bug Spray", "daily", "🦟", "Bug spray", ["bug spray", "mosquito", "outside"], "a can of bug spray with a crossed-out mosquito"),
    ("chapstick", "Chapstick", "daily", "💄", "Chapstick", ["chapstick", "lip balm", "lips"], "a tube of lip balm"),
    ("nail_clippers", "Nail Clippers", "daily", "💅", "Nail clippers", ["nail clippers", "nails", "trim"], "a pair of nail clippers"),
    ("cotton_swab", "Cotton Swab", "daily", "🩹", "Cotton swab", ["cotton swab", "q-tip", "ears"], "cotton swabs in a jar"),
    ("razor", "Razor", "daily", "🪒", "Razor", ["razor", "shave"], "a safety razor with foam"),
    ("mirror", "Mirror", "daily", "🪞", "Mirror", ["mirror", "look", "reflection"], "a round mirror with a child's reflection"),
    ("scale_weight", "Scale", "daily", "⚖️", "Scale", ["scale", "weigh", "bathroom"], "a bathroom scale"),
    ("hair_dryer", "Hair Dryer", "daily", "💨", "Hair dryer", ["hair dryer", "blow dry", "hair"], "a hair dryer blowing warm air"),
    ("bathrobe", "Bathrobe", "daily", "🥋", "Bathrobe", ["bathrobe", "robe", "cozy"], "a fluffy white bathrobe"),
    ("washcloth", "Washcloth", "daily", "🧻", "Washcloth", ["washcloth", "wash", "face"], "a folded blue washcloth"),
    ("bath_mat", "Bath Mat", "daily", "🛁", "Bath mat", ["bath mat", "rug", "bathroom"], "a fluffy bath mat by a tub"),
    ("alarm_clock", "Alarm Clock", "daily", "⏰", "Alarm clock", ["alarm clock", "wake up", "morning"], "a ringing alarm clock"),
    ("night_light", "Night Light", "daily", "🌙", "Night light", ["night light", "dark", "bedtime"], "a small glowing star-shaped night light plugged into a wall outlet, cut out on white with no room"),
    ("lamp", "Lamp", "daily", "🛋️", "Lamp", ["lamp", "light", "bedside"], "a bedside table lamp turned on"),
    ("sheets", "Sheets", "daily", "🛏️", "Sheets", ["sheets", "bed", "bedding"], "folded blue bed sheets"),
    ("comforter", "Comforter", "daily", "🛌", "Comforter", ["comforter", "blanket", "bed"], "a fluffy comforter on a bed"),
    ("sleeping_bag", "Sleeping Bag", "daily", "🛌", "Sleeping bag", ["sleeping bag", "camping", "sleep"], "a rolled-out blue sleeping bag"),
    ("crib", "Crib", "daily", "👶", "Crib", ["crib", "baby", "bed"], "a wooden baby crib"),
    ("bunk_bed", "Bunk Bed", "daily", "🛏️", "Bunk bed", ["bunk bed", "bed", "ladder"], "a bunk bed with a ladder"),
    ("rug", "Rug", "daily", "🟫", "Rug", ["rug", "carpet", "floor"], "a colorful round rug"),
    ("curtains", "Curtains", "daily", "🪟", "Curtains", ["curtains", "window", "close"], "a window with blue curtains"),
    ("blinds", "Blinds", "daily", "🪟", "Blinds", ["blinds", "window", "shade"], "a window with white blinds half open"),
    ("fan", "Fan", "daily", "🌀", "Fan", ["fan", "cool", "air"], "a standing electric fan"),
    ("heater", "Heater", "daily", "🔥", "Heater", ["heater", "warm", "heat"], "a space heater with a warm glow"),
    ("air_conditioner", "Air Conditioner", "daily", "❄️", "Air conditioner", ["air conditioner", "ac", "cool"], "a window air conditioner blowing cold air"),
    ("thermostat", "Thermostat", "daily", "🌡️", "Thermostat", ["thermostat", "temperature", "warm"], "a wall thermostat dial"),
    ("light_switch", "Light Switch", "daily", "💡", "Light switch", ["light switch", "on", "off"], "a wall light switch"),
    ("outlet", "Outlet", "daily", "🔌", "Outlet", ["outlet", "plug", "electric"], "a wall power outlet"),
    ("batteries", "Batteries", "daily", "🔋", "Batteries", ["batteries", "power", "dead"], "two AA batteries"),
    ("candle", "Candle", "daily", "🕯️", "Candle", ["candle", "light", "flame"], "a lit candle"),
    ("clock", "Clock", "daily", "🕐", "Clock", ["clock", "time", "wall"], "a round wall clock"),
    ("calendar_wall", "Wall Calendar", "daily", "📆", "Calendar", ["calendar", "date", "month"], "a wall calendar with a picture and a circled day"),
    ("mail", "Mail", "daily", "📬", "Mail", ["mail", "letters", "mailbox"], "a mailbox with letters inside"),
    ("package", "Package", "daily", "📦", "Package", ["package", "box", "delivery"], "a cardboard box with tape"),
    ("newspaper", "Newspaper", "daily", "📰", "Newspaper", ["newspaper", "news", "read"], "a folded newspaper"),
    ("garbage_bag", "Garbage Bag", "daily", "🗑️", "Garbage bag", ["garbage bag", "trash", "bag"], "a tied black garbage bag"),
    ("chores", "Chores", "daily", "📋", "Chores", ["chores", "jobs", "help out"], "a checklist with a broom, dishes and laundry icons"),
    ("allowance", "Allowance", "daily", "💵", "Allowance", ["allowance", "money", "earn"], "a child receiving coins in a jar"),
    ("routine", "Routine", "daily", "📋", "Routine", ["routine", "schedule", "steps"], "a vertical strip of four small picture cards: a sun, a toothbrush, a shirt, a bowl, each with a green check box, no words"),
    ("schedule", "Schedule", "daily", "🗓️", "Schedule", ["schedule", "plan", "day"], "a daily schedule board with time slots and pictures"),
    ("timer", "Timer", "daily", "⏲️", "Timer", ["timer", "time", "minutes"], "a kitchen timer counting down"),
    ("first_then", "First / Then", "daily", "➡️", "First then", ["first then", "first", "then"], "a board with two empty picture frames side by side joined by a big green arrow, a pencil icon in the first and a ball icon in the second"),
    ("all_done_board", "All Done", "daily", "✅", "All done", ["all done", "finished", "check"], "a picture schedule with every step checked off"),
    ("morning_routine", "Morning Routine", "daily", "🌅", "Morning routine", ["morning routine", "morning", "get ready"], "a strip of pictures: wake up, brush teeth, get dressed, eat"),
    ("bedtime_routine", "Bedtime Routine", "daily", "🌙", "Bedtime routine", ["bedtime routine", "night", "sleep"], "a strip of pictures: bath, pajamas, book, bed"),
    ("weekday", "Weekday", "daily", "📅", "Weekday", ["weekday", "school day", "work"], "a calendar with Monday to Friday highlighted"),
    ("monday", "Monday", "daily", "1️⃣", "Monday", ["monday", "day", "week"], "a calendar page with the first weekday highlighted, school bus icon"),
    ("friday", "Friday", "daily", "5️⃣", "Friday", ["friday", "day", "week"], "a calendar page with the last weekday highlighted, party icon"),
    ("saturday", "Saturday", "daily", "6️⃣", "Saturday", ["saturday", "weekend", "day"], "a calendar page with a weekend day highlighted, playground icon"),
    ("sunday", "Sunday", "daily", "7️⃣", "Sunday", ["sunday", "weekend", "day"], "a calendar page with a weekend day highlighted, family icon"),
    ("afternoon", "Afternoon", "daily", "🌤️", "Afternoon", ["afternoon", "after lunch", "day"], "a sun halfway across the sky over a house"),
    ("evening", "Evening", "daily", "🌆", "Evening", ["evening", "sunset", "dinner"], "a sunset sky over a house with lights on"),
    ("midnight", "Midnight", "daily", "🌃", "Midnight", ["midnight", "night", "late"], "a dark sky with a moon and a clock showing twelve"),
    ("noon", "Noon", "daily", "🕛", "Noon", ["noon", "lunchtime", "twelve"], "a sun at the top of the sky with a clock showing twelve"),
    ("minute", "Minute", "daily", "⏱️", "One minute", ["minute", "one minute", "short"], "a clock with one minute highlighted"),
    ("hour", "Hour", "daily", "🕐", "One hour", ["hour", "one hour", "long"], "a clock with a full hour sweep highlighted"),
    ("week", "Week", "daily", "🗓️", "Week", ["week", "seven days"], "a row of seven calendar boxes"),
    ("month", "Month", "daily", "📆", "Month", ["month", "calendar"], "a full month calendar grid"),
    ("year", "Year", "daily", "🎉", "Year", ["year", "twelve months"], "a stack of twelve small calendar pages"),
    ("spring", "Spring", "daily", "🌷", "Spring", ["spring", "season", "flowers"], "tulips blooming with a butterfly"),
    ("summer", "Summer", "daily", "☀️", "Summer", ["summer", "season", "hot"], "a bright sun over a beach with a beach ball"),
    ("fall", "Fall", "daily", "🍂", "Fall", ["fall", "autumn", "leaves"], "orange and red leaves falling from a tree"),
    ("winter", "Winter", "daily", "❄️", "Winter", ["winter", "season", "snow"], "a snowy tree with snowflakes"),
]
