# Additional AAC vocabulary the 320-entry base catalog was missing.
# Each tuple: (id, label, category, emoji_fallback, tts, [tags], image_subject)
# image_subject is what the picture should show — the style wrapper is added by build_prompts.py.

EXTRA = [
    # --- core / grammar words -------------------------------------------------
    ("come", "Come", "core", "👋", "Come here", ["come", "come here", "over here"], "a friendly child waving and beckoning someone to come over"),
    ("take", "Take", "core", "🤏", "Take", ["take", "grab", "pick up"], "a hand picking up a small red block from a table"),
    ("feel", "Feel", "core", "💗", "I feel", ["feel", "feeling", "emotion"], "a child with a hand on their chest, thoughtful expression, small heart glowing"),
    ("think", "Think", "core", "💭", "I think", ["think", "idea", "thought"], "a child with a finger on their chin and a thought bubble with a lightbulb"),
    ("know", "Know", "core", "💡", "I know", ["know", "understand", "got it"], "a child smiling and pointing to their head with a glowing lightbulb above"),
    ("dont_know", "Don't Know", "core", "🤷", "I don't know", ["don't know", "unsure", "shrug", "not sure"], "a child shrugging with both palms up and a puzzled face"),
    ("say", "Say", "core", "🗣️", "Say", ["say", "speak", "talk", "tell"], "a child's profile speaking with a big speech bubble"),
    ("ask", "Ask", "core", "🙋", "I want to ask", ["ask", "question", "raise hand"], "a child raising a hand high with a question mark above"),
    ("can", "Can", "core", "💪", "Can I", ["can", "able", "may i"], "a strong flexed arm with a green check mark"),
    ("do", "Do", "core", "⚙️", "Do", ["do", "does", "doing", "action"], "two hands building something with colorful blocks"),
    ("have", "Have", "core", "🤲", "I have", ["have", "has", "got", "own"], "two cupped hands holding a gift box"),
    ("this", "This", "core", "👇", "This", ["this", "here", "point"], "a hand pointing down at a red ball right in front"),
    ("that", "That", "core", "👉", "That", ["that", "there", "point"], "a hand pointing far away toward a distant blue ball"),
    ("some", "Some", "core", "🍪", "Some", ["some", "a few", "part"], "a plate with three cookies and two empty spots"),
    ("all", "All", "core", "🔵", "All", ["all", "every", "everything"], "a group of many colorful balls all gathered inside one circle"),
    ("first", "First", "core", "1️⃣", "First", ["first", "one", "begin", "start"], "a big number 1 on a podium with a gold ribbon"),
    ("next", "Next", "core", "⏭️", "Next", ["next", "then", "after that"], "a bold right-pointing arrow with a second one following it"),
    ("last", "Last", "core", "🏁", "Last", ["last", "end", "final"], "a checkered finish flag at the end of a short path"),
    ("before", "Before", "core", "⏮️", "Before", ["before", "earlier", "previous"], "a clock with an arrow pointing back to the left"),
    ("after", "After", "core", "⏭️", "After", ["after", "later", "then"], "a clock with an arrow pointing forward to the right"),
    ("today", "Today", "core", "📅", "Today", ["today", "day", "now"], "a calendar page with the current day circled in red"),
    ("tomorrow", "Tomorrow", "core", "🌅", "Tomorrow", ["tomorrow", "next day"], "a calendar with an arrow pointing to the next day and a rising sun"),
    ("yesterday", "Yesterday", "core", "🌇", "Yesterday", ["yesterday", "last day"], "a calendar with an arrow pointing to the previous day and a setting sun"),
    ("morning", "Morning", "core", "🌄", "Good morning", ["morning", "sunrise", "wake up"], "a bright sunrise over green hills with a rooster"),
    ("night", "Night", "core", "🌙", "Night", ["night", "dark", "bedtime"], "a crescent moon and stars over a sleeping house"),
    ("hot", "Hot", "core", "🌡️", "It is hot", ["hot", "warm", "heat"], "a thermometer bursting red at the top with a blazing sun"),
    ("cold", "Cold", "core", "🧊", "It is cold", ["cold", "chilly", "freezing"], "a thermometer with a blue bottom, snowflakes and an ice cube"),
    ("loud", "Loud", "core", "📢", "Too loud", ["loud", "noisy", "volume"], "a megaphone with big sound waves"),
    ("quiet", "Quiet", "core", "🤫", "Quiet please", ["quiet", "shh", "silence"], "a child holding a finger to their lips, shh"),
    ("new", "New", "core", "✨", "New", ["new", "fresh", "brand new"], "a shiny gift box with a bright NEW-style sparkle burst, no text"),
    ("old", "Old", "core", "🧸", "Old", ["old", "worn"], "a worn faded teddy bear with a patch"),
    ("clean", "Clean", "core", "✨", "Clean", ["clean", "tidy", "sparkle"], "a sparkling clean shirt with shine stars"),
    ("dirty", "Dirty", "core", "🟤", "Dirty", ["dirty", "messy", "mud"], "a shirt splattered with brown mud spots"),
    ("wet", "Wet", "core", "💦", "Wet", ["wet", "water", "soaked"], "a dripping wet sock with water drops"),
    ("dry", "Dry", "core", "☀️", "Dry", ["dry", "towel"], "a fluffy dry towel next to a small sun"),
    ("full", "Full", "core", "🥛", "Full", ["full", "filled"], "a glass filled to the top with milk"),
    ("empty", "Empty", "core", "🥛", "Empty", ["empty", "gone", "nothing"], "an empty clear glass"),
    ("many", "Many", "core", "🎈", "Many", ["many", "lots", "a lot"], "a big bunch of many colorful balloons"),
    ("few", "Few", "core", "🎈", "A few", ["few", "little bit", "not many"], "two balloons, one red one blue"),
    ("inside", "Inside", "core", "🏠", "Inside", ["inside", "indoors", "in"], "a child inside a cozy house looking out the window"),
    ("outside", "Outside", "core", "🌳", "Outside", ["outside", "outdoors", "out"], "a child standing outside on grass under the sun with a tree"),

    # --- people --------------------------------------------------------------
    ("boy", "Boy", "people", "👦", "Boy", ["boy", "kid", "he"], "a smiling boy with short brown hair in a striped shirt, portrait"),
    ("girl", "Girl", "people", "👧", "Girl", ["girl", "kid", "she"], "a smiling girl with pigtails in a yellow shirt, portrait"),
    ("man", "Man", "people", "👨", "Man", ["man", "adult", "he"], "a friendly adult man with a beard in a blue shirt, portrait"),
    ("woman", "Woman", "people", "👩", "Woman", ["woman", "adult", "she"], "a friendly adult woman with curly hair in a green top, portrait"),
    ("aunt", "Aunt", "people", "👩", "Aunt", ["aunt", "auntie", "family"], "a smiling woman with glasses waving, portrait"),
    ("uncle", "Uncle", "people", "👨", "Uncle", ["uncle", "family"], "a smiling man with a mustache waving, portrait"),
    ("cousin", "Cousin", "people", "🧒", "Cousin", ["cousin", "family"], "two kids of different ages standing together smiling"),
    ("bus_driver", "Bus Driver", "people", "🧑‍✈️", "Bus driver", ["bus driver", "driver"], "a smiling bus driver in a cap behind a big steering wheel"),
    ("coach", "Coach", "people", "🧑‍🏫", "Coach", ["coach", "sports", "gym"], "a coach with a whistle and a clipboard"),
    ("babysitter", "Babysitter", "people", "🧑", "Babysitter", ["babysitter", "sitter", "helper"], "a young adult reading a picture book to a small child"),
    ("me_self", "Me", "people", "🙋", "Me", ["me", "myself", "self"], "a child pointing at their own chest with a smile"),
    ("everyone", "Everyone", "people", "👥", "Everyone", ["everyone", "everybody", "all", "group"], "a diverse group of six people standing together smiling, no letters"),

    # --- body ----------------------------------------------------------------
    ("nose", "Nose", "health", "👃", "Nose", ["nose", "smell", "body"], "a close-up of a child's face with the nose highlighted"),
    ("arm", "Arm", "health", "💪", "Arm", ["arm", "body"], "a child's arm with the elbow bent, outlined"),
    ("leg", "Leg", "health", "🦵", "Leg", ["leg", "body", "knee"], "a child's leg with the knee, outlined"),
    ("tummy", "Tummy", "health", "🫃", "Tummy", ["tummy", "stomach", "belly"], "a child with both hands on their belly"),
    ("back_body", "Back", "health", "🧍", "My back", ["back", "spine", "body"], "a child seen from behind with a hand on their back"),
    ("teeth", "Teeth", "health", "🦷", "Teeth", ["teeth", "tooth", "dentist"], "a big smiling mouth showing clean white teeth"),
    ("hair", "Hair", "health", "💇", "Hair", ["hair", "brush", "haircut"], "a child's head with long wavy brown hair and a brush"),
    ("throat", "Throat", "health", "🗣️", "My throat hurts", ["throat", "sore throat", "neck"], "a child touching their throat with a red glow"),
    ("itchy", "Itchy", "health", "🤚", "I feel itchy", ["itchy", "itch", "scratch"], "a child scratching their arm with little red dots"),
    ("dizzy", "Dizzy", "health", "😵‍💫", "I feel dizzy", ["dizzy", "spinning", "faint"], "a child with swirly eyes and stars circling their head"),
    ("allergy", "Allergy", "health", "🤧", "I have an allergy", ["allergy", "allergic", "sneeze"], "a child sneezing near flowers with a warning symbol"),
    ("shot_vaccine", "Shot", "health", "💉", "I need a shot", ["shot", "vaccine", "needle", "injection"], "a nurse giving a shot in an arm with a small bandaid"),
    ("inhaler", "Inhaler", "health", "🌬️", "I need my inhaler", ["inhaler", "asthma", "breathe"], "a blue asthma inhaler"),
    ("thermometer", "Thermometer", "health", "🌡️", "Check my temperature", ["thermometer", "temperature", "fever"], "a digital thermometer"),
    ("ice_pack", "Ice Pack", "health", "🧊", "I need an ice pack", ["ice pack", "cold pack", "bump"], "a blue ice pack on a knee"),
    ("hearing_aid", "Hearing Aid", "health", "🦻", "My hearing aid", ["hearing aid", "ear", "deaf"], "an ear with a small hearing aid"),
    ("glasses_health", "Glasses", "health", "👓", "My glasses", ["glasses", "eyes", "see"], "a pair of blue-rimmed eyeglasses"),
    ("tired_health", "Sleepy", "health", "😴", "I am sleepy", ["sleepy", "nap", "rest"], "a yawning child rubbing their eyes holding a pillow"),
    ("pain", "Pain", "health", "⚡", "It hurts", ["pain", "ouch", "hurts", "ache"], "a child wincing and holding a knee with red pain flashes"),

    # --- clothing / daily ----------------------------------------------------
    ("underwear", "Underwear", "daily", "🩲", "Underwear", ["underwear", "undies"], "a pair of blue kids' underwear"),
    ("dress", "Dress", "daily", "👗", "Dress", ["dress", "clothes"], "a pink dress with white polka dots"),
    ("coat", "Coat", "daily", "🧥", "Coat", ["coat", "winter", "warm"], "a puffy red winter coat"),
    ("gloves", "Gloves", "daily", "🧤", "Gloves", ["gloves", "mittens", "cold"], "a pair of green wool mittens"),
    ("boots", "Boots", "daily", "🥾", "Boots", ["boots", "rain boots"], "a pair of yellow rain boots"),
    ("sweater", "Sweater", "daily", "🧶", "Sweater", ["sweater", "warm", "jumper"], "a cozy striped knit sweater"),
    ("shorts", "Shorts", "daily", "🩳", "Shorts", ["shorts", "summer"], "a pair of blue shorts"),
    ("diaper", "Diaper", "daily", "👶", "Diaper change", ["diaper", "change", "nappy"], "a clean folded diaper"),
    ("toothbrush", "Toothbrush", "daily", "🪥", "Toothbrush", ["toothbrush", "toothpaste", "brush"], "a toothbrush with a stripe of blue toothpaste"),
    ("hairbrush", "Brush Hair", "daily", "💇", "Brush my hair", ["brush hair", "hairbrush", "comb"], "a hairbrush and a comb"),
    ("haircut", "Haircut", "daily", "✂️", "Haircut", ["haircut", "barber", "scissors"], "a child getting a haircut with scissors"),
    ("shower", "Shower", "daily", "🚿", "Shower", ["shower", "wash", "clean"], "a shower head spraying water"),
    ("wash_face", "Wash Face", "daily", "🧼", "Wash my face", ["wash face", "clean", "soap"], "a child washing their face at a sink"),
    ("get_dressed", "Get Dressed", "daily", "👕", "Get dressed", ["get dressed", "clothes", "put on"], "a child pulling a shirt over their head"),
    ("nap", "Nap", "daily", "🛏️", "Nap time", ["nap", "rest", "sleep"], "a child napping under a blanket on a couch"),
    ("bedtime", "Bedtime", "daily", "🌙", "Bedtime", ["bedtime", "sleep", "night"], "a child in pajamas in bed with a moon in the window"),
    ("wake_up", "Wake Up", "daily", "⏰", "Wake up", ["wake up", "alarm", "morning"], "a child stretching in bed with a ringing alarm clock"),
    ("lotion", "Lotion", "daily", "🧴", "Lotion", ["lotion", "cream", "skin"], "a bottle of lotion with a pump"),
    ("tissue", "Tissue", "daily", "🤧", "I need a tissue", ["tissue", "nose", "blow"], "a box of tissues with one pulled out"),

    # --- household -----------------------------------------------------------
    ("table", "Table", "places", "🪑", "Table", ["table", "furniture"], "a wooden dining table"),
    ("chair", "Chair", "places", "🪑", "Chair", ["chair", "seat", "sit"], "a blue wooden chair"),
    ("bed", "Bed", "places", "🛏️", "Bed", ["bed", "sleep"], "a cozy bed with a blue blanket and pillow"),
    ("couch", "Couch", "places", "🛋️", "Couch", ["couch", "sofa"], "a comfy green sofa"),
    ("tv", "TV", "play", "📺", "Watch TV", ["tv", "television", "show", "watch"], "a flat screen TV showing a simple drawing of a green hill and sun, no writing"),
    ("phone", "Phone", "play", "📱", "Phone", ["phone", "call", "mobile"], "a smartphone with a green call icon"),
    ("computer", "Computer", "play", "💻", "Computer", ["computer", "laptop"], "an open laptop computer with a plain blue screen, no writing"),
    ("headphones", "Headphones", "play", "🎧", "Headphones", ["headphones", "music", "quiet"], "a pair of big over-ear headphones"),
    ("remote", "Remote", "play", "📺", "Remote", ["remote", "tv", "control"], "a TV remote control"),
    ("charger", "Charger", "play", "🔌", "Charger", ["charger", "plug", "battery"], "a phone charger cable and plug"),
    ("door", "Door", "places", "🚪", "Door", ["door", "open", "close"], "a plain wooden front door slightly open, no writing"),
    ("window", "Window", "places", "🪟", "Window", ["window", "look out"], "a window with curtains and sunshine"),
    ("light", "Light", "places", "💡", "Light", ["light", "lamp", "on", "off"], "a glowing light bulb"),
    ("fridge", "Fridge", "places", "🧊", "Fridge", ["fridge", "refrigerator", "cold"], "a refrigerator with the door open showing food"),
    ("cup", "Cup", "food", "🥤", "Cup", ["cup", "drink", "glass"], "a blue cup with a handle"),
    ("plate", "Plate", "food", "🍽️", "Plate", ["plate", "dish"], "a white plate with a blue rim"),
    ("fork", "Fork", "food", "🍴", "Fork", ["fork", "eat"], "a silver fork"),
    ("spoon", "Spoon", "food", "🥄", "Spoon", ["spoon", "eat"], "a silver spoon"),
    ("bowl", "Bowl", "food", "🥣", "Bowl", ["bowl", "cereal", "soup"], "a red bowl"),
    ("straw", "Straw", "drinks", "🥤", "Straw", ["straw", "drink", "sip"], "a striped drinking straw in a cup"),
    ("snack", "Snack", "food", "🍪", "I want a snack", ["snack", "hungry", "food"], "a snack plate with crackers, cheese and grapes"),
    ("breakfast", "Breakfast", "food", "🥞", "Breakfast", ["breakfast", "morning", "meal"], "a breakfast of eggs, toast and orange juice"),
    ("lunch", "Lunch", "food", "🥪", "Lunch", ["lunch", "meal", "noon"], "a lunch tray with a sandwich, apple and milk"),
    ("dinner", "Dinner", "food", "🍽️", "Dinner", ["dinner", "supper", "meal"], "a dinner plate with chicken, vegetables and rice"),
    ("peanut_butter", "Peanut Butter", "food", "🥜", "Peanut butter", ["peanut butter", "sandwich"], "a jar of peanut butter with a knife"),
    ("mac_cheese", "Mac & Cheese", "food", "🧀", "Mac and cheese", ["mac and cheese", "macaroni", "pasta"], "a bowl of macaroni and cheese"),
    ("nuggets", "Nuggets", "food", "🍗", "Chicken nuggets", ["chicken nuggets", "nuggets"], "chicken nuggets with a small cup of sauce"),
    ("grilled_cheese", "Grilled Cheese", "food", "🥪", "Grilled cheese", ["grilled cheese", "sandwich"], "a grilled cheese sandwich cut in half"),
    ("toast", "Toast", "food", "🍞", "Toast", ["toast", "bread", "butter"], "two slices of toast with butter"),
    ("fruit", "Fruit", "food", "🍇", "Fruit", ["fruit", "healthy"], "a bowl of mixed fruit"),
    ("vegetables", "Vegetables", "food", "🥦", "Vegetables", ["vegetables", "veggies", "healthy"], "a plate of mixed vegetables"),
    ("gum", "Gum", "food", "🍬", "Gum", ["gum", "chew"], "a few pieces of pink bubble gum and a green gum wrapper, no writing"),

    # --- school --------------------------------------------------------------
    ("pencil", "Pencil", "places", "✏️", "Pencil", ["pencil", "write", "school"], "a yellow pencil"),
    ("paper", "Paper", "places", "📄", "Paper", ["paper", "sheet", "write"], "a blank sheet of white paper with faint blue lines, no writing"),
    ("book", "Book", "places", "📖", "Book", ["book", "read", "story"], "an open picture book showing only a drawing of a sun and a tree, no writing"),
    ("scissors", "Scissors", "places", "✂️", "Scissors", ["scissors", "cut", "craft"], "a pair of kid safety scissors"),
    ("desk", "Desk", "places", "🪑", "Desk", ["desk", "school", "sit"], "a school desk with a chair"),
    ("lunchbox", "Lunchbox", "places", "🧺", "Lunchbox", ["lunchbox", "lunch", "school"], "a red lunchbox"),
    ("homework", "Homework", "places", "📝", "Homework", ["homework", "school", "work"], "a worksheet with a pencil and a check mark"),
    ("circle_time", "Circle Time", "places", "🧑‍🤝‍🧑", "Circle time", ["circle time", "group", "class"], "children sitting in a circle on a rug with a teacher"),
    ("line_up", "Line Up", "places", "🚶", "Line up", ["line up", "line", "wait"], "children standing in a neat line"),
    ("computer_lab", "Computer", "places", "🖥️", "Computer time", ["computer", "typing", "screen"], "a desktop computer with a plain blue screen on a desk, no writing"),
    ("art_class", "Art", "places", "🎨", "Art class", ["art", "paint", "draw"], "a paint palette with brushes"),
    ("music_class", "Music", "places", "🎵", "Music class", ["music", "song", "instrument"], "musical notes with a small guitar and tambourine"),
    ("therapy", "Therapy", "places", "🗣️", "Speech therapy", ["therapy", "speech", "ot", "pt"], "a therapist and a child at a small table with picture cards"),
    ("work", "Work", "places", "💼", "Work", ["work", "job", "office"], "a briefcase and a laptop"),
    ("church", "Church", "places", "⛪", "Church", ["church", "worship"], "a small white church with a steeple"),
    ("grandmas_house", "Grandma's House", "places", "🏡", "Grandma's house", ["grandma", "house", "visit"], "a cozy cottage with flowers and a grandma waving at the door"),
    ("doctor_office", "Doctor's Office", "places", "🏥", "Doctor's office", ["doctor", "office", "clinic"], "a doctor's office room with an exam table"),
    ("mall", "Mall", "places", "🛍️", "Mall", ["mall", "shopping", "store"], "a shopping mall entrance with bags"),
    ("car_ride", "Car Ride", "places", "🚗", "Car ride", ["car", "ride", "drive"], "a child buckled in a car seat looking out the window"),
    ("bus_stop", "Bus Stop", "places", "🚏", "Bus stop", ["bus stop", "wait", "bus"], "a bus stop sign with a bench"),
    ("outside_play", "Play Outside", "play", "🌳", "Play outside", ["outside", "play", "yard"], "a child running on grass with a kite"),
    ("birthday", "Birthday", "social", "🎂", "Happy birthday", ["birthday", "party", "cake"], "a birthday cake with candles and balloons"),
    ("party", "Party", "social", "🎉", "Party", ["party", "celebrate", "fun"], "confetti, streamers and a party hat"),
    ("christmas", "Christmas", "social", "🎄", "Merry Christmas", ["christmas", "holiday", "tree"], "a decorated Christmas tree with presents"),
    ("halloween", "Halloween", "social", "🎃", "Halloween", ["halloween", "pumpkin", "costume"], "a jack-o-lantern pumpkin with a small ghost"),
    ("shopping", "Shopping", "places", "🛒", "Go shopping", ["shopping", "store", "buy"], "a shopping cart full of groceries"),
    ("cooking", "Cooking", "actions", "🍳", "Cooking", ["cook", "cooking", "kitchen"], "a child in an apron stirring a pot"),
    ("bath_time", "Bath Time", "daily", "🛁", "Bath time", ["bath", "bubbles", "wash"], "a child in a bathtub full of bubbles with a rubber duck"),

    # --- feelings extras -----------------------------------------------------
    ("angry", "Angry", "feelings", "😡", "I feel angry", ["angry", "mad", "furious"], "a child with an angry red face and clenched fists"),
    ("lonely", "Lonely", "feelings", "😔", "I feel lonely", ["lonely", "alone", "sad"], "a child sitting alone on a bench looking down"),
    ("embarrassed", "Embarrassed", "feelings", "😳", "I feel embarrassed", ["embarrassed", "shy", "blush"], "a child with red cheeks covering their face"),
    ("jealous", "Jealous", "feelings", "😒", "I feel jealous", ["jealous", "envy"], "a child frowning while looking at another child's toy"),
    ("overwhelmed", "Overwhelmed", "feelings", "😵", "I feel overwhelmed", ["overwhelmed", "too much", "stressed"], "a child covering their ears with swirls and noise marks around"),
    ("brave", "Brave", "feelings", "🦸", "I feel brave", ["brave", "strong", "courage"], "a child in a plain red cape standing proud with fists on hips, no logo on the shirt"),
    ("grumpy", "Grumpy", "feelings", "😠", "I feel grumpy", ["grumpy", "cranky", "moody"], "a child with crossed arms and a pouty frown"),
    ("okay", "Okay", "feelings", "🙂", "I feel okay", ["okay", "fine", "alright"], "a child with a calm small smile giving a thumbs up"),
    ("love", "Love", "feelings", "❤️", "Love", ["love", "heart"], "a big red heart with small hearts around it"),
    ("safe", "Safe", "feelings", "🛡️", "I feel safe", ["safe", "protected", "secure"], "a child hugged by a parent inside a soft glowing blue shield outline, no box behind them"),

    # --- actions extras ------------------------------------------------------
    ("talk", "Talk", "actions", "💬", "Talk", ["talk", "speak", "chat"], "two children talking with speech bubbles"),
    ("share", "Share", "actions", "🤝", "Share", ["share", "sharing", "give"], "a child handing half of a cookie to a friend"),
    ("wait_turn", "Wait", "actions", "⏳", "Wait", ["wait", "patience", "turn"], "a child sitting with hands folded next to an hourglass"),
    ("kick", "Kick", "actions", "⚽", "Kick", ["kick", "soccer", "ball"], "a child kicking a soccer ball"),
    ("ride", "Ride", "actions", "🚲", "Ride", ["ride", "bike", "scooter"], "a child riding a bike wearing a helmet"),
    ("build", "Build", "actions", "🧱", "Build", ["build", "blocks", "stack"], "a child stacking a tower of colorful blocks"),
    ("paint", "Paint", "actions", "🖌️", "Paint", ["paint", "art", "brush"], "a child painting on an easel"),
    ("color", "Color", "actions", "🖍️", "Color", ["color", "crayon", "coloring"], "a child coloring a picture with crayons"),
    ("pretend", "Pretend", "actions", "🎭", "Pretend", ["pretend", "imagine", "play"], "a child wearing a paper crown and cape pretending to be royalty"),
    ("laugh", "Laugh", "actions", "😂", "Laugh", ["laugh", "funny", "giggle"], "a child laughing hard with ha-ha marks, no text"),
    ("cry", "Cry", "actions", "😭", "Cry", ["cry", "tears", "sad"], "a child crying with big tears"),
    ("smell", "Smell", "actions", "👃", "Smell", ["smell", "sniff", "nose"], "a child smelling a flower"),
    ("touch", "Touch", "actions", "🤚", "Touch", ["touch", "feel", "hand"], "a hand gently touching a fluffy cat"),
    ("go_potty", "Go Potty", "actions", "🚽", "I need to go potty", ["potty", "bathroom", "toilet", "pee"], "a child walking toward a toilet holding their tummy"),
    ("wash", "Wash", "actions", "🧼", "Wash", ["wash", "soap", "clean"], "hands under running water with soap bubbles"),
    ("stop_action", "Stop", "actions", "✋", "Stop", ["stop", "halt", "no"], "a child holding up an open palm in a stop gesture"),
    ("help_me", "Help Me", "actions", "🆘", "Help me please", ["help", "help me", "assist"], "a child with a raised hand and a worried face next to a helping adult hand"),
    ("leave_alone", "Leave Me Alone", "social", "🚫", "Please leave me alone", ["leave me alone", "space", "alone"], "a child sitting alone with a hand up asking for space"),
    ("come_here", "Come Here", "social", "👋", "Come here please", ["come here", "come"], "a child waving someone over with a big smile"),
    ("lets_go", "Let's Go", "social", "🚀", "Let's go", ["let's go", "go", "leave"], "a child pointing forward excitedly with a small backpack"),
    ("im_done", "I'm Done", "social", "✅", "I am done", ["done", "finished", "all done"], "a child pushing away an empty plate with a satisfied smile"),
    ("say_again", "Say It Again", "social", "🔁", "Please say that again", ["again", "repeat", "say again"], "an ear with a circular repeat arrow"),
    ("dont_understand", "Don't Understand", "social", "❓", "I do not understand", ["understand", "confused", "what"], "a child with a puzzled face and a big question mark"),
    ("good_morning", "Good Morning", "social", "🌅", "Good morning", ["good morning", "morning", "hello"], "a child waving in front of a sunrise"),
    ("good_night", "Good Night", "social", "🌙", "Good night", ["good night", "bedtime", "bye"], "a child in pajamas waving under a moon and stars"),
    ("how_are_you", "How Are You", "social", "🙂", "How are you?", ["how are you", "greeting"], "two children greeting each other with a wave and a smile"),
    ("im_fine", "I'm Fine", "social", "👌", "I am fine", ["fine", "okay", "good"], "a child giving an OK hand sign with a smile"),
    ("can_i", "Can I?", "social", "🙏", "Can I please?", ["can i", "may i", "ask"], "a child with hands together asking politely"),
    ("i_need", "I Need", "social", "❗", "I need", ["need", "i need"], "a child holding up a hand with an exclamation mark"),
    ("i_dont_want", "I Don't Want", "social", "🙅", "I do not want that", ["don't want", "no", "refuse"], "a child crossing arms in an X with a firm face"),
    ("yes_please", "Yes Please", "social", "👍", "Yes please", ["yes", "please", "ok"], "a child nodding with a thumbs up and a happy face"),
    ("no_thanks", "No Thanks", "social", "🙅", "No thank you", ["no", "no thanks", "decline"], "a child politely holding up a hand with a small head shake"),

    # --- animals extras ------------------------------------------------------
    ("chicken_animal", "Chicken", "animals", "🐔", "Chicken", ["chicken", "hen", "farm"], "a white hen"),
    ("goat", "Goat", "animals", "🐐", "Goat", ["goat", "farm"], "a friendly goat"),
    ("snake", "Snake", "animals", "🐍", "Snake", ["snake", "reptile"], "a green coiled snake"),
    ("spider", "Spider", "animals", "🕷️", "Spider", ["spider", "bug"], "a small friendly spider on a web"),
    ("bee", "Bee", "animals", "🐝", "Bee", ["bee", "bug", "honey"], "a cute honeybee"),
    ("shark", "Shark", "animals", "🦈", "Shark", ["shark", "ocean"], "a blue shark"),
    ("whale", "Whale", "animals", "🐳", "Whale", ["whale", "ocean"], "a blue whale spouting water"),
    ("giraffe", "Giraffe", "animals", "🦒", "Giraffe", ["giraffe", "zoo"], "a tall giraffe"),
    ("zebra", "Zebra", "animals", "🦓", "Zebra", ["zebra", "zoo"], "a striped zebra"),
    ("owl", "Owl", "animals", "🦉", "Owl", ["owl", "bird", "night"], "a brown owl on a branch"),
    ("deer", "Deer", "animals", "🦌", "Deer", ["deer", "forest"], "a deer with small antlers"),
    ("mouse", "Mouse", "animals", "🐭", "Mouse", ["mouse", "small"], "a small gray mouse"),
    ("bunny_pet", "Hamster", "animals", "🐹", "Hamster", ["hamster", "pet"], "a chubby hamster"),
    ("puppy", "Puppy", "animals", "🐶", "Puppy", ["puppy", "dog", "pet"], "a playful golden puppy"),
    ("kitten", "Kitten", "animals", "🐱", "Kitten", ["kitten", "cat", "pet"], "a small fluffy kitten"),

    # --- vehicles extras -----------------------------------------------------
    ("motorcycle", "Motorcycle", "vehicles", "🏍️", "Motorcycle", ["motorcycle", "bike"], "a red motorcycle"),
    ("scooter", "Scooter", "vehicles", "🛴", "Scooter", ["scooter", "ride"], "a plain red kick scooter, no lettering"),
    ("tractor", "Tractor", "vehicles", "🚜", "Tractor", ["tractor", "farm"], "a green farm tractor"),
    ("rocket", "Rocket", "vehicles", "🚀", "Rocket", ["rocket", "space"], "a rocket ship blasting off"),
    ("subway", "Subway", "vehicles", "🚇", "Subway", ["subway", "metro", "train"], "a subway train in a tunnel"),
    ("taxi", "Taxi", "vehicles", "🚕", "Taxi", ["taxi", "cab", "ride"], "a yellow taxi cab"),
    ("garbage_truck", "Garbage Truck", "vehicles", "🚛", "Garbage truck", ["garbage truck", "trash"], "a green garbage truck"),

    # --- nature extras -------------------------------------------------------
    ("hot_weather", "Sunny", "nature", "☀️", "It is sunny", ["sunny", "hot", "sunshine"], "a bright smiling sun with rays"),
    ("foggy", "Foggy", "nature", "🌫️", "It is foggy", ["fog", "foggy", "mist"], "trees and a road fading into thick gray fog, no writing"),
    ("grass", "Grass", "nature", "🌿", "Grass", ["grass", "lawn", "green"], "a patch of green grass"),
    ("ocean", "Ocean", "nature", "🌊", "Ocean", ["ocean", "sea", "waves"], "blue ocean waves"),
    ("mountain", "Mountain", "nature", "⛰️", "Mountain", ["mountain", "hike"], "a snow-capped mountain"),
    ("garden", "Garden", "nature", "🌻", "Garden", ["garden", "plants", "flowers"], "a small garden with sunflowers and a watering can"),
    ("leaf", "Leaf", "nature", "🍂", "Leaf", ["leaf", "fall", "autumn"], "an orange autumn leaf"),
    ("stars", "Stars", "nature", "⭐", "Stars", ["stars", "night", "sky"], "a night sky with many bright yellow stars, no ground"),

    # --- concepts extras -----------------------------------------------------
    ("num_0", "0", "concepts", "0️⃣", "Zero", ["zero", "0", "none"], "a big bold number 0 in bright blue"),
    ("circle", "Circle", "colors", "⚪", "Circle", ["circle", "round", "shape"], "a bold blue circle shape"),
    ("square", "Square", "colors", "🟦", "Square", ["square", "shape"], "a plain bold green square shape"),
    ("triangle", "Triangle", "colors", "🔺", "Triangle", ["triangle", "shape"], "a bold orange triangle shape"),
    ("black", "Black", "colors", "⚫", "Black", ["black", "color"], "a big bold plain black paint splash"),
    ("white", "White", "colors", "⚪", "White", ["white", "color"], "a big white paint splash with a thin gray outline"),
    ("brown", "Brown", "colors", "🟤", "Brown", ["brown", "color"], "a big bold brown paint splash"),
    ("gray", "Gray", "colors", "🩶", "Gray", ["gray", "grey", "color"], "a big bold gray paint splash"),
    ("money", "Money", "concepts", "💵", "Money", ["money", "dollars", "pay", "check"], "a few dollar bills and coins"),
    ("time_clock", "Time", "concepts", "🕒", "What time is it?", ["time", "clock", "when"], "a round wall clock"),
    ("calendar", "Calendar", "concepts", "📅", "Calendar", ["calendar", "date", "day"], "a monthly wall calendar with an empty grid of days, no writing"),
    ("weekend", "Weekend", "concepts", "🎉", "Weekend", ["weekend", "saturday", "sunday"], "a calendar with Saturday and Sunday highlighted, no text"),
    ("letters_abc", "Letters", "concepts", "🔤", "Letters", ["letters", "abc", "alphabet"], "three big colorful block letters A, B and C in a row"),
    ("napkin", "Napkin", "food", "🧻", "I need a napkin", ["napkin", "serviette", "wipe", "mouth"], "a folded white paper napkin next to a plate"),
    ("finished", "Finished", "core", "🏁", "I am finished", ["finished", "finish", "done", "complete"], "a child closing a book with a satisfied smile and a green check mark"),
]
