# Expansion set 5 (2026-09-13): animals, health & body, vehicles, nature, concepts, colors & shapes.

EXTRA5 = [
    # --- animals ----------------------------------------------------------------
    ("hamster", "Hamster", "animals", "🐹", "Hamster", ["hamster", "pet", "small"], "a chubby orange hamster holding a seed"),
    ("guinea_pig", "Guinea Pig", "animals", "🐹", "Guinea pig", ["guinea pig", "pet"], "a brown and white guinea pig"),
    ("gerbil", "Gerbil", "animals", "🐭", "Gerbil", ["gerbil", "pet", "small"], "a small tan gerbil with a long tail"),
    ("parrot", "Parrot", "animals", "🦜", "Parrot", ["parrot", "bird", "colorful"], "a bright red, blue and yellow parrot on a perch"),
    ("goldfish_pet", "Goldfish", "animals", "🐠", "Goldfish", ["goldfish", "fish", "bowl"], "an orange goldfish in a round bowl"),
    ("lizard", "Lizard", "animals", "🦎", "Lizard", ["lizard", "reptile", "gecko"], "a green gecko lizard"),
    ("hermit_crab", "Hermit Crab", "animals", "🦀", "Hermit crab", ["hermit crab", "shell", "pet"], "a hermit crab peeking out of a spiral shell"),
    ("chick", "Chick", "animals", "🐥", "Chick", ["chick", "baby chicken", "yellow"], "a fluffy yellow baby chick"),
    ("rooster", "Rooster", "animals", "🐓", "Rooster", ["rooster", "chicken", "farm"], "a colorful rooster crowing"),
    ("turkey_animal", "Turkey", "animals", "🦃", "Turkey", ["turkey", "bird", "farm"], "a turkey with fanned tail feathers"),
    ("donkey", "Donkey", "animals", "🫏", "Donkey", ["donkey", "farm"], "a gray donkey with long ears"),
    ("pony", "Pony", "animals", "🐴", "Pony", ["pony", "horse", "small"], "a small brown pony with a flowing mane"),
    ("lamb", "Lamb", "animals", "🐑", "Lamb", ["lamb", "baby sheep"], "a fluffy white baby lamb"),
    ("piglet", "Piglet", "animals", "🐷", "Piglet", ["piglet", "baby pig"], "a small pink piglet"),
    ("calf", "Calf", "animals", "🐄", "Calf", ["calf", "baby cow"], "a small brown and white baby cow"),
    ("goose", "Goose", "animals", "🪿", "Goose", ["goose", "bird", "honk"], "a white goose with an orange beak"),
    ("swan", "Swan", "animals", "🦢", "Swan", ["swan", "bird", "lake"], "a white swan on water"),
    ("flamingo", "Flamingo", "animals", "🦩", "Flamingo", ["flamingo", "pink", "bird"], "a pink flamingo standing on one leg"),
    ("peacock", "Peacock", "animals", "🦚", "Peacock", ["peacock", "feathers", "bird"], "a peacock with a fanned colorful tail"),
    ("eagle", "Eagle", "animals", "🦅", "Eagle", ["eagle", "bird", "fly"], "a bald eagle with wings spread"),
    ("hawk", "Hawk", "animals", "🦅", "Hawk", ["hawk", "bird"], "a brown hawk perched on a branch"),
    ("crow", "Crow", "animals", "🐦‍⬛", "Crow", ["crow", "black bird"], "a black crow"),
    ("robin", "Robin", "animals", "🐦", "Robin", ["robin", "bird", "red"], "a small bird with a red breast"),
    ("hummingbird", "Hummingbird", "animals", "🐦", "Hummingbird", ["hummingbird", "tiny bird", "flower"], "a tiny hummingbird hovering at a flower"),
    ("woodpecker", "Woodpecker", "animals", "🐦", "Woodpecker", ["woodpecker", "bird", "tree"], "a woodpecker pecking a tree trunk"),
    ("pigeon", "Pigeon", "animals", "🕊️", "Pigeon", ["pigeon", "bird", "city"], "a gray pigeon"),
    ("seagull", "Seagull", "animals", "🐦", "Seagull", ["seagull", "beach", "bird"], "a white seagull flying over the beach"),
    ("pelican", "Pelican", "animals", "🐦", "Pelican", ["pelican", "beak", "bird"], "a pelican with a big beak pouch"),
    ("toucan", "Toucan", "animals", "🐦", "Toucan", ["toucan", "colorful beak", "bird"], "a toucan with a big colorful beak"),
    ("ostrich", "Ostrich", "animals", "🐦", "Ostrich", ["ostrich", "big bird", "run"], "a tall ostrich with a long neck"),
    ("bat", "Bat", "animals", "🦇", "Bat", ["bat", "night", "halloween"], "a purple bat with wings spread"),
    ("squirrel", "Squirrel", "animals", "🐿️", "Squirrel", ["squirrel", "nut", "tree"], "a gray squirrel holding an acorn"),
    ("chipmunk", "Chipmunk", "animals", "🐿️", "Chipmunk", ["chipmunk", "stripes", "small"], "a striped chipmunk with puffy cheeks"),
    ("raccoon", "Raccoon", "animals", "🦝", "Raccoon", ["raccoon", "mask", "night"], "a raccoon with a black mask"),
    ("skunk", "Skunk", "animals", "🦨", "Skunk", ["skunk", "stripe", "smelly"], "a black skunk with a white stripe"),
    ("fox", "Fox", "animals", "🦊", "Fox", ["fox", "orange", "forest"], "an orange fox with a bushy tail"),
    ("wolf", "Wolf", "animals", "🐺", "Wolf", ["wolf", "howl", "forest"], "a gray wolf howling"),
    ("moose", "Moose", "animals", "🫎", "Moose", ["moose", "antlers", "forest"], "a brown moose with big antlers"),
    ("beaver", "Beaver", "animals", "🦫", "Beaver", ["beaver", "dam", "teeth"], "a brown beaver with a flat tail holding a log"),
    ("otter", "Otter", "animals", "🦦", "Otter", ["otter", "water", "swim"], "an otter floating on its back"),
    ("hedgehog", "Hedgehog", "animals", "🦔", "Hedgehog", ["hedgehog", "spiky", "small"], "a small hedgehog with spikes"),
    ("porcupine", "Porcupine", "animals", "🦔", "Porcupine", ["porcupine", "quills"], "a porcupine with long quills"),
    ("opossum", "Opossum", "animals", "🐀", "Opossum", ["opossum", "possum", "night"], "a gray opossum hanging by its tail"),
    ("rat", "Rat", "animals", "🐀", "Rat", ["rat", "rodent"], "a gray rat with a long tail"),
    ("mole", "Mole", "animals", "🐀", "Mole", ["mole", "dig", "underground"], "a mole popping out of a dirt hole"),
    ("groundhog", "Groundhog", "animals", "🦫", "Groundhog", ["groundhog", "shadow", "hole"], "a groundhog peeking out of a hole"),
    ("kangaroo", "Kangaroo", "animals", "🦘", "Kangaroo", ["kangaroo", "hop", "pouch"], "a kangaroo with a joey in its pouch"),
    ("koala", "Koala", "animals", "🐨", "Koala", ["koala", "tree", "sleepy"], "a gray koala hugging a tree branch"),
    ("panda", "Panda", "animals", "🐼", "Panda", ["panda", "bamboo", "black and white"], "a panda eating bamboo"),
    ("polar_bear", "Polar Bear", "animals", "🐻‍❄️", "Polar bear", ["polar bear", "snow", "white"], "a white polar bear on ice"),
    ("sloth", "Sloth", "animals", "🦥", "Sloth", ["sloth", "slow", "tree"], "a sloth hanging from a branch smiling"),
    ("gorilla", "Gorilla", "animals", "🦍", "Gorilla", ["gorilla", "ape", "strong"], "a big black gorilla sitting"),
    ("chimpanzee", "Chimpanzee", "animals", "🐵", "Chimpanzee", ["chimpanzee", "chimp", "monkey"], "a chimpanzee sitting and smiling"),
    ("orangutan", "Orangutan", "animals", "🦧", "Orangutan", ["orangutan", "orange", "ape"], "an orange orangutan hanging from a branch"),
    ("lemur", "Lemur", "animals", "🐒", "Lemur", ["lemur", "striped tail"], "a lemur with a black and white striped tail"),
    ("hippo", "Hippo", "animals", "🦛", "Hippo", ["hippo", "hippopotamus", "water"], "a gray hippo in water with its mouth open"),
    ("rhino", "Rhino", "animals", "🦏", "Rhino", ["rhino", "rhinoceros", "horn"], "a gray rhino with a horn"),
    ("camel", "Camel", "animals", "🐪", "Camel", ["camel", "desert", "hump"], "a camel with two humps in the desert"),
    ("cheetah", "Cheetah", "animals", "🐆", "Cheetah", ["cheetah", "fast", "spots"], "a spotted cheetah running"),
    ("leopard", "Leopard", "animals", "🐆", "Leopard", ["leopard", "spots"], "a spotted leopard lying on a branch"),
    ("jaguar", "Jaguar", "animals", "🐆", "Jaguar", ["jaguar", "spots", "jungle"], "a jaguar in the jungle"),
    ("panther", "Panther", "animals", "🐈‍⬛", "Panther", ["panther", "black cat", "jungle"], "a sleek black panther"),
    ("hyena", "Hyena", "animals", "🐕", "Hyena", ["hyena", "laugh"], "a spotted hyena laughing"),
    ("meerkat", "Meerkat", "animals", "🐿️", "Meerkat", ["meerkat", "standing", "desert"], "a meerkat standing up on lookout"),
    ("bison", "Bison", "animals", "🦬", "Bison", ["bison", "buffalo"], "a shaggy brown bison"),
    ("ox", "Ox", "animals", "🐂", "Ox", ["ox", "bull", "farm"], "a strong brown ox with horns"),
    ("bull", "Bull", "animals", "🐂", "Bull", ["bull", "horns"], "a black bull with big horns"),
    ("llama", "Llama", "animals", "🦙", "Llama", ["llama", "alpaca", "fluffy"], "a fluffy white llama"),
    ("alligator", "Alligator", "animals", "🐊", "Alligator", ["alligator", "gator", "swamp"], "a green alligator with an open mouth"),
    ("crocodile", "Crocodile", "animals", "🐊", "Crocodile", ["crocodile", "croc"], "a long green crocodile"),
    ("iguana", "Iguana", "animals", "🦎", "Iguana", ["iguana", "lizard", "green"], "a green iguana with spikes on its back"),
    ("chameleon", "Chameleon", "animals", "🦎", "Chameleon", ["chameleon", "color change", "lizard"], "a colorful chameleon on a branch with a curly tail"),
    ("tortoise", "Tortoise", "animals", "🐢", "Tortoise", ["tortoise", "slow", "shell"], "a big brown tortoise"),
    ("toad", "Toad", "animals", "🐸", "Toad", ["toad", "bumpy", "frog"], "a bumpy brown toad"),
    ("salamander", "Salamander", "animals", "🦎", "Salamander", ["salamander", "newt"], "an orange spotted salamander"),
    ("tadpole", "Tadpole", "animals", "🐸", "Tadpole", ["tadpole", "baby frog", "pond"], "small tadpoles swimming in a pond"),
    ("octopus", "Octopus", "animals", "🐙", "Octopus", ["octopus", "eight legs", "ocean"], "a purple octopus with eight arms"),
    ("squid", "Squid", "animals", "🦑", "Squid", ["squid", "ocean"], "a pink squid"),
    ("jellyfish", "Jellyfish", "animals", "🪼", "Jellyfish", ["jellyfish", "ocean", "sting"], "a glowing pink jellyfish"),
    ("starfish", "Starfish", "animals", "⭐", "Starfish", ["starfish", "sea star", "beach"], "an orange starfish on sand"),
    ("seahorse", "Seahorse", "animals", "🐠", "Seahorse", ["seahorse", "ocean"], "a yellow seahorse"),
    ("crab", "Crab", "animals", "🦀", "Crab", ["crab", "beach", "claws"], "a red crab with claws up"),
    ("lobster", "Lobster", "animals", "🦞", "Lobster", ["lobster", "ocean", "claws"], "a red lobster"),
    ("clam", "Clam", "animals", "🐚", "Clam", ["clam", "shell", "beach"], "an open clam shell with a pearl"),
    ("seal", "Seal", "animals", "🦭", "Seal", ["seal", "ocean", "clap"], "a gray seal clapping its flippers"),
    ("walrus", "Walrus", "animals", "🦭", "Walrus", ["walrus", "tusks", "ice"], "a walrus with long tusks on ice"),
    ("sea_turtle", "Sea Turtle", "animals", "🐢", "Sea turtle", ["sea turtle", "ocean", "swim"], "a green sea turtle swimming"),
    ("stingray", "Stingray", "animals", "🐟", "Stingray", ["stingray", "ocean", "flat"], "a flat gray stingray gliding"),
    ("clownfish", "Clownfish", "animals", "🐠", "Clownfish", ["clownfish", "orange fish", "reef"], "an orange and white striped clownfish"),
    ("eel", "Eel", "animals", "🐍", "Eel", ["eel", "long fish"], "a long green eel"),
    ("pufferfish", "Pufferfish", "animals", "🐡", "Pufferfish", ["pufferfish", "spiky", "puff"], "a round spiky puffed-up pufferfish"),
    ("swordfish", "Swordfish", "animals", "🐟", "Swordfish", ["swordfish", "long nose"], "a blue swordfish with a long pointed bill"),
    ("orca", "Orca", "animals", "🐋", "Orca", ["orca", "killer whale", "black and white"], "a black and white orca jumping"),
    ("narwhal", "Narwhal", "animals", "🦄", "Narwhal", ["narwhal", "horn", "whale"], "a narwhal with a long spiral tusk"),
    ("ant", "Ant", "animals", "🐜", "Ant", ["ant", "bug", "small"], "a black ant carrying a crumb"),
    ("ladybug", "Ladybug", "animals", "🐞", "Ladybug", ["ladybug", "bug", "red"], "a red ladybug with black spots on a leaf"),
    ("caterpillar", "Caterpillar", "animals", "🐛", "Caterpillar", ["caterpillar", "bug", "green"], "a green striped caterpillar on a leaf"),
    ("grasshopper", "Grasshopper", "animals", "🦗", "Grasshopper", ["grasshopper", "bug", "jump"], "a green grasshopper"),
    ("cricket", "Cricket", "animals", "🦗", "Cricket", ["cricket", "bug", "chirp"], "a brown cricket with music notes"),
    ("dragonfly", "Dragonfly", "animals", "🪰", "Dragonfly", ["dragonfly", "bug", "wings"], "a blue dragonfly with clear wings"),
    ("moth", "Moth", "animals", "🦋", "Moth", ["moth", "bug", "night"], "a gray moth near a light"),
    ("fly_animals", "Fly", "animals", "🪰", "Fly", ["fly", "bug", "buzz"], "a black housefly"),
    ("mosquito", "Mosquito", "animals", "🦟", "Mosquito", ["mosquito", "bug", "bite"], "a mosquito with long legs"),
    ("wasp", "Wasp", "animals", "🐝", "Wasp", ["wasp", "sting", "bug"], "a yellow and black wasp"),
    ("beetle", "Beetle", "animals", "🪲", "Beetle", ["beetle", "bug", "shell"], "a shiny green beetle"),
    ("worm", "Worm", "animals", "🪱", "Worm", ["worm", "dirt", "wiggle"], "a pink earthworm in soil"),
    ("snail", "Snail", "animals", "🐌", "Snail", ["snail", "slow", "shell"], "a snail with a spiral shell"),
    ("slug", "Slug", "animals", "🐌", "Slug", ["slug", "slimy"], "a gray slug on a leaf"),
    ("scorpion", "Scorpion", "animals", "🦂", "Scorpion", ["scorpion", "sting", "desert"], "a brown scorpion with a curled tail"),
    ("cockroach", "Cockroach", "animals", "🪳", "Cockroach", ["cockroach", "bug", "yuck"], "a brown cockroach"),
    ("firefly", "Firefly", "animals", "✨", "Firefly", ["firefly", "lightning bug", "glow"], "a glowing firefly at night"),
    ("t_rex", "T-Rex", "animals", "🦖", "T-Rex", ["t-rex", "dinosaur", "roar"], "a green T-rex roaring"),
    ("triceratops", "Triceratops", "animals", "🦕", "Triceratops", ["triceratops", "dinosaur", "horns"], "a triceratops with three horns"),
    ("stegosaurus", "Stegosaurus", "animals", "🦕", "Stegosaurus", ["stegosaurus", "dinosaur", "plates"], "a stegosaurus with back plates"),
    ("brachiosaurus", "Long Neck Dinosaur", "animals", "🦕", "Long neck dinosaur", ["brachiosaurus", "long neck", "dinosaur"], "a tall long-necked dinosaur eating leaves"),
    ("pterodactyl", "Pterodactyl", "animals", "🦅", "Pterodactyl", ["pterodactyl", "flying dinosaur"], "a flying pterodactyl with wide wings"),
    ("velociraptor", "Raptor", "animals", "🦖", "Raptor", ["raptor", "velociraptor", "dinosaur"], "a small fast raptor dinosaur running"),
    ("dragon", "Dragon", "animals", "🐉", "Dragon", ["dragon", "fire", "fantasy"], "a friendly green dragon breathing a small flame"),
    ("unicorn", "Unicorn", "animals", "🦄", "Unicorn", ["unicorn", "horn", "rainbow"], "a white unicorn with a rainbow mane"),
    ("pegasus", "Flying Horse", "animals", "🐴", "Flying horse", ["pegasus", "wings", "horse"], "a white horse with wings flying"),
    ("pet", "Pet", "animals", "🐾", "Pet", ["pet", "animal", "my pet"], "a child hugging a dog and a cat"),
    ("wild_animal", "Wild Animal", "animals", "🦁", "Wild animal", ["wild", "zoo", "jungle"], "a lion, an elephant and a giraffe together"),
    ("farm_animal", "Farm Animal", "animals", "🐄", "Farm animal", ["farm", "barn", "animals"], "a cow, a pig and a chicken in front of a barn"),
    ("sea_animal", "Sea Animal", "animals", "🐬", "Sea animal", ["sea", "ocean", "animals"], "a dolphin, a fish and an octopus under water"),
    ("bug", "Bug", "animals", "🐛", "Bug", ["bug", "insect", "creepy crawly"], "a ladybug, an ant and a caterpillar on a leaf"),
    ("baby_animal", "Baby Animal", "animals", "🐣", "Baby animal", ["baby animal", "cute", "small"], "a puppy, a kitten and a chick together"),
    ("nest", "Nest", "animals", "🪺", "Nest", ["nest", "eggs", "bird"], "a bird nest with three blue eggs"),
    ("egg_animal", "Egg", "animals", "🥚", "Egg", ["egg", "hatch", "bird"], "a white egg cracking with a chick peeking out"),
    ("paw", "Paw", "animals", "🐾", "Paw", ["paw", "paw print", "animal"], "a dog's paw and a paw print"),
    ("tail", "Tail", "animals", "🐕", "Tail", ["tail", "wag", "dog"], "a dog wagging its tail with motion lines"),
    ("feather", "Feather", "animals", "🪶", "Feather", ["feather", "bird", "soft"], "a single blue feather"),
    ("fur", "Fur", "animals", "🧸", "Fur", ["fur", "fluffy", "soft"], "a fluffy patch of brown fur being petted by a hand"),
    ("wing", "Wing", "animals", "🪽", "Wing", ["wing", "fly", "bird"], "a bird's outstretched wing"),
    ("horn", "Horn", "animals", "🐐", "Horn", ["horn", "goat", "pointy"], "a goat's head with curved horns"),
    ("shell", "Shell", "animals", "🐚", "Shell", ["shell", "beach", "turtle"], "a spiral seashell"),
    ("bark", "Bark", "animals", "🐕", "Woof", ["bark", "woof", "dog sound"], "a dog barking with a sound line"),
    ("meow", "Meow", "animals", "🐈", "Meow", ["meow", "cat sound"], "a cat meowing with a sound line"),
    ("moo", "Moo", "animals", "🐄", "Moo", ["moo", "cow sound"], "a cow mooing with a sound line"),
    ("roar", "Roar", "animals", "🦁", "Roar", ["roar", "lion sound", "loud"], "a lion roaring with sound lines"),
    ("dog_walk", "Walk the Dog", "animals", "🦮", "Walk the dog", ["walk dog", "leash", "dog"], "a child walking a dog on a leash"),
    ("feed_pet", "Feed the Pet", "animals", "🥣", "Feed the pet", ["feed pet", "food bowl", "cat"], "a child pouring food into a cat's bowl"),
    ("litter_box", "Litter Box", "animals", "🐈", "Litter box", ["litter box", "cat", "clean"], "a cat litter box with a scoop"),
    ("dog_bed", "Dog Bed", "animals", "🛏️", "Dog bed", ["dog bed", "pet", "sleep"], "a dog curled up in a round dog bed"),
    ("leash", "Leash", "animals", "🦮", "Leash", ["leash", "dog", "walk"], "a red dog leash and collar"),
    ("fish_tank", "Fish Tank", "animals", "🐠", "Fish tank", ["fish tank", "aquarium", "fish"], "a rectangular fish tank with colorful fish"),
    ("cage", "Cage", "animals", "🐹", "Cage", ["cage", "hamster", "pet"], "a small pet cage with a wheel"),
    ("birdhouse", "Birdhouse", "animals", "🏠", "Birdhouse", ["birdhouse", "bird", "feeder"], "a wooden birdhouse with a bird at the hole"),
    ("doghouse", "Doghouse", "animals", "🏠", "Doghouse", ["doghouse", "dog", "outside"], "a red doghouse with a dog inside"),
    ("bone", "Bone", "animals", "🦴", "Bone", ["bone", "dog treat", "chew"], "a single white cartoon dog bone, the kind a dog chews"),
    ("dog_treat", "Dog Treat", "animals", "🍖", "Dog treat", ["dog treat", "treat", "reward"], "a bone-shaped dog biscuit being given to a dog"),

    # --- health / body ----------------------------------------------------------
    ("face", "Face", "health", "🙂", "Face", ["face", "head"], "a child's smiling face, front view"),
    ("forehead", "Forehead", "health", "🧠", "Forehead", ["forehead", "head"], "a child's face with a hand touching the forehead"),
    ("cheek", "Cheek", "health", "😊", "Cheek", ["cheek", "face"], "a child's face with a finger pointing at a rosy cheek"),
    ("chin", "Chin", "health", "🙂", "Chin", ["chin", "face"], "a child's face with a finger touching the chin"),
    ("lips", "Lips", "health", "👄", "Lips", ["lips", "mouth"], "a pair of pink lips"),
    ("tongue", "Tongue", "health", "👅", "Tongue", ["tongue", "mouth", "taste"], "an open mouth with the tongue sticking out"),
    ("tooth", "Tooth", "health", "🦷", "Tooth", ["tooth", "teeth", "loose tooth"], "a single white tooth"),
    ("neck", "Neck", "health", "🧣", "Neck", ["neck", "throat"], "a child pointing at their neck"),
    ("shoulder", "Shoulder", "health", "🤷", "Shoulder", ["shoulder", "arm"], "a child touching their shoulder"),
    ("elbow", "Elbow", "health", "💪", "Elbow", ["elbow", "arm"], "a bent arm with the elbow highlighted"),
    ("wrist", "Wrist", "health", "⌚", "Wrist", ["wrist", "arm", "hand"], "a hand with the wrist highlighted"),
    ("finger", "Finger", "health", "☝️", "Finger", ["finger", "hand"], "a hand with one finger raised"),
    ("thumb", "Thumb", "health", "👍", "Thumb", ["thumb", "hand"], "a hand with the thumb highlighted"),
    ("fingernail", "Fingernail", "health", "💅", "Fingernail", ["fingernail", "nail", "hand"], "a hand with painted fingernails"),
    ("chest", "Chest", "health", "🫁", "Chest", ["chest", "body"], "a child pointing at their chest"),
    ("belly_button", "Belly Button", "health", "🔘", "Belly button", ["belly button", "tummy"], "a child's tummy with the belly button showing"),
    ("hip", "Hip", "health", "🦴", "Hip", ["hip", "body", "side"], "a child with hands on their hips"),
    ("bottom_health", "Bottom", "health", "🍑", "Bottom", ["bottom", "butt", "sit"], "a child sitting on a chair, side view, pointing at their bottom"),
    ("knee", "Knee", "health", "🦵", "Knee", ["knee", "leg"], "a bent leg with the knee highlighted"),
    ("ankle", "Ankle", "health", "🦶", "Ankle", ["ankle", "foot"], "a foot with the ankle highlighted"),
    ("toe", "Toe", "health", "🦶", "Toe", ["toe", "foot"], "a foot with the big toe highlighted"),
    ("heel", "Heel", "health", "🦶", "Heel", ["heel", "foot"], "a foot side view with the heel highlighted"),
    ("skin", "Skin", "health", "🖐️", "Skin", ["skin", "body"], "a hand touching an arm"),
    ("bones", "Bones", "health", "🦴", "Bones", ["bones", "skeleton"], "a friendly cartoon skeleton"),
    ("muscles", "Muscles", "health", "💪", "Muscles", ["muscles", "strong", "arm"], "a flexed arm with muscles"),
    ("heart_organ", "Heart", "health", "❤️", "Heart", ["heart", "heartbeat", "body"], "a red heart with a heartbeat line"),
    ("brain", "Brain", "health", "🧠", "Brain", ["brain", "think", "head"], "a pink brain"),
    ("lungs", "Lungs", "health", "🫁", "Lungs", ["lungs", "breathe"], "a pair of pink lungs"),
    ("stomach", "Stomach", "health", "🫃", "Stomach", ["stomach", "tummy", "belly"], "a child holding their belly"),
    ("blood", "Blood", "health", "🩸", "Blood", ["blood", "bleeding", "cut"], "a red drop of blood on a finger"),
    ("scrape", "Scrape", "health", "🩹", "Scrape", ["scrape", "scratch", "skinned knee"], "a child's knee with a red scrape"),
    ("cut_health", "Cut", "health", "🩸", "Cut", ["cut", "bleeding", "hurt"], "a finger with a small cut and a drop of blood"),
    ("bruise", "Bruise", "health", "🟣", "Bruise", ["bruise", "purple", "bump"], "an arm with a purple bruise"),
    ("bump", "Bump", "health", "🤕", "Bump", ["bump", "hit head", "ouch"], "a child with a bump on their head and a star"),
    ("burn", "Burn", "health", "🔥", "Burn", ["burn", "hot", "hurt"], "a hand with a red burn near a hot stove"),
    ("sunburn", "Sunburn", "health", "🌞", "Sunburn", ["sunburn", "red", "sun"], "a child with red sunburned shoulders"),
    ("bug_bite", "Bug Bite", "health", "🦟", "Bug bite", ["bug bite", "itchy", "mosquito"], "an arm with a red itchy bump and a mosquito"),
    ("splinter", "Splinter", "health", "🪵", "Splinter", ["splinter", "finger", "wood"], "a finger with a tiny splinter and tweezers"),
    ("sprain", "Sprain", "health", "🦶", "Sprain", ["sprain", "twisted ankle", "hurt"], "a swollen ankle wrapped in a bandage"),
    ("broken_bone", "Broken Bone", "health", "🦴", "Broken bone", ["broken bone", "cast", "fracture"], "an arm in a white cast"),
    ("cast", "Cast", "health", "🩼", "Cast", ["cast", "broken", "arm"], "a child with a cast on their arm and signatures"),
    ("crutches", "Crutches", "health", "🩼", "Crutches", ["crutches", "walk", "leg"], "a child walking with crutches"),
    ("stitches", "Stitches", "health", "🧵", "Stitches", ["stitches", "cut", "doctor"], "a small cut closed with stitches"),
    ("bandage", "Bandage", "health", "🩹", "Bandage", ["bandage", "wrap", "gauze"], "a rolled white gauze bandage"),
    ("nosebleed", "Nosebleed", "health", "🩸", "Nosebleed", ["nosebleed", "nose", "blood"], "a child holding a tissue to a bleeding nose"),
    ("runny_nose", "Runny Nose", "health", "🤧", "Runny nose", ["runny nose", "cold", "tissue"], "a child with a runny nose holding a tissue"),
    ("stuffy_nose", "Stuffy Nose", "health", "😤", "Stuffy nose", ["stuffy nose", "congested", "cold"], "a child with a red blocked nose"),
    ("sneeze", "Sneeze", "health", "🤧", "Sneeze", ["sneeze", "achoo"], "a child mid-sneeze"),
    ("cough", "Cough", "health", "😷", "Cough", ["cough", "sick", "throat"], "a child coughing into their elbow"),
    ("sore_throat", "Sore Throat", "health", "😣", "Sore throat", ["sore throat", "throat hurts"], "a child holding their throat with a red glow"),
    ("earache", "Earache", "health", "👂", "Earache", ["earache", "ear hurts", "ear infection"], "a child holding their ear with a pain star"),
    ("toothache", "Toothache", "health", "🦷", "Toothache", ["toothache", "tooth hurts", "dentist"], "a child holding their cheek with a pain star and a tooth"),
    ("stomach_ache", "Stomach Ache", "health", "🤢", "Stomach ache", ["stomach ache", "belly hurts"], "a child bent over holding their stomach"),
    ("throw_up", "Throw Up", "health", "🤮", "I threw up", ["throw up", "vomit", "sick"], "a child leaning over a bucket looking green"),
    ("diarrhea", "Diarrhea", "health", "🚽", "Diarrhea", ["diarrhea", "bathroom", "tummy"], "a child rushing to a toilet holding their stomach"),
    ("constipated", "Constipated", "health", "😖", "Constipated", ["constipated", "can't poop", "tummy"], "a child sitting on a toilet with a strained face"),
    ("rash", "Rash", "health", "🔴", "Rash", ["rash", "red spots", "itchy"], "an arm with red spots"),
    ("hives", "Hives", "health", "🔴", "Hives", ["hives", "allergy", "bumps"], "an arm with raised red welts"),
    ("swollen", "Swollen", "health", "🎈", "Swollen", ["swollen", "puffy", "big"], "a puffy swollen hand"),
    ("chills", "Chills", "health", "🥶", "Chills", ["chills", "shivering", "cold"], "a child shivering under a blanket"),
    ("sweaty", "Sweaty", "health", "💦", "Sweaty", ["sweaty", "hot", "sweat"], "a child with sweat drops on their forehead"),
    ("faint", "Faint", "health", "😵", "I feel faint", ["faint", "dizzy", "pass out"], "a child wobbling with swirls around their head"),
    ("seizure", "Seizure", "health", "⚡", "Seizure", ["seizure", "epilepsy", "emergency"], "a child lying on their side on a mat with an adult nearby, lightning symbol"),
    ("asthma", "Asthma", "health", "🫁", "Asthma", ["asthma", "inhaler", "breathe"], "a child using an inhaler with lungs symbol"),
    ("cant_breathe", "Can't Breathe", "health", "😮", "I can't breathe", ["can't breathe", "breathing", "emergency"], "a child holding their chest with an open mouth and a warning triangle"),
    ("choking", "Choking", "health", "🆘", "Choking", ["choking", "can't breathe", "emergency"], "a child with hands at their throat, universal choking sign"),
    ("allergic", "Allergic", "health", "🥜", "I'm allergic", ["allergic", "allergy", "no"], "a peanut with a red no symbol over it"),
    ("epipen", "EpiPen", "health", "💉", "EpiPen", ["epipen", "allergy", "emergency"], "an epinephrine auto-injector pen"),
    ("pill", "Pill", "health", "💊", "Pill", ["pill", "medicine", "take"], "a red and white capsule pill"),
    ("liquid_medicine", "Liquid Medicine", "health", "🥄", "Liquid medicine", ["liquid medicine", "syrup", "spoon"], "a bottle of pink medicine with a measuring spoon"),
    ("chewable", "Chewable", "health", "🍬", "Chewable medicine", ["chewable", "vitamin", "medicine"], "a chewable tablet shaped like a bear"),
    ("vitamins", "Vitamins", "health", "🍊", "Vitamins", ["vitamins", "gummy", "healthy"], "a bottle of gummy vitamins"),
    ("eye_drops", "Eye Drops", "health", "👁️", "Eye drops", ["eye drops", "eyes", "medicine"], "a dropper bottle putting a drop into an eye"),
    ("nose_spray", "Nose Spray", "health", "👃", "Nose spray", ["nose spray", "nasal", "medicine"], "a nasal spray bottle"),
    ("ointment", "Ointment", "health", "🧴", "Ointment", ["ointment", "cream", "rub"], "a tube of cream being squeezed onto a finger"),
    ("cough_drop", "Cough Drop", "health", "🍬", "Cough drop", ["cough drop", "throat", "lozenge"], "a wrapped cough drop"),
    ("humidifier", "Humidifier", "health", "💨", "Humidifier", ["humidifier", "mist", "sick"], "a humidifier puffing mist"),
    ("heating_pad", "Heating Pad", "health", "🔥", "Heating pad", ["heating pad", "warm", "pain"], "a warm heating pad on a child's back"),
    ("blood_pressure", "Blood Pressure", "health", "🩺", "Blood pressure", ["blood pressure", "cuff", "doctor"], "a blood pressure cuff on an arm"),
    ("stethoscope", "Stethoscope", "health", "🩺", "Stethoscope", ["stethoscope", "doctor", "listen"], "a stethoscope"),
    ("x_ray", "X-Ray", "health", "🩻", "X-ray", ["x-ray", "bones", "picture"], "an x-ray image of a hand"),
    ("blood_test", "Blood Test", "health", "🩸", "Blood test", ["blood test", "needle", "lab"], "a small vial of blood with a bandage on an arm"),
    ("checkup", "Checkup", "health", "🩺", "Checkup", ["checkup", "doctor visit", "exam"], "a doctor listening to a child's heart with a stethoscope"),
    ("exam_table", "Exam Table", "health", "🛏️", "Exam table", ["exam table", "doctor", "sit"], "a child sitting on a paper-covered exam table"),
    ("otoscope", "Ear Check", "health", "👂", "Ear check", ["ear check", "otoscope", "doctor"], "a doctor looking into a child's ear with a light"),
    ("tongue_depressor", "Say Ahh", "health", "😮", "Say ahh", ["say ahh", "throat check", "tongue depressor"], "a child opening wide while a doctor uses a flat stick"),
    ("height_check", "Height Check", "health", "📏", "Height check", ["height", "measure", "tall"], "a child standing against a height chart"),
    ("weight_check", "Weight Check", "health", "⚖️", "Weight check", ["weight", "scale", "doctor"], "a child standing on a doctor's scale"),
    ("eye_test", "Eye Test", "health", "👁️", "Eye test", ["eye test", "eye chart", "glasses"], "a child covering one eye with a hand while a doctor points at a row of simple shapes, circle triangle square, on a board, no letters"),
    ("hearing_test", "Hearing Test", "health", "👂", "Hearing test", ["hearing test", "headphones", "beep"], "a child wearing headphones raising a hand"),
    ("dental_cleaning", "Teeth Cleaning", "health", "🦷", "Teeth cleaning", ["teeth cleaning", "dentist", "polish"], "a dentist cleaning a child's teeth in a chair"),
    ("cavity", "Cavity", "health", "🦷", "Cavity", ["cavity", "tooth", "dentist"], "a tooth with a dark spot and a sad face"),
    ("braces", "Braces", "health", "😬", "Braces", ["braces", "teeth", "orthodontist"], "a smile with metal braces"),
    ("retainer", "Retainer", "health", "🦷", "Retainer", ["retainer", "teeth"], "a clear dental retainer"),
    ("loose_tooth", "Loose Tooth", "health", "🦷", "Loose tooth", ["loose tooth", "wiggly", "tooth fairy"], "a child wiggling a loose front tooth"),
    ("surgery", "Surgery", "health", "🏥", "Surgery", ["surgery", "operation", "hospital"], "a hospital bed with a doctor in a mask"),
    ("hospital_bed", "Hospital Bed", "health", "🛏️", "Hospital bed", ["hospital bed", "hospital", "stay"], "a hospital bed with rails"),
    ("iv", "IV", "health", "💧", "IV", ["iv", "drip", "hospital"], "an IV bag on a pole with a tube to an arm"),
    ("mask", "Mask", "health", "😷", "Mask", ["mask", "face mask", "germs"], "a child wearing a blue face mask"),
    ("germs", "Germs", "health", "🦠", "Germs", ["germs", "sick", "wash"], "cartoon green germs with angry faces"),
    ("wash_germs", "Wash Away Germs", "health", "🧼", "Wash away germs", ["wash", "germs", "soap"], "hands washing with soap and germs floating away"),
    ("healthy", "Healthy", "health", "💪", "Healthy", ["healthy", "well", "strong"], "a child flexing with an apple and a green check"),
    ("sick_day", "Sick Day", "health", "🛌", "Sick day", ["sick day", "stay home", "rest"], "a child in bed with a tissue box and a thermometer"),
    ("feel_better", "Feel Better", "health", "🌈", "I feel better", ["feel better", "recovered", "okay now"], "a child sitting up in bed smiling with a rainbow"),
    ("doctor_visit", "Doctor Visit", "health", "🏥", "Doctor visit", ["doctor visit", "appointment"], "a child and parent walking into a clinic"),
    ("appointment", "Appointment", "health", "📅", "Appointment", ["appointment", "calendar", "doctor"], "a calendar with a stethoscope on one day"),
    ("therapy_session", "Therapy", "health", "🧩", "Therapy", ["therapy", "session", "help"], "a child and therapist at a table with picture cards"),
    ("aac_device", "Talker", "health", "📱", "My talker", ["talker", "aac", "device"], "a tablet with a grid of picture buttons"),
    ("hearing_aids", "Hearing Aids", "health", "🦻", "Hearing aids", ["hearing aids", "ears", "hear"], "a small hearing aid on an ear"),
    ("cochlear", "Cochlear Implant", "health", "🦻", "Cochlear implant", ["cochlear", "implant", "hear"], "a cochlear implant processor on the side of a head"),
    ("walker", "Walker", "health", "🚶", "Walker", ["walker", "walk", "support"], "a child using a walker"),
    ("cane", "Cane", "health", "🦯", "Cane", ["cane", "walk", "support"], "a walking cane"),
    ("brace", "Brace", "health", "🦿", "Brace", ["brace", "leg brace", "support"], "a leg brace on a child's leg"),
    ("orthotics", "Orthotics", "health", "👟", "Orthotics", ["orthotics", "shoe inserts"], "a pair of shoe inserts"),
    ("feeding_tube", "Feeding Tube", "health", "🩺", "Feeding tube", ["feeding tube", "g-tube", "eat"], "a child with a small feeding tube button on their tummy"),
    ("oxygen", "Oxygen", "health", "💨", "Oxygen", ["oxygen", "breathe", "tank"], "an oxygen tank with a nasal tube"),
    ("nebulizer", "Nebulizer", "health", "😷", "Nebulizer", ["nebulizer", "breathing treatment", "mist"], "a child breathing mist from a nebulizer mask"),
    ("insulin", "Insulin", "health", "💉", "Insulin", ["insulin", "diabetes", "shot"], "an insulin pen and a glucose meter"),
    ("sugar_check", "Sugar Check", "health", "🩸", "Check my sugar", ["sugar check", "diabetes", "finger prick"], "a finger prick with a glucose meter"),
    ("sensory_overload", "Sensory Overload", "health", "🌪️", "Too much", ["sensory overload", "too much", "overwhelmed"], "a child covering ears and eyes with swirling noise and light lines"),
    ("meltdown", "Meltdown", "health", "🌋", "I'm having a meltdown", ["meltdown", "upset", "overwhelmed"], "a child crying with fists clenched and storm lines"),
    ("calm_down", "Calm Down", "health", "🧘", "Calm down", ["calm down", "relax", "breathe"], "a child breathing slowly with a hand on their chest, soft waves"),
    ("calm_corner", "Calm Corner", "health", "🛋️", "Calm corner", ["calm corner", "quiet space", "break"], "a cozy corner with a bean bag, pillows and a lamp"),
    ("noise_cancelling", "Noise Headphones", "health", "🎧", "Noise headphones", ["noise cancelling", "headphones", "quiet"], "a child wearing big over-ear headphones with sound blocked"),
    ("tight_hug", "Deep Pressure", "health", "🤗", "Squeeze me", ["deep pressure", "squeeze", "tight hug"], "an adult giving a child a firm hug"),
    ("stim", "Stim", "health", "🙌", "Stim", ["stim", "flap", "rock"], "a child happily flapping hands with motion lines"),

    # --- vehicles ---------------------------------------------------------------
    ("van", "Van", "vehicles", "🚐", "Van", ["van", "minivan", "car"], "a blue minivan"),
    ("suv", "SUV", "vehicles", "🚙", "SUV", ["suv", "car", "big car"], "a gray SUV"),
    ("pickup_truck", "Pickup Truck", "vehicles", "🛻", "Pickup truck", ["pickup", "truck"], "a red pickup truck"),
    ("semi_truck", "Semi Truck", "vehicles", "🚛", "Semi truck", ["semi", "big truck", "eighteen wheeler"], "a big semi truck with a trailer"),
    ("tow_truck", "Tow Truck", "vehicles", "🚚", "Tow truck", ["tow truck", "truck", "broken car"], "a tow truck pulling a car"),
    ("dump_truck", "Dump Truck", "vehicles", "🚛", "Dump truck", ["dump truck", "construction", "dirt"], "a yellow dump truck tipping dirt"),
    ("cement_mixer", "Cement Mixer", "vehicles", "🚛", "Cement mixer", ["cement mixer", "construction", "truck"], "a cement mixer truck with a spinning drum"),
    ("bulldozer", "Bulldozer", "vehicles", "🚜", "Bulldozer", ["bulldozer", "construction", "push"], "a yellow bulldozer pushing dirt"),
    ("excavator", "Excavator", "vehicles", "🏗️", "Excavator", ["excavator", "digger", "construction"], "a yellow excavator with a digging arm"),
    ("crane", "Crane", "vehicles", "🏗️", "Crane", ["crane", "construction", "lift"], "a tall construction crane lifting a beam"),
    ("forklift", "Forklift", "vehicles", "🏗️", "Forklift", ["forklift", "warehouse", "lift"], "a forklift lifting a box"),
    ("mail_truck", "Mail Truck", "vehicles", "📬", "Mail truck", ["mail truck", "mail", "delivery"], "a white mail truck with a red and blue stripe"),
    ("delivery_truck", "Delivery Truck", "vehicles", "🚚", "Delivery truck", ["delivery truck", "package", "truck"], "a brown delivery truck with boxes"),
    ("ice_cream_truck", "Ice Cream Truck", "vehicles", "🍦", "Ice cream truck", ["ice cream truck", "music", "treat"], "a colorful ice cream truck with a window"),
    ("food_truck", "Food Truck", "vehicles", "🚚", "Food truck", ["food truck", "tacos", "eat"], "a food truck with a serving window"),
    ("city_bus", "City Bus", "vehicles", "🚌", "City bus", ["city bus", "bus", "ride"], "a blue city bus"),
    ("trolley", "Trolley", "vehicles", "🚋", "Trolley", ["trolley", "streetcar", "tram"], "a red trolley car on tracks"),
    ("monorail", "Monorail", "vehicles", "🚝", "Monorail", ["monorail", "train", "ride"], "a sleek monorail on an elevated track"),
    ("freight_train", "Freight Train", "vehicles", "🚂", "Freight train", ["freight train", "train", "cargo"], "a train pulling cargo cars"),
    ("steam_train", "Steam Train", "vehicles", "🚂", "Steam train", ["steam train", "choo choo", "train"], "an old steam locomotive puffing smoke"),
    ("jet", "Jet", "vehicles", "🛩️", "Jet", ["jet", "fast plane", "airplane"], "a sleek fighter jet"),
    ("hot_air_balloon", "Hot Air Balloon", "vehicles", "🎈", "Hot air balloon", ["hot air balloon", "balloon", "fly"], "a striped hot air balloon with a basket"),
    ("blimp", "Blimp", "vehicles", "🎈", "Blimp", ["blimp", "airship"], "a blimp floating in the sky"),
    ("glider", "Glider", "vehicles", "🪂", "Glider", ["glider", "plane", "fly"], "a white glider plane soaring"),
    ("parachute", "Parachute", "vehicles", "🪂", "Parachute", ["parachute", "jump", "float"], "a person floating under a colorful parachute"),
    ("space_shuttle", "Space Shuttle", "vehicles", "🚀", "Space shuttle", ["space shuttle", "rocket", "space"], "a space shuttle lifting off"),
    ("ufo", "UFO", "vehicles", "🛸", "UFO", ["ufo", "spaceship", "alien"], "a silver flying saucer with lights"),
    ("sailboat", "Sailboat", "vehicles", "⛵", "Sailboat", ["sailboat", "boat", "sail"], "a sailboat with a white sail"),
    ("speedboat", "Speedboat", "vehicles", "🚤", "Speedboat", ["speedboat", "fast boat"], "a speedboat making a wake"),
    ("ferry", "Ferry", "vehicles", "⛴️", "Ferry", ["ferry", "boat", "ride"], "a ferry boat carrying cars"),
    ("cruise_ship", "Cruise Ship", "vehicles", "🛳️", "Cruise ship", ["cruise ship", "ship", "vacation"], "a big white cruise ship"),
    ("canoe", "Canoe", "vehicles", "🛶", "Canoe", ["canoe", "paddle", "lake"], "a canoe with a paddle on a lake"),
    ("kayak", "Kayak", "vehicles", "🛶", "Kayak", ["kayak", "paddle", "river"], "a person paddling a yellow kayak"),
    ("raft", "Raft", "vehicles", "🛶", "Raft", ["raft", "river", "float"], "an inflatable raft on a river"),
    ("submarine", "Submarine", "vehicles", "🚢", "Submarine", ["submarine", "underwater", "sub"], "a yellow submarine with a periscope"),
    ("jet_ski", "Jet Ski", "vehicles", "🚤", "Jet ski", ["jet ski", "water", "fast"], "a person riding a jet ski"),
    ("tricycle", "Tricycle", "vehicles", "🚲", "Tricycle", ["tricycle", "trike", "ride"], "a red tricycle"),
    ("balance_bike", "Balance Bike", "vehicles", "🚲", "Balance bike", ["balance bike", "bike", "learn"], "a small bike with no pedals"),
    ("training_wheels", "Training Wheels", "vehicles", "🚲", "Bike with training wheels", ["training wheels", "bike", "learn"], "a bike with small training wheels"),
    ("unicycle", "Unicycle", "vehicles", "🚲", "Unicycle", ["unicycle", "one wheel"], "a person riding a one-wheeled unicycle"),
    ("wagon", "Wagon", "vehicles", "🛒", "Wagon", ["wagon", "pull", "red wagon"], "a red wagon with a handle"),
    ("stroller", "Stroller", "vehicles", "👶", "Stroller", ["stroller", "baby", "push"], "a baby stroller"),
    ("wheelchair_veh", "Wheelchair", "vehicles", "♿", "Wheelchair", ["wheelchair", "wheels", "ride"], "a child in a wheelchair"),
    ("power_chair", "Power Chair", "vehicles", "🦽", "Power chair", ["power chair", "electric wheelchair", "joystick"], "a child in a motorized wheelchair with a joystick"),
    ("golf_cart", "Golf Cart", "vehicles", "🛺", "Golf cart", ["golf cart", "cart", "ride"], "a white golf cart"),
    ("atv", "ATV", "vehicles", "🏍️", "ATV", ["atv", "four wheeler", "ride"], "a four-wheeler ATV"),
    ("snowmobile", "Snowmobile", "vehicles", "🏂", "Snowmobile", ["snowmobile", "snow", "ride"], "a snowmobile on snow"),
    ("snowplow", "Snowplow", "vehicles", "🚜", "Snowplow", ["snowplow", "snow", "truck"], "a truck with a plow pushing snow"),
    ("street_sweeper", "Street Sweeper", "vehicles", "🧹", "Street sweeper", ["street sweeper", "truck", "clean"], "a street sweeper truck with brushes"),
    ("limo", "Limo", "vehicles", "🚘", "Limo", ["limo", "limousine", "fancy"], "a long black limousine"),
    ("race_car", "Race Car", "vehicles", "🏎️", "Race car", ["race car", "fast", "racing"], "a red race car with a number"),
    ("monster_truck", "Monster Truck", "vehicles", "🚙", "Monster truck", ["monster truck", "big wheels"], "a monster truck with giant wheels"),
    ("convertible", "Convertible", "vehicles", "🚗", "Convertible", ["convertible", "car", "top down"], "a red convertible with the top down"),
    ("electric_car", "Electric Car", "vehicles", "🔌", "Electric car", ["electric car", "charge", "car"], "a car plugged into a charging station"),
    ("carriage", "Horse Carriage", "vehicles", "🐎", "Horse carriage", ["carriage", "horse", "ride"], "a horse pulling a carriage"),
    ("sleigh", "Sleigh", "vehicles", "🛷", "Sleigh", ["sleigh", "santa", "snow"], "a red sleigh on snow"),
    ("elevator_ride", "Ride", "vehicles", "🎢", "Go for a ride", ["ride", "go", "trip"], "a child in a car seat looking out a window happily"),
    ("seat_belt", "Seat Belt", "vehicles", "🔒", "Seat belt", ["seat belt", "buckle", "safe"], "a fastened seat belt"),
    ("car_seat", "Car Seat", "vehicles", "🪑", "Car seat", ["car seat", "booster", "safe"], "a child car seat"),
    ("steering_wheel", "Steering Wheel", "vehicles", "🛞", "Steering wheel", ["steering wheel", "drive"], "a steering wheel"),
    ("wheel", "Wheel", "vehicles", "🛞", "Wheel", ["wheel", "tire", "round"], "a black tire with a silver rim"),
    ("flat_tire", "Flat Tire", "vehicles", "🛞", "Flat tire", ["flat tire", "broken", "car"], "a car with a flat squashed tire"),
    ("traffic_light", "Traffic Light", "vehicles", "🚦", "Traffic light", ["traffic light", "stop light", "red green"], "a traffic light with red, yellow and green"),
    ("stop_sign", "Stop Sign", "vehicles", "🛑", "Stop sign", ["stop sign", "stop", "red"], "a red octagon stop sign on a post"),
    ("road", "Road", "vehicles", "🛣️", "Road", ["road", "highway", "drive"], "a road stretching to the horizon with dashed lines"),
    ("bridge", "Bridge", "vehicles", "🌉", "Bridge", ["bridge", "cross", "river"], "a bridge over a river"),
    ("tunnel_road", "Tunnel", "vehicles", "🚇", "Tunnel", ["tunnel", "dark", "drive through"], "a car entering a tunnel through a mountain"),
    ("traffic", "Traffic", "vehicles", "🚗", "Traffic", ["traffic", "jam", "slow"], "a line of cars bumper to bumper"),
    ("gas", "Gas", "vehicles", "⛽", "Gas", ["gas", "fuel", "fill up"], "a gas pump nozzle filling a car"),
    ("map", "Map", "vehicles", "🗺️", "Map", ["map", "directions", "where"], "a folded map with a route line"),
    ("gps", "GPS", "vehicles", "📍", "GPS", ["gps", "directions", "navigate"], "a phone screen showing a map with a route arrow"),
    ("ticket", "Ticket", "vehicles", "🎫", "Ticket", ["ticket", "ride", "admission"], "a paper ticket stub"),
    ("suitcase", "Suitcase", "vehicles", "🧳", "Suitcase", ["suitcase", "luggage", "trip"], "a rolling suitcase"),
    ("vacation", "Vacation", "vehicles", "🏖️", "Vacation", ["vacation", "trip", "holiday"], "a suitcase, sunglasses and a beach umbrella"),
    ("road_trip", "Road Trip", "vehicles", "🚗", "Road trip", ["road trip", "long drive", "car"], "a car packed with bags driving on a road with a map"),
    ("fly_trip", "Fly on a Plane", "vehicles", "✈️", "Fly on a plane", ["fly", "airplane trip", "travel"], "a child looking out an airplane window at clouds"),

    # --- nature / weather -------------------------------------------------------
    ("sunny", "Sunny", "nature", "☀️", "Sunny", ["sunny", "sun", "bright"], "a big bright sun in a clear blue sky"),
    ("cloudy", "Cloudy", "nature", "☁️", "Cloudy", ["cloudy", "clouds", "gray"], "a sky full of gray clouds"),
    ("partly_cloudy", "Partly Cloudy", "nature", "⛅", "Partly cloudy", ["partly cloudy", "sun and clouds"], "a sun peeking from behind a cloud"),
    ("rainy", "Rainy", "nature", "🌧️", "Rainy", ["rainy", "rain", "wet"], "a cloud raining on a puddle"),
    ("drizzle", "Drizzle", "nature", "🌦️", "Drizzle", ["drizzle", "light rain", "sprinkle"], "a cloud with a few light rain drops and a sun"),
    ("storm", "Storm", "nature", "⛈️", "Storm", ["storm", "thunderstorm", "lightning"], "a dark cloud with lightning and heavy rain"),
    ("lightning", "Lightning", "nature", "⚡", "Lightning", ["lightning", "flash", "storm"], "a bright lightning bolt from a dark cloud"),
    ("tornado", "Tornado", "nature", "🌪️", "Tornado", ["tornado", "twister", "wind"], "a spinning funnel tornado"),
    ("hurricane", "Hurricane", "nature", "🌀", "Hurricane", ["hurricane", "storm", "wind"], "a swirling hurricane symbol over the ocean"),
    ("windy", "Windy", "nature", "💨", "Windy", ["windy", "wind", "blow"], "a tree bending in the wind with leaves flying"),
    ("hail", "Hail", "nature", "🧊", "Hail", ["hail", "ice", "storm"], "a cloud dropping white ice balls"),
    ("sleet", "Sleet", "nature", "🌨️", "Sleet", ["sleet", "icy rain", "cold"], "a cloud dropping mixed rain and ice"),
    ("blizzard", "Blizzard", "nature", "❄️", "Blizzard", ["blizzard", "snowstorm", "cold"], "heavy blowing snow with a bent tree"),
    ("snowflake", "Snowflake", "nature", "❄️", "Snowflake", ["snowflake", "snow", "winter"], "a single detailed white snowflake"),
    ("icy", "Icy", "nature", "🧊", "Icy", ["icy", "slippery", "ice"], "an icy sidewalk with a child slipping"),
    ("frost", "Frost", "nature", "❄️", "Frost", ["frost", "cold", "morning"], "a window with frost patterns"),
    ("humid", "Humid", "nature", "💧", "Humid", ["humid", "sticky", "muggy"], "a sweaty child with a wavy heat line and water drops"),
    ("dry_nature", "Dry", "nature", "🏜️", "Dry", ["dry", "no rain", "desert"], "cracked dry ground with a sun"),
    ("warm_weather", "Warm", "nature", "🌤️", "Warm", ["warm", "nice out", "mild"], "a child in a t-shirt under a soft sun"),
    ("cool_weather", "Cool", "nature", "🍃", "Cool", ["cool", "chilly", "jacket"], "a child in a light jacket with a few leaves blowing"),
    ("freezing", "Freezing", "nature", "🥶", "Freezing", ["freezing", "very cold", "ice"], "a thermometer showing very cold with icicles"),
    ("temperature", "Temperature", "nature", "🌡️", "Temperature", ["temperature", "thermometer", "degrees"], "a thermometer with a sun and a snowflake"),
    ("forecast", "Forecast", "nature", "📺", "Weather forecast", ["forecast", "weather", "tv"], "a tv screen showing weather icons for the week"),
    ("sunrise", "Sunrise", "nature", "🌅", "Sunrise", ["sunrise", "morning", "sun"], "a sun rising over hills"),
    ("sunset", "Sunset", "nature", "🌇", "Sunset", ["sunset", "evening", "orange sky"], "a sun setting over the ocean with an orange sky"),
    ("daytime", "Daytime", "nature", "🌞", "Daytime", ["daytime", "day", "light"], "a bright blue sky with a sun over a house"),
    ("nighttime", "Nighttime", "nature", "🌙", "Nighttime", ["nighttime", "night", "dark"], "a dark blue sky with a moon and stars over a house"),
    ("full_moon", "Full Moon", "nature", "🌕", "Full moon", ["full moon", "moon", "night"], "a big round full moon"),
    ("crescent_moon", "Crescent Moon", "nature", "🌙", "Crescent moon", ["crescent", "moon", "night"], "a yellow crescent moon"),
    ("shooting_star", "Shooting Star", "nature", "🌠", "Shooting star", ["shooting star", "wish", "night"], "a star streaking across a night sky"),
    ("planet", "Planet", "nature", "🪐", "Planet", ["planet", "space", "saturn"], "a ringed planet"),
    ("earth", "Earth", "nature", "🌍", "Earth", ["earth", "world", "globe"], "the planet Earth"),
    ("comet", "Comet", "nature", "☄️", "Comet", ["comet", "space", "tail"], "a comet with a glowing tail"),
    ("galaxy", "Galaxy", "nature", "🌌", "Galaxy", ["galaxy", "stars", "space"], "a swirling purple galaxy"),
    ("sky", "Sky", "nature", "🌤️", "Sky", ["sky", "up", "blue"], "a blue sky with a few white clouds"),
    ("hill", "Hill", "nature", "⛰️", "Hill", ["hill", "up", "roll"], "a green rolling hill"),
    ("volcano", "Volcano", "nature", "🌋", "Volcano", ["volcano", "lava", "erupt"], "a volcano erupting with orange lava"),
    ("rock_nature", "Rock", "nature", "🪨", "Rock", ["rock", "stone"], "a gray rock"),
    ("pebble", "Pebble", "nature", "🪨", "Pebble", ["pebble", "small rock", "smooth"], "a few small smooth pebbles"),
    ("boulder", "Boulder", "nature", "🪨", "Boulder", ["boulder", "big rock"], "a huge boulder with a small child beside it"),
    ("sand", "Sand", "nature", "🏖️", "Sand", ["sand", "beach", "dig"], "a pile of sand with a shovel"),
    ("dirt", "Dirt", "nature", "🟫", "Dirt", ["dirt", "mud", "soil"], "a pile of brown dirt"),
    ("mud", "Mud", "nature", "🟫", "Mud", ["mud", "muddy", "messy"], "a muddy puddle with a boot print"),
    ("puddle", "Puddle", "nature", "💧", "Puddle", ["puddle", "water", "splash"], "a puddle on the ground with a rain boot"),
    ("pond", "Pond", "nature", "🐸", "Pond", ["pond", "water", "frog"], "a small pond with lily pads and a frog"),
    ("stream", "Stream", "nature", "🏞️", "Stream", ["stream", "creek", "water"], "a small stream running over rocks"),
    ("wave_nature", "Wave", "nature", "🌊", "Wave", ["wave", "ocean", "surf"], "a big blue ocean wave"),
    ("tide", "Tide", "nature", "🌊", "Tide", ["tide", "ocean", "beach"], "waves washing up on a beach"),
    ("seashell", "Seashell", "nature", "🐚", "Seashell", ["seashell", "beach", "shell"], "a pink spiral seashell on sand"),
    ("seaweed", "Seaweed", "nature", "🌿", "Seaweed", ["seaweed", "ocean", "green"], "green seaweed waving under water"),
    ("coral", "Coral", "nature", "🪸", "Coral", ["coral", "reef", "ocean"], "colorful coral on the sea floor"),
    ("iceberg", "Iceberg", "nature", "🧊", "Iceberg", ["iceberg", "ice", "cold"], "an iceberg floating in the ocean"),
    ("glacier", "Glacier", "nature", "🏔️", "Glacier", ["glacier", "ice", "mountain"], "a giant ice glacier between mountains"),
    ("bush", "Bush", "nature", "🌳", "Bush", ["bush", "shrub", "plant"], "a round green bush"),
    ("hedge", "Hedge", "nature", "🌳", "Hedge", ["hedge", "bushes", "row"], "a neatly trimmed row of hedges"),
    ("vine", "Vine", "nature", "🌿", "Vine", ["vine", "climb", "plant"], "a green vine climbing a fence"),
    ("weed", "Weed", "nature", "🌱", "Weed", ["weed", "pull", "garden"], "a dandelion weed being pulled from the ground"),
    ("moss", "Moss", "nature", "🟢", "Moss", ["moss", "green", "soft"], "green moss on a rock"),
    ("fern", "Fern", "nature", "🌿", "Fern", ["fern", "plant", "leaves"], "a green fern plant"),
    ("cactus", "Cactus", "nature", "🌵", "Cactus", ["cactus", "desert", "spiky"], "a green cactus with a pink flower"),
    ("palm_tree", "Palm Tree", "nature", "🌴", "Palm tree", ["palm tree", "beach", "tropical"], "a tall palm tree"),
    ("pine_tree", "Pine Tree", "nature", "🌲", "Pine tree", ["pine tree", "evergreen", "christmas"], "a tall green pine tree"),
    ("oak_tree", "Oak Tree", "nature", "🌳", "Oak tree", ["oak tree", "big tree", "acorn"], "a big leafy oak tree"),
    ("apple_tree", "Apple Tree", "nature", "🍎", "Apple tree", ["apple tree", "fruit tree", "orchard"], "a tree full of red apples"),
    ("cherry_blossom", "Cherry Blossom", "nature", "🌸", "Cherry blossom", ["cherry blossom", "pink", "spring"], "a tree covered in pink blossoms"),
    ("willow", "Willow Tree", "nature", "🌳", "Willow tree", ["willow", "drooping tree"], "a weeping willow tree with drooping branches"),
    ("stump", "Stump", "nature", "🪵", "Stump", ["stump", "tree stump", "sit"], "a tree stump with rings"),
    ("log", "Log", "nature", "🪵", "Log", ["log", "wood", "firewood"], "a brown log"),
    ("branch", "Branch", "nature", "🌿", "Branch", ["branch", "stick", "tree"], "a tree branch with leaves"),
    ("stick", "Stick", "nature", "🪄", "Stick", ["stick", "twig", "wood"], "a plain wooden stick"),
    ("acorn", "Acorn", "nature", "🌰", "Acorn", ["acorn", "nut", "oak"], "a brown acorn with a cap"),
    ("pinecone", "Pinecone", "nature", "🌲", "Pinecone", ["pinecone", "pine", "fall"], "a brown pinecone"),
    ("seed", "Seed", "nature", "🌱", "Seed", ["seed", "plant", "grow"], "a seed sprouting a tiny green shoot"),
    ("sprout", "Sprout", "nature", "🌱", "Sprout", ["sprout", "seedling", "grow"], "a small green sprout in soil"),
    ("root", "Root", "nature", "🌱", "Root", ["root", "underground", "plant"], "a plant with roots showing under the soil"),
    ("petal", "Petal", "nature", "🌸", "Petal", ["petal", "flower"], "a single pink flower petal"),
    ("rose", "Rose", "nature", "🌹", "Rose", ["rose", "red flower", "love"], "a red rose"),
    ("tulip", "Tulip", "nature", "🌷", "Tulip", ["tulip", "spring", "flower"], "a pink tulip"),
    ("sunflower", "Sunflower", "nature", "🌻", "Sunflower", ["sunflower", "yellow", "tall"], "a tall yellow sunflower"),
    ("daisy", "Daisy", "nature", "🌼", "Daisy", ["daisy", "white flower"], "a white daisy with a yellow center"),
    ("dandelion", "Dandelion", "nature", "🌼", "Dandelion", ["dandelion", "blow", "wish"], "a fluffy white dandelion with seeds blowing"),
    ("lily", "Lily", "nature", "🌸", "Lily", ["lily", "flower"], "a white lily flower"),
    ("bouquet", "Bouquet", "nature", "💐", "Bouquet", ["bouquet", "flowers", "gift"], "a bouquet of mixed flowers with a ribbon"),
    ("clover", "Clover", "nature", "☘️", "Clover", ["clover", "lucky", "green"], "a green four-leaf clover"),
    ("pumpkin_patch", "Pumpkin Patch", "nature", "🎃", "Pumpkin patch", ["pumpkin patch", "fall", "pumpkins"], "a field of orange pumpkins"),
    ("corn_field", "Corn Field", "nature", "🌽", "Corn field", ["corn field", "farm", "maze"], "rows of tall corn stalks"),
    ("hay", "Hay", "nature", "🌾", "Hay", ["hay", "farm", "bale"], "a round bale of hay"),
    ("wheat", "Wheat", "nature", "🌾", "Wheat", ["wheat", "grain", "field"], "golden wheat stalks"),
    ("lawn", "Lawn", "nature", "🌱", "Lawn", ["lawn", "grass", "yard"], "a neatly mowed green lawn"),
    ("lawn_mower", "Lawn Mower", "nature", "🚜", "Lawn mower", ["lawn mower", "mow", "grass"], "a red push lawn mower"),
    ("hose", "Hose", "nature", "🚿", "Hose", ["hose", "water", "garden"], "a green garden hose spraying water"),
    ("watering_can", "Watering Can", "nature", "🪣", "Watering can", ["watering can", "water plants"], "a green watering can"),
    ("shovel", "Shovel", "nature", "⛏️", "Shovel", ["shovel", "dig", "garden"], "a garden shovel"),
    ("rake_tool", "Rake", "nature", "🍂", "Rake", ["rake", "leaves", "tool"], "a garden rake"),
    ("wheelbarrow", "Wheelbarrow", "nature", "🛒", "Wheelbarrow", ["wheelbarrow", "garden", "push"], "a wheelbarrow full of dirt"),
    ("flower_pot", "Flower Pot", "nature", "🪴", "Flower pot", ["flower pot", "plant", "pot"], "a terracotta pot with a flower"),
    ("greenhouse", "Greenhouse", "nature", "🏡", "Greenhouse", ["greenhouse", "plants", "glass"], "a glass greenhouse full of plants"),
    ("birdfeeder", "Bird Feeder", "nature", "🐦", "Bird feeder", ["bird feeder", "seeds", "birds"], "a bird feeder with birds eating"),
    ("campfire", "Campfire", "nature", "🔥", "Campfire", ["campfire", "fire", "camping"], "a campfire with logs and flames"),
    ("smores", "S'mores", "nature", "🍫", "S'mores", ["smores", "campfire", "marshmallow"], "a s'more with a toasted marshmallow"),
    ("fire", "Fire", "nature", "🔥", "Fire", ["fire", "hot", "danger"], "bright orange flames"),
    ("smoke", "Smoke", "nature", "💨", "Smoke", ["smoke", "fire", "gray"], "gray smoke rising"),
    ("air", "Air", "nature", "🌬️", "Air", ["air", "breathe", "wind"], "soft swirling air lines with a leaf floating"),
    ("bubble", "Bubble", "nature", "🫧", "Bubble", ["bubble", "float", "pop"], "a shiny floating soap bubble"),
    ("steam", "Steam", "nature", "♨️", "Steam", ["steam", "hot", "vapor"], "steam rising from a cup"),
    ("shadow", "Shadow", "nature", "👤", "Shadow", ["shadow", "dark", "sun"], "a child with a long shadow on the ground"),
    ("reflection", "Reflection", "nature", "🪞", "Reflection", ["reflection", "mirror", "water"], "a tree reflected in still water"),
    ("echo", "Echo", "nature", "🗣️", "Echo", ["echo", "sound", "cave"], "a child shouting into a canyon with sound waves bouncing back"),
    ("environment", "Nature", "nature", "🌿", "Nature", ["nature", "outdoors", "environment"], "trees, a river, a mountain and a sun together"),
    ("earth_day", "Earth Day", "nature", "🌍", "Earth Day", ["earth day", "recycle", "planet"], "the Earth with a green leaf and a heart"),
    ("pollution", "Pollution", "nature", "🏭", "Pollution", ["pollution", "trash", "smoke"], "a factory with smoke and litter on the ground"),
    ("litter", "Litter", "nature", "🗑️", "Litter", ["litter", "trash", "pick up"], "trash on the ground with a child picking it up"),

    # --- concepts / numbers / time --------------------------------------------
    ("num_11", "11", "concepts", "🔢", "Eleven", ["11", "eleven", "number"], "the number 11 in big bold rounded digits with eleven small dots below"),
    ("num_12", "12", "concepts", "🔢", "Twelve", ["12", "twelve", "number"], "the number 12 in big bold rounded digits with twelve small dots below"),
    ("num_13", "13", "concepts", "🔢", "Thirteen", ["13", "thirteen", "number"], "the number 13 in big bold rounded digits"),
    ("num_14", "14", "concepts", "🔢", "Fourteen", ["14", "fourteen", "number"], "the number 14 in big bold rounded digits"),
    ("num_15", "15", "concepts", "🔢", "Fifteen", ["15", "fifteen", "number"], "the number 15 in big bold rounded digits"),
    ("num_16", "16", "concepts", "🔢", "Sixteen", ["16", "sixteen", "number"], "the number 16 in big bold rounded digits"),
    ("num_17", "17", "concepts", "🔢", "Seventeen", ["17", "seventeen", "number"], "the number 17 in big bold rounded digits"),
    ("num_18", "18", "concepts", "🔢", "Eighteen", ["18", "eighteen", "number"], "the number 18 in big bold rounded digits"),
    ("num_19", "19", "concepts", "🔢", "Nineteen", ["19", "nineteen", "number"], "the number 19 in big bold rounded digits"),
    ("num_20", "20", "concepts", "🔢", "Twenty", ["20", "twenty", "number"], "the number 20 in big bold rounded digits"),
    ("num_30", "30", "concepts", "🔢", "Thirty", ["30", "thirty", "number"], "the number 30 in big bold rounded digits"),
    ("num_50", "50", "concepts", "🔢", "Fifty", ["50", "fifty", "number"], "the number 50 in big bold rounded digits"),
    ("num_100", "100", "concepts", "💯", "One hundred", ["100", "hundred", "number"], "the number 100 in big bold rounded digits"),
    ("first_ordinal", "1st", "concepts", "🥇", "First", ["1st", "first place", "winner"], "a gold medal with the number 1"),
    ("second_ordinal", "2nd", "concepts", "🥈", "Second", ["2nd", "second place"], "a silver medal with the number 2"),
    ("third_ordinal", "3rd", "concepts", "🥉", "Third", ["3rd", "third place"], "a bronze medal with the number 3"),
    ("plus", "Plus", "concepts", "➕", "Plus", ["plus", "add", "math"], "a big green plus sign"),
    ("minus", "Minus", "concepts", "➖", "Minus", ["minus", "subtract", "math"], "a big red minus sign"),
    ("equals", "Equals", "concepts", "🟰", "Equals", ["equals", "same", "math"], "a big blue equals sign"),
    ("times", "Times", "concepts", "✖️", "Times", ["times", "multiply", "math"], "a big multiplication x sign"),
    ("divide", "Divide", "concepts", "➗", "Divide", ["divide", "split", "math"], "a big blue division symbol: a dot above a horizontal line above a dot"),
    ("addition", "Addition", "concepts", "➕", "Addition", ["addition", "add", "math"], "two apples plus three apples with an equals sign and five apples"),
    ("subtraction", "Subtraction", "concepts", "➖", "Subtraction", ["subtraction", "take away", "math"], "five apples with two crossed out"),
    ("counting", "Counting", "concepts", "🔢", "Counting", ["counting", "count", "numbers"], "colored blocks in a row numbered 1 2 3"),
    ("more_than", "More Than", "concepts", "▶️", "More than", ["more than", "greater", "bigger"], "a big pile of blocks next to a small pile, arrow pointing at the big one"),
    ("less_than", "Less Than", "concepts", "◀️", "Less than", ["less than", "fewer", "smaller"], "a small pile of blocks next to a big pile, arrow pointing at the small one"),
    ("equal", "Equal", "concepts", "⚖️", "Equal", ["equal", "same amount", "fair"], "two identical piles of blocks on a balanced scale"),
    ("pair", "Pair", "concepts", "👟", "Pair", ["pair", "two", "match"], "a matching pair of socks"),
    ("dozen", "Dozen", "concepts", "🥚", "Dozen", ["dozen", "twelve", "eggs"], "a carton of twelve eggs"),
    ("ruler", "Ruler", "concepts", "📏", "Ruler", ["ruler", "measure", "inches"], "a wooden ruler"),
    ("tape_measure", "Tape Measure", "concepts", "📐", "Tape measure", ["tape measure", "measure"], "a yellow tape measure"),
    ("inch", "Inch", "concepts", "📏", "Inch", ["inch", "small", "measure"], "a ruler with one inch highlighted"),
    ("foot_measure", "Foot", "concepts", "📏", "One foot", ["foot", "twelve inches", "measure"], "a ruler one foot long"),
    ("cup_measure", "Measuring Cup", "concepts", "🥛", "Measuring cup", ["measuring cup", "cup", "cooking"], "a glass measuring cup with lines"),
    ("spoon_measure", "Measuring Spoon", "concepts", "🥄", "Measuring spoon", ["measuring spoon", "teaspoon"], "a set of measuring spoons"),
    ("degrees", "Degrees", "concepts", "🌡️", "Degrees", ["degrees", "temperature"], "a thermometer with a degree mark"),
    ("percent", "Percent", "concepts", "💯", "Percent", ["percent", "part", "math"], "a big percent sign"),
    ("fraction", "Fraction", "concepts", "🍕", "Fraction", ["fraction", "part", "half"], "a pizza cut into four slices with one slice colored"),
    ("quarter", "Quarter", "concepts", "🪙", "Quarter", ["quarter", "coin", "twenty five cents"], "a silver quarter coin"),
    ("dime", "Dime", "concepts", "🪙", "Dime", ["dime", "coin", "ten cents"], "a small silver dime"),
    ("nickel", "Nickel", "concepts", "🪙", "Nickel", ["nickel", "coin", "five cents"], "a silver nickel coin"),
    ("penny", "Penny", "concepts", "🪙", "Penny", ["penny", "coin", "one cent"], "a copper penny"),
    ("dollar", "Dollar", "concepts", "💵", "Dollar", ["dollar", "money", "bill"], "a green one dollar bill"),
    ("coins", "Coins", "concepts", "🪙", "Coins", ["coins", "change", "money"], "a pile of assorted coins"),
    ("piggy_bank", "Piggy Bank", "concepts", "🐷", "Piggy bank", ["piggy bank", "save", "money"], "a pink piggy bank with a coin going in"),
    ("credit_card", "Card", "concepts", "💳", "Card", ["credit card", "debit", "pay"], "a blue bank card"),
    ("price", "Price", "concepts", "🏷️", "Price", ["price", "cost", "how much"], "a price tag with a dollar sign"),
    ("expensive", "Expensive", "concepts", "💎", "Expensive", ["expensive", "costs a lot"], "a price tag with many dollar signs and a surprised child"),
    ("cheap", "Cheap", "concepts", "🪙", "Cheap", ["cheap", "not much", "sale"], "a price tag with a single coin"),
    ("free", "Free", "concepts", "🆓", "Free", ["free", "no cost", "gift"], "a gift box with a tag showing a crossed-out dollar sign"),
    ("pay", "Pay", "concepts", "💸", "Pay", ["pay", "buy", "money"], "a hand giving money to a cashier"),
    ("buy", "Buy", "concepts", "🛍️", "Buy", ["buy", "purchase", "shop"], "a child holding a shopping bag and money"),
    ("save", "Save", "concepts", "🏦", "Save", ["save", "keep", "bank"], "a child putting a coin into a jar"),
    ("spend", "Spend", "concepts", "🛒", "Spend", ["spend", "use money", "buy"], "coins going from a hand into a cash register"),
    ("o_clock", "O'Clock", "concepts", "🕐", "O'clock", ["o'clock", "time", "hour"], "a clock face with the minute hand on twelve"),
    ("half_past", "Half Past", "concepts", "🕜", "Half past", ["half past", "thirty", "time"], "a clock face with the minute hand on six"),
    ("clock_1", "1 O'Clock", "concepts", "🕐", "One o'clock", ["1 o'clock", "one", "time"], "a clock face showing one o'clock"),
    ("clock_2", "2 O'Clock", "concepts", "🕑", "Two o'clock", ["2 o'clock", "two", "time"], "a clock face showing two o'clock"),
    ("clock_3", "3 O'Clock", "concepts", "🕒", "Three o'clock", ["3 o'clock", "three", "time"], "a clock face showing three o'clock"),
    ("clock_4", "4 O'Clock", "concepts", "🕓", "Four o'clock", ["4 o'clock", "four", "time"], "a clock face showing four o'clock"),
    ("clock_5", "5 O'Clock", "concepts", "🕔", "Five o'clock", ["5 o'clock", "five", "time"], "a clock face showing five o'clock"),
    ("clock_6", "6 O'Clock", "concepts", "🕕", "Six o'clock", ["6 o'clock", "six", "time"], "a clock face showing six o'clock"),
    ("clock_7", "7 O'Clock", "concepts", "🕖", "Seven o'clock", ["7 o'clock", "seven", "time"], "a clock face showing seven o'clock"),
    ("clock_8", "8 O'Clock", "concepts", "🕗", "Eight o'clock", ["8 o'clock", "eight", "time"], "a clock face showing eight o'clock"),
    ("clock_9", "9 O'Clock", "concepts", "🕘", "Nine o'clock", ["9 o'clock", "nine", "time"], "a clock face showing nine o'clock"),
    ("clock_10", "10 O'Clock", "concepts", "🕙", "Ten o'clock", ["10 o'clock", "ten", "time"], "a clock face showing ten o'clock"),
    ("clock_11", "11 O'Clock", "concepts", "🕚", "Eleven o'clock", ["11 o'clock", "eleven", "time"], "a clock face showing eleven o'clock"),
    ("clock_12", "12 O'Clock", "concepts", "🕛", "Twelve o'clock", ["12 o'clock", "twelve", "time"], "a clock face showing twelve o'clock"),
    ("digital_clock", "Digital Clock", "concepts", "⏰", "Digital clock", ["digital clock", "time", "numbers"], "a digital clock with glowing digits"),
    ("stopwatch", "Stopwatch", "concepts", "⏱️", "Stopwatch", ["stopwatch", "timer", "seconds"], "a stopwatch"),
    ("hourglass", "Hourglass", "concepts", "⏳", "Hourglass", ["hourglass", "sand", "time"], "an hourglass with sand falling"),
    ("january", "January", "concepts", "❄️", "January", ["january", "month", "winter"], "a calendar page with a snowflake"),
    ("february", "February", "concepts", "💝", "February", ["february", "month", "valentine"], "a calendar page with a heart"),
    ("march_concepts", "March", "concepts", "☘️", "March", ["march", "month", "clover"], "a calendar page with a shamrock"),
    ("april", "April", "concepts", "🌧️", "April", ["april", "month", "rain"], "a calendar page with an umbrella and rain"),
    ("may", "May", "concepts", "🌷", "May", ["may", "month", "flowers"], "a calendar page with flowers"),
    ("june", "June", "concepts", "☀️", "June", ["june", "month", "summer"], "a calendar page with a sun"),
    ("july", "July", "concepts", "🎆", "July", ["july", "month", "fireworks"], "a calendar page with fireworks"),
    ("august", "August", "concepts", "🏖️", "August", ["august", "month", "beach"], "a calendar page with a beach ball"),
    ("september", "September", "concepts", "🍎", "September", ["september", "month", "school"], "a calendar page with an apple and a backpack"),
    ("october", "October", "concepts", "🎃", "October", ["october", "month", "halloween"], "a calendar page with a pumpkin"),
    ("november", "November", "concepts", "🦃", "November", ["november", "month", "thanksgiving"], "a calendar page with a turkey"),
    ("december", "December", "concepts", "🎄", "December", ["december", "month", "christmas"], "a calendar page with a christmas tree"),
    ("letter_a", "A", "concepts", "🅰️", "A", ["a", "letter", "alphabet"], "a big bold uppercase letter A with a small apple"),
    ("letter_b", "B", "concepts", "🅱️", "B", ["b", "letter", "alphabet"], "a big bold uppercase letter B with a small ball"),
    ("letter_c", "C", "concepts", "©️", "C", ["c", "letter", "alphabet"], "a big bold uppercase letter C with a small cat"),
    ("alphabet", "Alphabet", "concepts", "🔤", "Alphabet", ["alphabet", "abc", "letters"], "colorful alphabet blocks spelling A B C D"),
    ("word", "Word", "concepts", "💬", "Word", ["word", "spell", "read"], "a speech bubble containing three simple colored blocks in a row, no letters"),
    ("sentence", "Sentence", "concepts", "📝", "Sentence", ["sentence", "write", "words"], "a sheet of paper with a row of small colored blocks ending in a big dot, like a sentence made of blocks, no letters"),
    ("spell", "Spell", "concepts", "🔤", "Spell", ["spell", "letters", "write"], "a child arranging letter tiles"),
    ("read_word", "Read", "concepts", "📖", "Read", ["read", "book", "words"], "a child pointing at words in a book"),
    ("story", "Story", "concepts", "📚", "Story", ["story", "book", "tale"], "an open storybook with a castle popping up"),
    ("rhyme", "Rhyme", "concepts", "🎵", "Rhyme", ["rhyme", "poem", "song"], "a cat and a hat with music notes"),
    ("sound", "Sound", "concepts", "🔊", "Sound", ["sound", "hear", "noise"], "a speaker with sound waves"),
    ("silent", "Silent", "concepts", "🔇", "Silent", ["silent", "no sound", "mute"], "a speaker with a crossed-out sound wave"),
    ("pattern", "Pattern", "concepts", "🔁", "Pattern", ["pattern", "repeat", "sequence"], "a row of red blue red blue beads"),
    ("opposite", "Opposite", "concepts", "↔️", "Opposite", ["opposite", "different", "reverse"], "a big elephant and a tiny mouse with arrows pointing apart"),
    ("same_concept", "Same", "concepts", "🟰", "Same", ["same", "alike", "match"], "two identical red apples"),
    ("group", "Group", "concepts", "👥", "Group", ["group", "set", "together"], "three blue circles inside one dashed ring"),
    ("list", "List", "concepts", "📋", "List", ["list", "checklist", "items"], "a clipboard with a bulleted list"),
    ("chart", "Chart", "concepts", "📊", "Chart", ["chart", "graph", "bars"], "a colorful bar chart"),
    ("puzzle_piece", "Puzzle Piece", "concepts", "🧩", "Puzzle piece", ["puzzle piece", "fit", "piece"], "a single blue puzzle piece"),
    ("magnet_concept", "Magnet", "concepts", "🧲", "Magnet", ["magnet", "stick", "science"], "a red horseshoe magnet attracting paper clips"),
    ("gravity", "Gravity", "concepts", "🍎", "Gravity", ["gravity", "fall", "science"], "an apple falling from a tree with a down arrow"),
    ("float_sink", "Float or Sink", "concepts", "🛁", "Float or sink", ["float", "sink", "science"], "a cork floating and a rock sinking in water"),
    ("melt", "Melt", "concepts", "🫠", "Melt", ["melt", "ice", "hot"], "an ice cube melting into a puddle under a sun"),
    ("freeze", "Freeze", "concepts", "🧊", "Freeze", ["freeze", "ice", "cold"], "water turning into an ice cube with frost"),
    ("grow", "Grow", "concepts", "🌱", "Grow", ["grow", "bigger", "plant"], "a sprout, a small plant and a tall plant in a row"),
    ("shrink", "Shrink", "concepts", "🔽", "Shrink", ["shrink", "smaller"], "a big balloon, a medium balloon and a tiny balloon"),
    ("mix_colors", "Mix Colors", "concepts", "🎨", "Mix colors", ["mix colors", "blend", "paint"], "blue and yellow paint mixing into green"),
    ("light_dark", "Light and Dark", "concepts", "🌓", "Light and dark", ["light", "dark", "opposite"], "a room half lit by a lamp and half dark"),
    ("loud_soft", "Loud and Soft", "concepts", "🔊", "Loud and soft", ["loud", "soft", "volume"], "a big speaker with large waves and a small speaker with tiny waves"),
    ("wet_dry", "Wet and Dry", "concepts", "💧", "Wet and dry", ["wet", "dry", "opposite"], "a wet dripping towel and a dry folded towel"),
    ("push_pull", "Push and Pull", "concepts", "↔️", "Push and pull", ["push", "pull", "opposite"], "a child pushing a cart and a child pulling a wagon"),
    ("north", "North", "concepts", "🧭", "North", ["north", "direction", "compass"], "a compass with the N highlighted"),
    ("south", "South", "concepts", "🧭", "South", ["south", "direction", "compass"], "a compass with the S highlighted"),
    ("east", "East", "concepts", "🧭", "East", ["east", "direction", "sunrise"], "a compass with the E highlighted"),
    ("west", "West", "concepts", "🧭", "West", ["west", "direction", "sunset"], "a compass with the W highlighted"),
    ("usa", "USA", "concepts", "🇺🇸", "United States", ["usa", "america", "flag"], "an American flag waving"),
    ("ohio", "Ohio", "concepts", "🗺️", "Ohio", ["ohio", "state", "home"], "the outline shape of the state of Ohio with a small heart"),
    ("world", "World", "concepts", "🌎", "World", ["world", "globe", "countries"], "a globe on a stand"),
    ("flag", "Flag", "concepts", "🚩", "Flag", ["flag", "wave", "pole"], "a red flag on a pole"),

    # --- colors / shapes --------------------------------------------------------
    ("light_blue", "Light Blue", "colors", "🩵", "Light blue", ["light blue", "sky blue", "color"], "a light sky-blue paint splat"),
    ("dark_blue", "Dark Blue", "colors", "🔵", "Dark blue", ["dark blue", "navy", "color"], "a dark navy blue paint splat"),
    ("light_green", "Light Green", "colors", "💚", "Light green", ["light green", "lime", "color"], "a light lime green paint splat"),
    ("dark_green", "Dark Green", "colors", "🟢", "Dark green", ["dark green", "forest green", "color"], "a dark forest green paint splat"),
    ("turquoise", "Turquoise", "colors", "🩵", "Turquoise", ["turquoise", "teal", "color"], "a bright turquoise paint splat"),
    ("magenta", "Magenta", "colors", "🩷", "Magenta", ["magenta", "hot pink", "color"], "a bright magenta paint splat"),
    ("lavender", "Lavender", "colors", "💜", "Lavender", ["lavender", "light purple", "color"], "a soft lavender paint splat"),
    ("peach_color", "Peach", "colors", "🍑", "Peach", ["peach", "color", "light orange"], "a soft peach-colored paint splat"),
    ("tan", "Tan", "colors", "🟤", "Tan", ["tan", "beige", "color"], "a tan beige paint splat"),
    ("gold", "Gold", "colors", "🥇", "Gold", ["gold", "shiny", "color"], "a shiny metallic gold paint splat"),
    ("silver", "Silver", "colors", "🥈", "Silver", ["silver", "shiny", "color"], "a shiny metallic silver paint splat"),
    ("rainbow_color", "Rainbow", "colors", "🌈", "Rainbow colors", ["rainbow", "all colors", "colorful"], "a paint splat with rainbow stripes"),
    ("clear", "Clear", "colors", "🫧", "Clear", ["clear", "see through", "transparent"], "a clear glass of water you can see through"),
    ("dark_color", "Dark", "colors", "⚫", "Dark", ["dark", "black", "night"], "a dark navy and black paint splat next to a moon"),
    ("light_color", "Light", "colors", "⚪", "Light", ["light", "pale", "bright"], "a pale white and cream paint splat next to a sun"),
    ("oval", "Oval", "colors", "🥚", "Oval", ["oval", "shape", "egg"], "a big blue oval shape"),
    ("rectangle", "Rectangle", "colors", "▭", "Rectangle", ["rectangle", "shape"], "a big green rectangle shape"),
    ("diamond", "Diamond", "colors", "🔷", "Diamond", ["diamond", "shape", "rhombus"], "a big blue diamond shape"),
    ("pentagon", "Pentagon", "colors", "⬠", "Pentagon", ["pentagon", "shape", "five sides"], "a big purple pentagon shape"),
    ("hexagon", "Hexagon", "colors", "⬡", "Hexagon", ["hexagon", "shape", "six sides"], "a big orange hexagon shape"),
    ("octagon", "Octagon", "colors", "🛑", "Octagon", ["octagon", "shape", "eight sides"], "a big red octagon shape"),
    ("crescent", "Crescent", "colors", "🌙", "Crescent", ["crescent", "shape", "moon"], "a big yellow crescent shape"),
    ("arrow", "Arrow", "colors", "➡️", "Arrow", ["arrow", "shape", "point"], "a big red arrow shape pointing right"),
    ("cross_shape", "Cross", "colors", "➕", "Cross", ["cross", "plus", "shape"], "a big green plus cross shape"),
    ("cube", "Cube", "colors", "🧊", "Cube", ["cube", "3d", "box"], "a blue 3D cube"),
    ("sphere", "Sphere", "colors", "⚽", "Sphere", ["sphere", "ball", "3d"], "a red 3D sphere"),
    ("cone", "Cone", "colors", "🍦", "Cone", ["cone", "3d", "shape"], "an orange 3D cone"),
    ("cylinder", "Cylinder", "colors", "🥫", "Cylinder", ["cylinder", "can", "3d"], "a green 3D cylinder"),
    ("pyramid", "Pyramid", "colors", "🔺", "Pyramid", ["pyramid", "3d", "triangle"], "a yellow 3D pyramid"),
    ("line", "Line", "colors", "📏", "Line", ["line", "straight", "draw"], "a straight thick blue line"),
    ("dot", "Dot", "colors", "⚫", "Dot", ["dot", "point", "spot"], "a single big black dot"),
    ("curve", "Curve", "colors", "〰️", "Curve", ["curve", "wavy", "bend"], "a thick curved blue line"),
    ("zigzag", "Zigzag", "colors", "⚡", "Zigzag", ["zigzag", "jagged", "line"], "a thick zigzag orange line"),
    ("spiral", "Spiral", "colors", "🌀", "Spiral", ["spiral", "swirl", "twist"], "a thick purple spiral"),
    ("stripes", "Stripes", "colors", "🦓", "Stripes", ["stripes", "striped", "pattern"], "a square with bold red and white stripes"),
    ("polka_dots", "Polka Dots", "colors", "🔴", "Polka dots", ["polka dots", "dots", "pattern"], "a square with blue polka dots on white"),
    ("plaid", "Plaid", "colors", "🟥", "Plaid", ["plaid", "checkered", "pattern"], "a square with a red and green plaid pattern"),
    ("checkered", "Checkered", "colors", "🏁", "Checkered", ["checkered", "checkerboard", "pattern"], "a black and white checkerboard square"),
    ("big_shape", "Big", "colors", "⬛", "Big", ["big", "large", "size"], "a huge red circle next to a tiny red circle, arrow at the huge one"),
    ("small_shape", "Small", "colors", "▪️", "Small", ["small", "little", "size"], "a huge red circle next to a tiny red circle, arrow at the tiny one"),
    ("medium", "Medium", "colors", "🔶", "Medium", ["medium", "middle size"], "three circles small medium and large with an arrow at the middle one"),
    ("thick", "Thick", "colors", "📕", "Thick", ["thick", "fat", "wide"], "a thick book next to a thin book, arrow at the thick one"),
    ("thin", "Thin", "colors", "📄", "Thin", ["thin", "skinny", "narrow"], "a thick book next to a thin book, arrow at the thin one"),
    ("wide", "Wide", "colors", "↔️", "Wide", ["wide", "broad"], "a wide rectangle with a double-ended arrow across it"),
    ("narrow", "Narrow", "colors", "↕️", "Narrow", ["narrow", "skinny", "tight"], "a tall narrow rectangle with a small double-ended arrow across it"),
    ("round", "Round", "colors", "⭕", "Round", ["round", "circle", "ball"], "a round orange ball"),
    ("flat", "Flat", "colors", "▬", "Flat", ["flat", "level", "even"], "a flat pancake on a plate"),
    ("bumpy", "Bumpy", "colors", "🟤", "Bumpy", ["bumpy", "lumpy", "rough"], "a bumpy brown surface with lumps"),
    ("shiny", "Shiny", "colors", "✨", "Shiny", ["shiny", "sparkle", "glossy"], "a shiny gold star with sparkles"),
    ("dull", "Dull", "colors", "🪨", "Dull", ["dull", "not shiny", "plain"], "a plain matte gray rock"),
    ("bright", "Bright", "colors", "🌟", "Bright", ["bright", "vivid", "glowing"], "a bright glowing yellow lightbulb"),
    ("dim", "Dim", "colors", "🔅", "Dim", ["dim", "faint", "low light"], "a dim, barely glowing lightbulb"),
    ("colorful", "Colorful", "colors", "🌈", "Colorful", ["colorful", "many colors", "rainbow"], "a burst of many colored paint splats"),
    ("plain", "Plain", "colors", "⬜", "Plain", ["plain", "simple", "no pattern"], "a plain white t-shirt"),
    ("fancy", "Fancy", "colors", "💎", "Fancy", ["fancy", "dressy", "sparkly"], "a sparkly dress with a bow tie"),
]
