# Expansion set 3 (2026-09-13): food, drinks, actions.

EXTRA3 = [
    # --- food -------------------------------------------------------------------
    ("spaghetti", "Spaghetti", "food", "🍝", "Spaghetti", ["spaghetti", "noodles", "pasta"], "a plate of spaghetti with red sauce and a meatball"),
    ("noodles", "Noodles", "food", "🍜", "Noodles", ["noodles", "ramen", "bowl"], "a bowl of noodles with chopsticks"),
    ("quesadilla", "Quesadilla", "food", "🫓", "Quesadilla", ["quesadilla", "cheese", "tortilla"], "a folded quesadilla cut into wedges with melted cheese"),
    ("steak", "Steak", "food", "🥩", "Steak", ["steak", "meat", "beef"], "a grilled steak on a plate with grill marks"),
    ("ham", "Ham", "food", "🍖", "Ham", ["ham", "meat", "pork"], "slices of pink ham on a plate"),
    ("bacon", "Bacon", "food", "🥓", "Bacon", ["bacon", "breakfast", "meat"], "three crispy strips of bacon"),
    ("sausage", "Sausage", "food", "🌭", "Sausage", ["sausage", "breakfast", "meat"], "two brown sausage links on a plate"),
    ("fish_food", "Fish", "food", "🐟", "Fish", ["fish", "fish sticks", "seafood"], "a plate of golden fish sticks with a lemon wedge"),
    ("shrimp", "Shrimp", "food", "🍤", "Shrimp", ["shrimp", "seafood"], "three cooked pink shrimp on a plate"),
    ("turkey_food", "Turkey", "food", "🦃", "Turkey", ["turkey", "meat", "thanksgiving"], "a roasted turkey on a platter"),
    ("meatballs", "Meatballs", "food", "🧆", "Meatballs", ["meatballs", "meat", "dinner"], "a bowl of meatballs in red sauce"),
    ("tofu", "Tofu", "food", "🧊", "Tofu", ["tofu", "vegetarian"], "white tofu cubes in a bowl"),
    ("beans", "Beans", "food", "🫘", "Beans", ["beans", "vegetables"], "a bowl of brown beans"),
    ("peas", "Peas", "food", "🟢", "Peas", ["peas", "vegetables", "green"], "a bowl of bright green peas with an open pea pod"),
    ("green_beans", "Green Beans", "food", "🥬", "Green beans", ["green beans", "vegetables"], "a pile of green beans on a plate"),
    ("potato", "Potato", "food", "🥔", "Potato", ["potato", "vegetables"], "a brown baked potato split open with butter"),
    ("mashed_potatoes", "Mashed Potatoes", "food", "🥣", "Mashed potatoes", ["mashed potatoes", "potatoes", "dinner"], "a mound of mashed potatoes with a pat of butter"),
    ("sweet_potato", "Sweet Potato", "food", "🍠", "Sweet potato", ["sweet potato", "yam"], "an orange sweet potato cut open"),
    ("tomato", "Tomato", "food", "🍅", "Tomato", ["tomato", "vegetables"], "a shiny red tomato with a green stem"),
    ("cucumber", "Cucumber", "food", "🥒", "Cucumber", ["cucumber", "vegetables"], "a green cucumber with a few round slices"),
    ("lettuce", "Lettuce", "food", "🥬", "Lettuce", ["lettuce", "salad", "greens"], "a head of green lettuce"),
    ("spinach", "Spinach", "food", "🌿", "Spinach", ["spinach", "greens"], "a bowl of green spinach leaves"),
    ("pepper", "Bell Pepper", "food", "🫑", "Bell pepper", ["pepper", "bell pepper", "vegetables"], "a red and a green bell pepper side by side"),
    ("onion", "Onion", "food", "🧅", "Onion", ["onion", "vegetables"], "a whole brown onion with a cut half"),
    ("mushroom", "Mushroom", "food", "🍄", "Mushroom", ["mushroom", "vegetables"], "two brown button mushrooms"),
    ("cauliflower", "Cauliflower", "food", "🥦", "Cauliflower", ["cauliflower", "vegetables"], "a white head of cauliflower with green leaves"),
    ("celery", "Celery", "food", "🥬", "Celery", ["celery", "vegetables", "snack"], "three green celery sticks"),
    ("avocado", "Avocado", "food", "🥑", "Avocado", ["avocado", "guacamole"], "a halved avocado with the pit"),
    ("pumpkin_food", "Pumpkin", "food", "🎃", "Pumpkin", ["pumpkin", "fall", "pie"], "a round orange pumpkin"),
    ("squash", "Squash", "food", "🥒", "Squash", ["squash", "zucchini", "vegetables"], "a yellow squash and a green zucchini"),
    ("pear", "Pear", "food", "🍐", "Pear", ["pear", "fruit"], "a green pear with a leaf"),
    ("peach", "Peach", "food", "🍑", "Peach", ["peach", "fruit"], "a fuzzy orange-pink peach with a leaf"),
    ("plum", "Plum", "food", "🟣", "Plum", ["plum", "fruit"], "a shiny purple plum"),
    ("cherries", "Cherries", "food", "🍒", "Cherries", ["cherries", "fruit"], "two red cherries joined at the stem"),
    ("blueberries", "Blueberries", "food", "🫐", "Blueberries", ["blueberries", "berries", "fruit"], "a small bowl of round blueberries"),
    ("raspberries", "Raspberries", "food", "🍇", "Raspberries", ["raspberries", "berries", "fruit"], "a small pile of red raspberries"),
    ("mango", "Mango", "food", "🥭", "Mango", ["mango", "fruit"], "a yellow-orange mango with a cut slice showing cubes"),
    ("kiwi", "Kiwi", "food", "🥝", "Kiwi", ["kiwi", "fruit"], "a brown kiwi with a bright green sliced half"),
    ("lemon", "Lemon", "food", "🍋", "Lemon", ["lemon", "sour", "fruit"], "a yellow lemon with a cut wedge"),
    ("lime", "Lime", "food", "🍈", "Lime", ["lime", "sour", "fruit"], "a green lime with a cut wedge"),
    ("melon", "Melon", "food", "🍈", "Melon", ["melon", "cantaloupe", "fruit"], "a cantaloupe with an orange wedge cut out"),
    ("coconut", "Coconut", "food", "🥥", "Coconut", ["coconut", "fruit"], "a brown coconut split open showing white inside"),
    ("raisins", "Raisins", "food", "🟤", "Raisins", ["raisins", "snack", "dried fruit"], "a small red box of raisins with a few spilled out"),
    ("applesauce", "Applesauce", "food", "🍎", "Applesauce", ["applesauce", "snack"], "a small cup of applesauce with a spoon and an apple beside it"),
    ("fruit_snacks", "Fruit Snacks", "food", "🍬", "Fruit snacks", ["fruit snacks", "gummies", "snack"], "a small pouch of colorful gummy fruit snacks"),
    ("granola_bar", "Granola Bar", "food", "🍫", "Granola bar", ["granola bar", "snack", "bar"], "a granola bar half out of its wrapper"),
    ("pretzels", "Pretzels", "food", "🥨", "Pretzels", ["pretzels", "snack", "salty"], "a bowl of twisted brown pretzels"),
    ("goldfish", "Goldfish Crackers", "food", "🐠", "Goldfish crackers", ["goldfish", "crackers", "snack"], "orange fish-shaped crackers spilling from a bag"),
    ("cheese_stick", "Cheese Stick", "food", "🧀", "Cheese stick", ["cheese stick", "string cheese", "snack"], "a string cheese stick half unwrapped"),
    ("trail_mix", "Trail Mix", "food", "🥜", "Trail mix", ["trail mix", "nuts", "snack"], "a bowl of nuts, raisins and chocolate pieces"),
    ("rice_cake", "Rice Cake", "food", "🍘", "Rice cake", ["rice cake", "snack"], "a round white puffed rice cake"),
    ("veggie_sticks", "Veggie Sticks", "food", "🥕", "Veggie sticks", ["veggie sticks", "carrots", "snack"], "carrot and celery sticks in a cup with dip"),
    ("dip", "Dip", "food", "🫕", "Dip", ["dip", "ranch", "hummus"], "a small bowl of creamy dip with a carrot stick in it"),
    ("hummus", "Hummus", "food", "🥣", "Hummus", ["hummus", "dip"], "a bowl of tan hummus with pita wedges"),
    ("ketchup", "Ketchup", "food", "🍅", "Ketchup", ["ketchup", "sauce", "condiment"], "a red squeeze bottle of ketchup"),
    ("mustard", "Mustard", "food", "🟡", "Mustard", ["mustard", "sauce", "condiment"], "a yellow squeeze bottle of mustard"),
    ("mayo", "Mayo", "food", "⚪", "Mayo", ["mayo", "mayonnaise", "condiment"], "a white jar of mayonnaise with a spoon"),
    ("ranch", "Ranch", "food", "🥛", "Ranch", ["ranch", "dressing", "dip"], "a bottle of ranch dressing next to a salad"),
    ("syrup", "Syrup", "food", "🍯", "Syrup", ["syrup", "pancakes", "sweet"], "a bottle of syrup pouring onto pancakes"),
    ("honey", "Honey", "food", "🍯", "Honey", ["honey", "sweet", "bee"], "a jar of golden honey with a wooden dipper"),
    ("jam", "Jam", "food", "🍓", "Jam", ["jam", "jelly", "spread"], "a jar of red strawberry jam with a spoon"),
    ("butter", "Butter", "food", "🧈", "Butter", ["butter", "spread"], "a yellow stick of butter on a dish"),
    ("salt", "Salt", "food", "🧂", "Salt", ["salt", "seasoning"], "a salt shaker"),
    ("sugar", "Sugar", "food", "🍚", "Sugar", ["sugar", "sweet"], "a bowl of white sugar with a spoon"),
    ("sauce", "Sauce", "food", "🥫", "Sauce", ["sauce", "gravy"], "a small pitcher pouring brown sauce"),
    ("bagel", "Bagel", "food", "🥯", "Bagel", ["bagel", "breakfast", "bread"], "a bagel cut in half with cream cheese"),
    ("croissant", "Croissant", "food", "🥐", "Croissant", ["croissant", "pastry", "breakfast"], "a golden flaky croissant"),
    ("biscuit", "Biscuit", "food", "🍪", "Biscuit", ["biscuit", "bread", "roll"], "a fluffy golden biscuit split open"),
    ("roll", "Dinner Roll", "food", "🍞", "Roll", ["roll", "bread", "bun"], "a round golden dinner roll"),
    ("tortilla", "Tortilla", "food", "🫓", "Tortilla", ["tortilla", "wrap", "bread"], "a stack of round flour tortillas"),
    ("pita", "Pita", "food", "🫓", "Pita", ["pita", "bread"], "a round pita bread cut in half showing the pocket"),
    ("oatmeal", "Oatmeal", "food", "🥣", "Oatmeal", ["oatmeal", "porridge", "breakfast"], "a bowl of oatmeal with a few blueberries and a spoon"),
    ("french_toast", "French Toast", "food", "🍞", "French toast", ["french toast", "breakfast"], "two slices of french toast with syrup and powdered sugar"),
    ("omelet", "Omelet", "food", "🍳", "Omelet", ["omelet", "eggs", "breakfast"], "a folded yellow omelet on a plate"),
    ("scrambled_eggs", "Scrambled Eggs", "food", "🍳", "Scrambled eggs", ["scrambled eggs", "eggs", "breakfast"], "a plate of fluffy yellow scrambled eggs"),
    ("hash_browns", "Hash Browns", "food", "🥔", "Hash browns", ["hash browns", "potatoes", "breakfast"], "golden crispy hash browns on a plate"),
    ("pie", "Pie", "food", "🥧", "Pie", ["pie", "dessert"], "a whole pie with a lattice crust and one slice cut"),
    ("brownie", "Brownie", "food", "🟫", "Brownie", ["brownie", "chocolate", "dessert"], "a square chocolate brownie"),
    ("pudding", "Pudding", "food", "🍮", "Pudding", ["pudding", "dessert"], "a cup of chocolate pudding with a spoon"),
    ("jello", "Jello", "food", "🟥", "Jello", ["jello", "gelatin", "dessert"], "a wobbly red jello in a cup"),
    ("popsicle", "Popsicle", "food", "🍧", "Popsicle", ["popsicle", "ice pop", "frozen"], "an orange popsicle on a wooden stick"),
    ("lollipop", "Lollipop", "food", "🍭", "Lollipop", ["lollipop", "candy", "sucker"], "a big swirl lollipop on a stick"),
    ("marshmallow", "Marshmallow", "food", "☁️", "Marshmallow", ["marshmallow", "sweet"], "three white fluffy marshmallows"),
    ("gummy_bears", "Gummy Bears", "food", "🐻", "Gummy bears", ["gummy bears", "candy"], "colorful gummy bears in a pile"),
    ("cotton_candy", "Cotton Candy", "food", "🍥", "Cotton candy", ["cotton candy", "fair", "sweet"], "pink fluffy cotton candy on a stick"),
    ("birthday_cake", "Birthday Cake", "food", "🎂", "Birthday cake", ["birthday cake", "cake", "candles"], "a layered birthday cake with lit candles"),
    ("sundae", "Ice Cream Sundae", "food", "🍨", "Ice cream sundae", ["sundae", "ice cream", "dessert"], "an ice cream sundae with chocolate sauce and a cherry"),
    ("frozen_yogurt", "Frozen Yogurt", "food", "🍦", "Frozen yogurt", ["frozen yogurt", "froyo", "dessert"], "a cup of swirled frozen yogurt with sprinkles"),
    ("sprinkles", "Sprinkles", "food", "🌈", "Sprinkles", ["sprinkles", "topping"], "a shaker of rainbow sprinkles pouring out"),
    ("whipped_cream", "Whipped Cream", "food", "🍦", "Whipped cream", ["whipped cream", "topping"], "a can of whipped cream with a swirl on top of a dessert"),
    ("chili", "Chili", "food", "🌶️", "Chili", ["chili", "soup", "dinner"], "a bowl of red bean chili with shredded cheese"),
    ("stew", "Stew", "food", "🍲", "Stew", ["stew", "dinner", "soup"], "a bowl of chunky beef stew with vegetables"),
    ("chicken_soup", "Chicken Soup", "food", "🍜", "Chicken soup", ["chicken soup", "soup", "sick"], "a bowl of chicken noodle soup with steam"),
    ("tomato_soup", "Tomato Soup", "food", "🥣", "Tomato soup", ["tomato soup", "soup"], "a bowl of red tomato soup with a grilled cheese beside it"),
    ("casserole", "Casserole", "food", "🥘", "Casserole", ["casserole", "dinner"], "a baked casserole in a rectangular dish"),
    ("lasagna", "Lasagna", "food", "🍝", "Lasagna", ["lasagna", "pasta", "dinner"], "a square slice of layered lasagna"),
    ("ravioli", "Ravioli", "food", "🥟", "Ravioli", ["ravioli", "pasta"], "a plate of square ravioli with red sauce"),
    ("dumplings", "Dumplings", "food", "🥟", "Dumplings", ["dumplings", "potstickers"], "three dumplings in a bamboo steamer"),
    ("sushi", "Sushi", "food", "🍣", "Sushi", ["sushi", "rice", "fish"], "three sushi rolls on a plate with chopsticks"),
    ("fried_rice", "Fried Rice", "food", "🍚", "Fried rice", ["fried rice", "rice", "chinese"], "a bowl of fried rice with egg and peas"),
    ("stir_fry", "Stir Fry", "food", "🥡", "Stir fry", ["stir fry", "vegetables", "dinner"], "a pan of colorful stir-fried vegetables"),
    ("curry", "Curry", "food", "🍛", "Curry", ["curry", "rice", "dinner"], "a plate of rice with orange curry"),
    ("enchiladas", "Enchiladas", "food", "🌯", "Enchiladas", ["enchiladas", "mexican", "dinner"], "two rolled enchiladas with red sauce and cheese"),
    ("nachos", "Nachos", "food", "🧀", "Nachos", ["nachos", "chips", "cheese"], "a plate of tortilla chips covered in melted cheese"),
    ("chicken_wings", "Chicken Wings", "food", "🍗", "Chicken wings", ["wings", "chicken"], "a plate of orange chicken wings"),
    ("fried_chicken", "Fried Chicken", "food", "🍗", "Fried chicken", ["fried chicken", "chicken", "drumstick"], "a crispy fried chicken drumstick"),
    ("pork_chop", "Pork Chop", "food", "🥩", "Pork chop", ["pork chop", "meat"], "a grilled pork chop on a plate"),
    ("meatloaf", "Meatloaf", "food", "🍖", "Meatloaf", ["meatloaf", "dinner"], "a sliced meatloaf with ketchup glaze"),
    ("sloppy_joe", "Sloppy Joe", "food", "🍔", "Sloppy joe", ["sloppy joe", "sandwich"], "a bun overflowing with saucy ground beef"),
    ("blt", "BLT", "food", "🥪", "B L T", ["blt", "bacon", "sandwich"], "a sandwich with bacon, lettuce and tomato cut diagonally"),
    ("pbj", "PB&J", "food", "🥪", "Peanut butter and jelly", ["pbj", "peanut butter and jelly", "sandwich"], "a peanut butter and jelly sandwich cut in half"),
    ("turkey_sandwich", "Turkey Sandwich", "food", "🥪", "Turkey sandwich", ["turkey sandwich", "sandwich", "lunch"], "a turkey sandwich with lettuce on wheat bread"),
    ("wrap_food", "Wrap", "food", "🌯", "Wrap", ["wrap", "tortilla", "lunch"], "a rolled tortilla wrap cut in half showing filling"),
    ("corn_dog", "Corn Dog", "food", "🌭", "Corn dog", ["corn dog", "fair"], "a golden corn dog on a stick with mustard"),
    ("pizza_slice", "Pizza Slice", "food", "🍕", "Pizza slice", ["pizza slice", "slice", "pizza"], "a single triangular slice of pepperoni pizza"),
    ("garlic_bread", "Garlic Bread", "food", "🥖", "Garlic bread", ["garlic bread", "bread"], "slices of golden garlic bread"),
    ("breadsticks", "Breadsticks", "food", "🥖", "Breadsticks", ["breadsticks", "bread"], "a basket of breadsticks"),
    ("baked_beans", "Baked Beans", "food", "🫘", "Baked beans", ["baked beans", "beans"], "a bowl of brown baked beans"),
    ("coleslaw", "Coleslaw", "food", "🥗", "Coleslaw", ["coleslaw", "salad", "side"], "a bowl of creamy coleslaw"),
    ("fruit_salad", "Fruit Salad", "food", "🍓", "Fruit salad", ["fruit salad", "fruit"], "a bowl of mixed fruit salad"),
    ("fruit_cup", "Fruit Cup", "food", "🍑", "Fruit cup", ["fruit cup", "snack"], "a small plastic cup of fruit pieces in juice"),
    ("leftovers", "Leftovers", "food", "🍱", "Leftovers", ["leftovers", "reheat", "container"], "a plastic container with leftover food and a lid"),
    ("dessert", "Dessert", "food", "🍰", "Dessert", ["dessert", "sweet", "treat"], "a slice of cake, a cookie and a scoop of ice cream together"),
    ("treat", "Treat", "food", "🍬", "Treat", ["treat", "reward", "candy"], "a child receiving a wrapped candy with a happy face"),
    ("seconds", "Seconds", "food", "🍽️", "I want seconds", ["seconds", "more food", "another plate"], "a child holding out an empty plate toward a pot with a plus sign"),
    ("bite", "Bite", "food", "😬", "Take a bite", ["bite", "taste", "try"], "a child taking one bite of an apple with a bite missing"),
    ("taste", "Taste", "food", "👅", "Taste it", ["taste", "try", "lick"], "a child tasting a spoonful of soup"),
    ("chew", "Chew", "food", "🦷", "Chew", ["chew", "eat", "teeth"], "a child chewing with puffed cheeks"),
    ("swallow", "Swallow", "food", "😮", "Swallow", ["swallow", "gulp"], "a child swallowing with a hand on their throat"),
    ("spit_out", "Spit It Out", "food", "🤮", "Spit it out", ["spit out", "yuck", "don't eat"], "a child spitting food out into a napkin"),
    ("too_spicy", "Too Spicy", "food", "🌶️", "Too spicy", ["spicy", "hot", "burn"], "a red-faced child with a tongue out and a chili pepper"),
    ("too_sweet", "Too Sweet", "food", "🍬", "Too sweet", ["sweet", "sugary"], "a child grimacing at a huge pile of candy"),
    ("sour", "Sour", "food", "🍋", "Sour", ["sour", "lemon", "pucker"], "a child puckering their face after biting a lemon"),
    ("salty", "Salty", "food", "🧂", "Salty", ["salty", "salt"], "a child eating a pretzel with a salt shaker beside"),
    ("crunchy", "Crunchy", "food", "🥕", "Crunchy", ["crunchy", "crisp"], "a child biting a carrot with crunch lines"),
    ("mushy", "Mushy", "food", "🥣", "Mushy", ["mushy", "soft", "smooth"], "a bowl of smooth mashed food with a spoon"),
    ("cold_food", "Cold Food", "food", "🧊", "It's cold", ["cold food", "cold", "not warm"], "a plate of food with ice cubes and blue frost lines"),
    ("hot_food", "Hot Food", "food", "♨️", "It's hot", ["hot food", "hot", "careful"], "a plate of food with steam rising and a warning"),
    ("warm_it_up", "Warm It Up", "food", "🔥", "Warm it up", ["warm up", "heat", "microwave"], "a plate of food going into a microwave"),
    ("cut_it_up", "Cut It Up", "food", "🔪", "Cut it up", ["cut up", "small pieces", "knife"], "an adult cutting food into small pieces on a plate"),
    ("grocery", "Groceries", "food", "🛒", "Groceries", ["groceries", "shopping", "food"], "a paper grocery bag full of food"),
    ("menu", "Menu", "food", "📋", "Menu", ["menu", "restaurant", "order"], "an open restaurant menu with pictures of food"),
    ("order_food", "Order", "food", "🧾", "I want to order", ["order", "restaurant", "waiter"], "a child pointing at a menu while a waiter writes"),
    ("drive_thru", "Drive Thru", "food", "🚗", "Drive thru", ["drive thru", "fast food"], "a car at a drive-thru window receiving a bag"),
    ("picnic", "Picnic", "food", "🧺", "Picnic", ["picnic", "outside", "basket"], "a picnic basket and blanket with food on grass"),

    # --- drinks -----------------------------------------------------------------
    ("grape_juice", "Grape Juice", "drinks", "🍇", "Grape juice", ["grape juice", "juice", "purple"], "a glass of purple grape juice with grapes"),
    ("cranberry_juice", "Cranberry Juice", "drinks", "🔴", "Cranberry juice", ["cranberry juice", "juice"], "a glass of red cranberry juice"),
    ("fruit_punch", "Fruit Punch", "drinks", "🧃", "Fruit punch", ["fruit punch", "punch", "juice"], "a red fruit punch in a cup with a straw"),
    ("sports_drink", "Sports Drink", "drinks", "🏃", "Sports drink", ["sports drink", "gatorade", "electrolytes"], "a blue sports drink bottle"),
    ("sparkling_water", "Sparkling Water", "drinks", "🫧", "Sparkling water", ["sparkling water", "fizzy", "bubbles"], "a glass of water with rising bubbles"),
    ("coffee", "Coffee", "drinks", "☕", "Coffee", ["coffee", "hot drink"], "a mug of hot coffee with steam"),
    ("iced_coffee", "Iced Coffee", "drinks", "🧋", "Iced coffee", ["iced coffee", "cold coffee"], "a clear cup of iced coffee with a straw"),
    ("iced_tea", "Iced Tea", "drinks", "🥤", "Iced tea", ["iced tea", "tea", "cold"], "a tall glass of iced tea with a lemon slice"),
    ("bubble_tea", "Bubble Tea", "drinks", "🧋", "Bubble tea", ["bubble tea", "boba"], "a cup of bubble tea with tapioca pearls and a wide straw"),
    ("slushie", "Slushie", "drinks", "🥤", "Slushie", ["slushie", "icee", "frozen drink"], "a blue frozen slushie in a cup with a dome lid"),
    ("root_beer", "Root Beer", "drinks", "🍺", "Root beer", ["root beer", "soda"], "a frosty mug of root beer with foam"),
    ("kombucha", "Kombucha", "drinks", "🍵", "Kombucha", ["kombucha", "fizzy"], "a bottle of amber kombucha"),
    ("protein_shake", "Protein Shake", "drinks", "🥤", "Protein shake", ["protein shake", "shake"], "a shaker bottle with a chocolate shake"),
    ("formula", "Formula", "drinks", "🍼", "Formula", ["formula", "bottle", "baby"], "a baby bottle of formula with a can beside it"),
    ("breast_milk", "Milk Bottle", "drinks", "🍼", "Bottle", ["bottle", "baby", "milk"], "a baby bottle full of milk"),
    ("almond_milk", "Almond Milk", "drinks", "🌰", "Almond milk", ["almond milk", "milk"], "a carton of almond milk with almonds"),
    ("strawberry_milk", "Strawberry Milk", "drinks", "🍓", "Strawberry milk", ["strawberry milk", "milk", "pink"], "a glass of pink strawberry milk with a straw"),
    ("warm_milk", "Warm Milk", "drinks", "🥛", "Warm milk", ["warm milk", "milk", "bedtime"], "a mug of warm milk with steam and a moon"),
    ("cup_of_water", "Cup of Water", "drinks", "🥛", "Cup of water", ["cup of water", "water", "cup"], "a clear cup filled with water"),
    ("water_bottle", "Water Bottle", "drinks", "🍶", "Water bottle", ["water bottle", "bottle", "water"], "a reusable blue water bottle"),
    ("sippy_cup", "Sippy Cup", "drinks", "🥤", "Sippy cup", ["sippy cup", "cup", "toddler"], "a colorful sippy cup with handles"),
    ("thermos", "Thermos", "drinks", "🫗", "Thermos", ["thermos", "bottle", "hot"], "a metal thermos with a cup lid"),
    ("ice", "Ice", "drinks", "🧊", "Ice", ["ice", "ice cubes", "cold"], "three ice cubes"),
    ("no_ice", "No Ice", "drinks", "🚫", "No ice", ["no ice", "without ice"], "a cup of water with ice cubes crossed out"),
    ("refill", "Refill", "drinks", "🔄", "Refill please", ["refill", "more", "fill up"], "a pitcher pouring into an empty cup"),
    ("sip", "Sip", "drinks", "😗", "Take a sip", ["sip", "drink", "small drink"], "a child taking a small sip from a cup"),
    ("thick_drink", "Thickened Drink", "drinks", "🥤", "Thick drink", ["thickened", "thick", "nectar"], "a cup with a thick honey-like liquid and a spoon"),
    ("open_it", "Open It", "drinks", "🔓", "Open it please", ["open it", "open", "lid"], "a child struggling with a juice box straw, asking for help"),

    # --- actions ----------------------------------------------------------------
    ("skip", "Skip", "actions", "🦘", "Skip", ["skip", "hop", "bounce"], "a child skipping happily with one leg up"),
    ("hop", "Hop", "actions", "🐇", "Hop", ["hop", "jump", "bunny"], "a child hopping on both feet like a bunny"),
    ("crawl", "Crawl", "actions", "🐛", "Crawl", ["crawl", "hands and knees"], "a child crawling on hands and knees"),
    ("roll_actions", "Roll", "actions", "🌀", "Roll", ["roll", "roll over", "tumble"], "a child rolling sideways on a mat"),
    ("spin", "Spin", "actions", "🌪️", "Spin", ["spin", "twirl", "turn"], "a child twirling with arms out and a circular motion line"),
    ("stretch", "Stretch", "actions", "🙆", "Stretch", ["stretch", "reach", "exercise"], "a child stretching arms up high"),
    ("bend", "Bend", "actions", "🙇", "Bend", ["bend", "bend over", "touch toes"], "a child bending down to touch their toes"),
    ("balance", "Balance", "actions", "🤸", "Balance", ["balance", "one foot", "steady"], "a child balancing on one foot with arms out"),
    ("march", "March", "actions", "🥁", "March", ["march", "walk", "parade"], "a child marching with knees high"),
    ("tiptoe", "Tiptoe", "actions", "🤫", "Tiptoe", ["tiptoe", "sneak", "quiet"], "a child sneaking on tiptoes"),
    ("clap", "Clap", "actions", "👏", "Clap", ["clap", "applause", "hands"], "a child clapping hands with motion lines"),
    ("wave", "Wave", "actions", "👋", "Wave", ["wave", "hello", "bye"], "a child waving one hand"),
    ("point", "Point", "actions", "👉", "Point", ["point", "show", "finger"], "a child pointing with one finger"),
    ("nod", "Nod", "actions", "🙂", "Nod yes", ["nod", "yes", "head"], "a child nodding with up-down motion arrows"),
    ("shake_head", "Shake Head", "actions", "🙂‍↔️", "Shake head no", ["shake head", "no", "head"], "a child shaking their head with side-to-side motion arrows"),
    ("blow", "Blow", "actions", "🌬️", "Blow", ["blow", "breathe out", "candles"], "a child blowing out birthday candles"),
    ("breathe", "Breathe", "actions", "😮‍💨", "Take a deep breath", ["breathe", "deep breath", "calm"], "a child with eyes closed taking a slow deep breath, gentle air swirls"),
    ("whisper", "Whisper", "actions", "🤫", "Whisper", ["whisper", "quiet voice"], "a child whispering behind a hand"),
    ("shout", "Shout", "actions", "📣", "Shout", ["shout", "yell", "loud"], "a child shouting with hands cupped around the mouth"),
    ("scream", "Scream", "actions", "😱", "Scream", ["scream", "yell", "loud"], "a child screaming with wide open mouth and sound lines"),
    ("hum", "Hum", "actions", "🎶", "Hum", ["hum", "sing", "music"], "a child with closed mouth and music notes floating"),
    ("wiggle", "Wiggle", "actions", "🐍", "Wiggle", ["wiggle", "squirm", "move"], "a child wiggling with wavy motion lines"),
    ("squeeze", "Squeeze", "actions", "🤏", "Squeeze", ["squeeze", "press", "stress ball"], "a child squeezing a soft stress ball"),
    ("rock", "Rock", "actions", "🪑", "Rock", ["rock", "rocking", "sway"], "a child rocking gently in a rocking chair"),
    ("swing_act", "Swing", "actions", "🎢", "Swing", ["swing", "back and forth"], "a child swinging on a swing"),
    ("bounce", "Bounce", "actions", "⛹️", "Bounce", ["bounce", "ball", "jump"], "a child bouncing a red ball"),
    ("slide_act", "Slide", "actions", "🛝", "Slide", ["slide", "go down"], "a child sliding down a playground slide"),
    ("dig", "Dig", "actions", "⛏️", "Dig", ["dig", "shovel", "sand"], "a child digging in sand with a small shovel"),
    ("pour", "Pour", "actions", "🫗", "Pour", ["pour", "fill"], "a child pouring water from a pitcher into a cup"),
    ("stir", "Stir", "actions", "🥄", "Stir", ["stir", "mix", "cooking"], "a child stirring a bowl with a wooden spoon"),
    ("mix", "Mix", "actions", "🥣", "Mix", ["mix", "blend", "combine"], "a child mixing batter in a bowl"),
    ("bake", "Bake", "actions", "🧁", "Bake", ["bake", "oven", "cookies"], "a child putting a tray of cookies into an oven"),
    ("wipe", "Wipe", "actions", "🧻", "Wipe", ["wipe", "clean", "cloth"], "a child wiping a table with a cloth"),
    ("sweep", "Sweep", "actions", "🧹", "Sweep", ["sweep", "broom", "clean"], "a child sweeping the floor with a broom"),
    ("vacuum", "Vacuum", "actions", "🧹", "Vacuum", ["vacuum", "clean", "floor"], "a child pushing a vacuum cleaner"),
    ("fold", "Fold", "actions", "👕", "Fold", ["fold", "laundry", "clothes"], "a child folding a shirt"),
    ("hang_up", "Hang Up", "actions", "🧥", "Hang up", ["hang up", "coat", "hook"], "a child hanging a coat on a hook"),
    ("pack", "Pack", "actions", "🎒", "Pack", ["pack", "backpack", "bag"], "a child putting books into a backpack"),
    ("unpack", "Unpack", "actions", "📤", "Unpack", ["unpack", "take out", "empty"], "a child taking items out of a backpack"),
    ("carry", "Carry", "actions", "📦", "Carry", ["carry", "hold", "bring"], "a child carrying a box with both arms"),
    ("lift", "Lift", "actions", "🏋️", "Lift", ["lift", "pick up", "raise"], "a child lifting a box up onto a table"),
    ("hide", "Hide", "actions", "🙈", "Hide", ["hide", "hiding", "seek"], "a child hiding behind a curtain with feet showing"),
    ("seek", "Seek", "actions", "🔎", "Seek", ["seek", "search", "look for"], "a child with a hand over their eyes counting against a tree"),
    ("chase", "Chase", "actions", "🏃", "Chase", ["chase", "tag", "run after"], "a child running after another child laughing"),
    ("race", "Race", "actions", "🏁", "Race", ["race", "run", "fast"], "two children racing toward a finish flag"),
    ("tag", "Tag", "actions", "🫳", "Tag", ["tag", "you're it", "game"], "a child tapping another child on the shoulder while running"),
    ("tickle", "Tickle", "actions", "🤭", "Tickle", ["tickle", "laugh", "silly"], "a child tickling a laughing friend"),
    ("kiss", "Kiss", "actions", "😘", "Kiss", ["kiss", "love", "smooch"], "a parent kissing a child on the forehead"),
    ("cuddle", "Cuddle", "actions", "🤗", "Cuddle", ["cuddle", "snuggle", "hug"], "a parent and child cuddling on a couch"),
    ("pet_act", "Pet", "actions", "🐶", "Pet the dog", ["pet", "stroke", "animal"], "a child gently petting a dog"),
    ("feed", "Feed", "actions", "🍼", "Feed", ["feed", "give food"], "a child feeding a dog from a bowl"),
    ("water_plants", "Water Plants", "actions", "🪴", "Water the plants", ["water plants", "garden", "watering can"], "a child watering a potted plant with a watering can"),
    ("plant", "Plant", "actions", "🌱", "Plant", ["plant", "seed", "garden"], "a child planting a seedling in soil"),
    ("rake", "Rake", "actions", "🍂", "Rake", ["rake", "leaves", "yard"], "a child raking a pile of orange leaves"),
    ("shovel_snow", "Shovel Snow", "actions", "❄️", "Shovel snow", ["shovel", "snow", "winter"], "a child shoveling snow off a path"),
    ("wash_dishes", "Wash Dishes", "actions", "🍽️", "Wash the dishes", ["wash dishes", "sink", "clean"], "a child washing a plate at a sink with bubbles"),
    ("set_table", "Set the Table", "actions", "🍽️", "Set the table", ["set table", "plates", "dinner"], "a child placing plates and forks on a table"),
    ("make_bed", "Make the Bed", "actions", "🛏️", "Make the bed", ["make bed", "blanket", "tidy"], "a child pulling a blanket neatly over a bed"),
    ("take_out_trash", "Take Out Trash", "actions", "🗑️", "Take out the trash", ["trash", "garbage", "chore"], "a child carrying a tied trash bag to a bin"),
    ("recycle", "Recycle", "actions", "♻️", "Recycle", ["recycle", "bin", "bottles"], "a child putting a plastic bottle into a blue recycling bin"),
    ("brush_hair", "Brush Hair", "actions", "💇", "Brush hair", ["brush hair", "hairbrush", "comb"], "a child brushing their hair with a hairbrush"),
    ("comb", "Comb", "actions", "🪮", "Comb", ["comb", "hair"], "a child combing their hair"),
    ("floss", "Floss", "actions", "🦷", "Floss", ["floss", "teeth", "dental"], "a child flossing their teeth"),
    ("rinse", "Rinse", "actions", "🚰", "Rinse", ["rinse", "water", "mouth"], "a child rinsing their mouth with a cup of water at a sink"),
    ("spit", "Spit", "actions", "💦", "Spit", ["spit", "sink", "toothpaste"], "a child spitting toothpaste into a sink"),
    ("blow_nose", "Blow Nose", "actions", "🤧", "Blow your nose", ["blow nose", "tissue", "nose"], "a child blowing their nose into a tissue"),
    ("cover_mouth", "Cover Mouth", "actions", "🤭", "Cover your mouth", ["cover mouth", "cough", "sneeze"], "a child coughing into their elbow"),
    ("wash_hair", "Wash Hair", "actions", "🧴", "Wash hair", ["wash hair", "shampoo", "bath"], "a child with bubbly shampoo on their head"),
    ("dry_off", "Dry Off", "actions", "🛁", "Dry off", ["dry off", "towel", "bath"], "a child drying off with a big towel"),
    ("put_on", "Put On", "actions", "👕", "Put on", ["put on", "wear", "clothes"], "a child pulling a shirt over their head"),
    ("take_off", "Take Off", "actions", "👚", "Take off", ["take off", "remove", "clothes"], "a child pulling off a sock"),
    ("zip", "Zip", "actions", "🧥", "Zip", ["zip", "zipper", "jacket"], "a child zipping up a jacket"),
    ("button", "Button", "actions", "🔘", "Button", ["button", "shirt", "fasten"], "a child buttoning a shirt"),
    ("tie_shoes", "Tie Shoes", "actions", "👟", "Tie shoes", ["tie shoes", "laces", "shoes"], "a child tying shoelaces"),
    ("buckle", "Buckle", "actions", "🔒", "Buckle up", ["buckle", "seat belt", "car"], "a child clicking a seat belt buckle"),
    ("lock", "Lock", "actions", "🔐", "Lock", ["lock", "key", "door"], "a hand turning a key in a door lock"),
    ("unlock", "Unlock", "actions", "🔓", "Unlock", ["unlock", "key", "open"], "a hand turning a key with an open padlock"),
    ("knock", "Knock", "actions", "✊", "Knock", ["knock", "door"], "a child knocking on a door"),
    ("ring", "Ring the Bell", "actions", "🔔", "Ring the doorbell", ["ring", "doorbell", "bell"], "a child pressing a doorbell"),
    ("plug_in", "Plug In", "actions", "🔌", "Plug in", ["plug in", "charge", "cord"], "a hand plugging a charger into a wall outlet"),
    ("press", "Press", "actions", "🔘", "Press", ["press", "push button", "tap"], "a finger pressing a big red button"),
    ("tap", "Tap", "actions", "👆", "Tap", ["tap", "touch", "screen"], "a finger tapping a tablet screen"),
    ("swipe", "Swipe", "actions", "👉", "Swipe", ["swipe", "screen", "slide"], "a finger swiping across a phone screen with an arrow"),
    ("type", "Type", "actions", "⌨️", "Type", ["type", "keyboard", "computer"], "a child typing on a keyboard"),
    ("scroll", "Scroll", "actions", "🖱️", "Scroll", ["scroll", "mouse", "screen"], "a finger scrolling on a tablet with up-down arrows"),
    ("take_photo", "Take a Photo", "actions", "📸", "Take a photo", ["take photo", "picture", "camera"], "a child taking a photo with a camera"),
    ("record", "Record", "actions", "🎙️", "Record", ["record", "video", "voice"], "a child speaking into a microphone with a red record dot"),
    ("call", "Call", "actions", "📞", "Call", ["call", "phone", "talk"], "a child holding a phone to their ear"),
    ("text", "Text", "actions", "💬", "Text", ["text", "message", "phone"], "a child typing a message on a phone with a speech bubble"),
    ("email", "Email", "actions", "📧", "Email", ["email", "message", "send"], "a laptop with an envelope icon on the screen"),
    ("search_act", "Search", "actions", "🔍", "Search", ["search", "look up", "google"], "a child typing into a search bar with a magnifying glass"),
    ("print", "Print", "actions", "🖨️", "Print", ["print", "printer", "paper"], "a printer printing a page"),
    ("copy", "Copy", "actions", "📄", "Copy", ["copy", "duplicate"], "two identical sheets of paper side by side, the second one with a small arrow coming from the first"),
    ("count", "Count", "actions", "🔢", "Count", ["count", "numbers", "math"], "a child counting colored blocks on fingers"),
    ("measure", "Measure", "actions", "📏", "Measure", ["measure", "ruler", "length"], "a child measuring a block with a ruler"),
    ("weigh", "Weigh", "actions", "⚖️", "Weigh", ["weigh", "scale", "heavy"], "a child standing on a bathroom scale"),
    ("sort", "Sort", "actions", "🗂️", "Sort", ["sort", "organize", "group"], "a child sorting red and blue blocks into two bins"),
    ("match", "Match", "actions", "🃏", "Match", ["match", "same", "pair"], "a child matching two identical cards"),
    ("trace", "Trace", "actions", "✏️", "Trace", ["trace", "letters", "write"], "a child tracing a dotted letter with a pencil"),
    ("erase", "Erase", "actions", "🧽", "Erase", ["erase", "eraser", "undo"], "a child erasing pencil marks with an eraser"),
    ("staple", "Staple", "actions", "📎", "Staple", ["staple", "stapler", "paper"], "a child pressing a stapler on papers"),
    ("tape", "Tape", "actions", "🩹", "Tape", ["tape", "stick", "craft"], "a child tearing a piece of tape from a dispenser"),
    ("fold_paper", "Fold Paper", "actions", "📄", "Fold the paper", ["fold paper", "origami", "craft"], "a child folding a sheet of paper in half"),
    ("stamp", "Stamp", "actions", "🖃", "Stamp", ["stamp", "ink", "craft"], "a child pressing a rubber stamp onto paper"),
    ("sculpt", "Sculpt", "actions", "🗿", "Sculpt", ["sculpt", "clay", "model"], "a child shaping clay into a figure"),
    ("string_beads", "String Beads", "actions", "📿", "String beads", ["beads", "necklace", "craft"], "a child threading colorful beads on a string"),
    ("stack", "Stack", "actions", "🧱", "Stack", ["stack", "blocks", "tower"], "a child stacking blocks into a tall tower"),
    ("knock_down", "Knock Down", "actions", "💥", "Knock it down", ["knock down", "crash", "tower"], "a child knocking over a block tower with blocks flying"),
    ("line_up_act", "Line Up", "actions", "🚶", "Line up", ["line up", "queue", "wait"], "children standing in a straight line behind each other"),
    ("sit_criss_cross", "Sit Criss-Cross", "actions", "🧘", "Sit criss-cross", ["criss cross", "sit", "carpet"], "a child sitting cross-legged on a carpet"),
    ("raise_hand", "Raise Hand", "actions", "🙋", "Raise your hand", ["raise hand", "question", "class"], "a child sitting at a desk raising a hand"),
    ("quiet_hands", "Quiet Hands", "actions", "🤲", "Quiet hands", ["quiet hands", "hands in lap", "still"], "a child sitting with hands folded in their lap"),
    ("look_at_me", "Look at Me", "actions", "👁️", "Look at me", ["look at me", "eyes", "attention"], "an adult pointing at their own eyes while a child looks up"),
    ("follow", "Follow", "actions", "🐾", "Follow", ["follow", "come along", "behind"], "a child walking behind an adult following footprints"),
    ("lead", "Lead", "actions", "🚩", "Lead", ["lead", "go first", "line leader"], "a child at the front of a line holding a small flag"),
    ("copy_me", "Copy Me", "actions", "🪞", "Copy me", ["copy me", "imitate", "do this"], "two children making the same pose facing each other"),
    ("practice", "Practice", "actions", "🔁", "Practice", ["practice", "again", "learn"], "a child at a desk drawing the same simple circle shape three times in a row on blank paper"),
    ("learn", "Learn", "actions", "🧠", "Learn", ["learn", "study", "school"], "a child reading a book with a glowing brain above"),
    ("teach", "Teach", "actions", "👩‍🏫", "Teach", ["teach", "show how", "teacher"], "an adult pointing at a board while a child watches"),
    ("remember", "Remember", "actions", "🧠", "Remember", ["remember", "recall", "memory"], "a child with a finger on their temple and a thought bubble of a photo"),
    ("forget", "Forget", "actions", "❓", "I forgot", ["forget", "forgot", "can't remember"], "a child scratching their head with an empty thought bubble"),
    ("guess", "Guess", "actions", "🎲", "Guess", ["guess", "wonder", "maybe"], "a child pointing at one of three closed cups with a question mark"),
    ("win", "Win", "actions", "🏆", "I won", ["win", "winner", "first"], "a child holding a trophy with arms up"),
    ("lose", "Lose", "actions", "😞", "I lost", ["lose", "lost", "didn't win"], "a child looking down sadly while a friend holds a trophy"),
    ("cheer", "Cheer", "actions", "📣", "Cheer", ["cheer", "hooray", "root for"], "a child cheering with pom-poms"),
    ("vote", "Vote", "actions", "🗳️", "Vote", ["vote", "choose", "raise hand"], "a child dropping a paper into a ballot box"),
    ("exercise", "Exercise", "actions", "🏃", "Exercise", ["exercise", "workout", "fitness"], "a child doing jumping jacks"),
    ("yoga", "Yoga", "actions", "🧘", "Yoga", ["yoga", "stretch", "calm"], "a child in a tree yoga pose on a mat"),
    ("nap_act", "Take a Nap", "actions", "😴", "Take a nap", ["nap", "rest", "sleep"], "a child lying on a mat with a small blanket, eyes closed"),
    ("rest", "Rest", "actions", "🛋️", "Rest", ["rest", "relax", "lie down"], "a child lying back on a couch with eyes closed"),
    ("relax", "Relax", "actions", "😌", "Relax", ["relax", "calm down", "chill"], "a child reclining in a chair with a calm smile"),
    ("meditate", "Meditate", "actions", "🧘", "Meditate", ["meditate", "calm", "breathe"], "a child sitting cross-legged with eyes closed and hands on knees"),
    ("hide_face", "Cover Eyes", "actions", "🙈", "Cover my eyes", ["cover eyes", "peekaboo", "hide"], "a child covering their eyes with both hands"),
    ("peek", "Peek", "actions", "👀", "Peek", ["peek", "look", "peekaboo"], "a child peeking through fingers"),
    ("wink", "Wink", "actions", "😉", "Wink", ["wink", "eye", "silly"], "a child winking one eye"),
    ("stick_out_tongue", "Stick Out Tongue", "actions", "😝", "Stick out tongue", ["tongue", "silly", "face"], "a child sticking out their tongue playfully"),
    ("make_face", "Make a Face", "actions", "🤪", "Make a silly face", ["silly face", "funny face"], "a child making a goofy face with crossed eyes"),
    ("pose", "Pose", "actions", "🕺", "Pose", ["pose", "picture", "strike a pose"], "a child striking a superhero pose"),
    ("fly", "Fly", "actions", "🦅", "Fly", ["fly", "wings", "airplane"], "a child with arms out pretending to fly with small clouds"),
    ("float", "Float", "actions", "🏊", "Float", ["float", "water", "pool"], "a child floating on their back in a pool"),
    ("dive", "Dive", "actions", "🤿", "Dive", ["dive", "jump in", "pool"], "a child diving into a pool"),
    ("splash", "Splash", "actions", "💦", "Splash", ["splash", "water", "puddle"], "a child jumping into a puddle with water splashing"),
    ("sled", "Sled", "actions", "🛷", "Sled", ["sled", "snow", "winter"], "a child riding a sled down a snowy hill"),
    ("skate", "Skate", "actions", "⛸️", "Skate", ["skate", "ice skate", "rollerblade"], "a child ice skating with arms out"),
    ("ski", "Ski", "actions", "⛷️", "Ski", ["ski", "snow", "mountain"], "a child skiing down a slope"),
    ("surf", "Surf", "actions", "🏄", "Surf", ["surf", "wave", "beach"], "a child riding a surfboard on a wave"),
    ("fish_act", "Go Fishing", "actions", "🎣", "Go fishing", ["fishing", "fish", "rod"], "a child holding a fishing rod with a fish on the line"),
    ("camp", "Camp", "actions", "🏕️", "Go camping", ["camp", "camping", "tent"], "a child sitting by a tent and a campfire"),
    ("hike", "Hike", "actions", "🥾", "Go hiking", ["hike", "walk", "trail"], "a child hiking on a trail with a backpack and walking stick"),
    ("bowl_act", "Bowl", "actions", "🎳", "Go bowling", ["bowling", "bowl", "pins"], "a child rolling a bowling ball toward pins"),
    ("golf", "Golf", "actions", "⛳", "Play golf", ["golf", "putt", "club"], "a child swinging a golf club at a ball"),
    ("shoot_hoops", "Shoot Hoops", "actions", "🏀", "Shoot hoops", ["basketball", "hoops", "shoot"], "a child throwing a basketball toward a hoop"),
    ("hit", "Hit", "actions", "🏏", "Hit", ["hit", "bat", "swing"], "a child swinging a baseball bat at a ball"),
    ("serve", "Serve", "actions", "🏐", "Serve", ["serve", "volleyball", "tennis"], "a child serving a volleyball"),
    ("score", "Score", "actions", "🥅", "Score", ["score", "goal", "point"], "a soccer ball going into a net with a child celebrating"),
    ("pass", "Pass", "actions", "🤾", "Pass", ["pass", "throw to", "give"], "a child passing a ball to a teammate"),
    ("juggle", "Juggle", "actions", "🤹", "Juggle", ["juggle", "balls", "circus"], "a child juggling three colored balls"),
    ("perform", "Perform", "actions", "🎭", "Perform", ["perform", "show", "stage"], "a child taking a bow with arms spread wide, small yellow stars around them"),
    ("act", "Act", "actions", "🎬", "Act", ["act", "pretend", "play"], "a child wearing a paper crown and a cape striking a dramatic pose with one arm raised"),
    ("play_instrument", "Play Music", "actions", "🎸", "Play music", ["play instrument", "music", "guitar"], "a child strumming a guitar with music notes"),
    ("drum", "Drum", "actions", "🥁", "Drum", ["drum", "beat", "music"], "a child hitting a drum with sticks"),
    ("play_piano", "Play Piano", "actions", "🎹", "Play piano", ["piano", "keys", "music"], "a child playing a piano"),
]
